export const chinaCategories = [
  { id: 'imperial',  name: 'Imperial Dynasties',      color: '#EAB308' },
  { id: 'culture',   name: 'Philosophy & Culture',    color: '#10B981' },
  { id: 'wars',      name: 'Wars & Unification',      color: '#EF4444' },
  { id: 'modern',    name: 'Modern China',            color: '#3B82F6' },
];

export const chinaItems = [
  {
    id: 'xia-shang-zhou',
    name: 'Xia–Shang–Zhou Dynasties',
    start: -2100, end: -221,
    region: 'imperial',
    icon: '🏺',
    description: 'China\'s formative era. The Xia is the first recorded dynasty; the Shang develops China\'s early writing system and bronze casting. The Zhou era produces Confucius, Laozi, and the Hundred Schools of Thought. It ends with the violent Warring States period.',
    periods: [
      { name: 'Xia Dynasty', start: -2100, end: -1600 },
      { name: 'Shang Dynasty', start: -1600, end: -1046 },
      { name: 'Western Zhou', start: -1046, end: -771 },
      { name: 'Eastern Zhou', start: -771, end: -221 },
    ],
  },
  {
    id: 'confucianism-taoism',
    name: 'Hundred Schools of Thought',
    start: -551, end: -221,
    region: 'culture',
    icon: '☯️',
    description: 'During the chaotic Warring States period, China\'s greatest philosophical traditions emerge: Confucius founds Confucianism, Laozi inspires Taoism, Mozi advocates universal love, and Legalism shapes the Qin state. This explosion of ideas shapes Chinese civilisation for two millennia.',
    periods: [],
  },
  {
    id: 'qin-unification',
    name: 'Qin Unification',
    start: -221, end: -206,
    region: 'wars',
    icon: '🐉',
    description: 'Qin Shi Huang conquers the warring states and becomes China\'s first emperor. He standardises writing, weights, and measures; builds the early Great Wall; and creates the famous Terracotta Army. His brutal Legalist regime lasts only 15 years but leaves an indelible mark.',
    periods: [],
  },
  {
    id: 'han-dynasty',
    name: 'Han Dynasty',
    start: -206, end: 220,
    region: 'imperial',
    icon: '📜',
    description: 'The Han is China\'s golden age, roughly contemporary with Rome. Confucianism becomes state ideology, the Silk Road opens trade with the West, papermaking is invented, and the Chinese identity itself — Han — takes its name from this dynasty.',
    periods: [
      { name: 'Western Han', start: -206, end: 9 },
      { name: 'Eastern Han', start: 25, end: 220 },
    ],
  },
  {
    id: 'three-kingdoms-jin',
    name: 'Three Kingdoms & Jin',
    start: 220, end: 420,
    region: 'wars',
    icon: '⚔️',
    description: 'The fall of Han leads to a century of war as three kingdoms — Wei, Shu, and Wu — battle for supremacy. The period is immortalised in the classic novel "Romance of the Three Kingdoms." Brief reunification under Jin is followed by further fragmentation.',
    periods: [
      { name: 'Three Kingdoms', start: 220, end: 280 },
      { name: 'Jin Dynasty', start: 280, end: 420 },
    ],
  },
  {
    id: 'sui-tang',
    name: 'Sui & Tang Dynasties',
    start: 581, end: 907,
    region: 'imperial',
    icon: '🏯',
    description: 'The Sui briefly reunifies China and builds the Grand Canal. The Tang is China\'s most cosmopolitan dynasty — a cultural zenith of poetry, painting, Buddhism, and trade. Chang\'an (Xi\'an) is the world\'s largest city and a crossroads of Silk Road civilisations.',
    periods: [
      { name: 'Sui Dynasty', start: 581, end: 618 },
      { name: 'Tang Dynasty', start: 618, end: 907 },
    ],
  },
  {
    id: 'song-dynasty',
    name: 'Song Dynasty',
    start: 960, end: 1279,
    region: 'imperial',
    icon: '📖',
    description: 'The Song presides over the world\'s most advanced economy and a revolution in technology: gunpowder weapons, printing, the compass, and paper money all develop here. Neo-Confucianism is codified. Despite losing the north to the Jurchen Jin, the Southern Song flourishes.',
    periods: [
      { name: 'Northern Song', start: 960, end: 1127 },
      { name: 'Southern Song', start: 1127, end: 1279 },
    ],
  },
  {
    id: 'yuan-mongol',
    name: 'Yuan Dynasty — Mongol Rule',
    start: 1271, end: 1368,
    region: 'imperial',
    icon: '🐎',
    description: 'Kublai Khan\'s Mongol conquest establishes the Yuan dynasty, the first foreign rule over all China. Marco Polo visits the court. The Mongols connect China more firmly to the rest of Eurasia but face constant Chinese resistance and economic mismanagement.',
    periods: [],
  },
  {
    id: 'ming-dynasty',
    name: 'Ming Dynasty',
    start: 1368, end: 1644,
    region: 'imperial',
    icon: '🏮',
    description: 'The Han Chinese Ming dynasty expels the Mongols and rebuilds China. The Forbidden City and the final Great Wall are built. Zheng He leads the world\'s greatest fleet on seven voyages across Asia and Africa. Later isolationism and economic crisis lead to the dynasty\'s fall.',
    periods: [
      { name: 'Early Ming', start: 1368, end: 1424 },
      { name: 'Maritime Voyages', start: 1405, end: 1433 },
      { name: 'Late Ming', start: 1433, end: 1644 },
    ],
  },
  {
    id: 'qing-dynasty',
    name: 'Qing Dynasty',
    start: 1644, end: 1912,
    region: 'imperial',
    icon: '🐉',
    description: 'The Manchu Qing is China\'s last dynasty and at its height the world\'s largest economy. It expands China to its modern borders. The 19th century brings the Opium Wars, Unequal Treaties with Western powers, the Taiping Rebellion (20 million dead), and the slow collapse of imperial rule.',
    periods: [
      { name: 'Conquest & Consolidation', start: 1644, end: 1735 },
      { name: 'Height of Power', start: 1735, end: 1839 },
      { name: 'Decline & Fall', start: 1839, end: 1912 },
    ],
  },
  {
    id: 'republic-of-china',
    name: 'Republic of China',
    start: 1912, end: 1949,
    region: 'modern',
    icon: '⚡',
    description: 'Sun Yat-sen\'s revolution ends imperial China. The republic is plagued by warlordism, Japanese invasion (1937–1945, killing 15–20 million Chinese), and civil war between the Nationalists (KMT) and Communists (CCP). The CCP wins in 1949; the KMT retreats to Taiwan.',
    periods: [
      { name: 'Warlord Era', start: 1916, end: 1928 },
      { name: 'Nanjing Decade', start: 1928, end: 1937 },
      { name: 'War with Japan', start: 1937, end: 1945 },
      { name: 'Civil War', start: 1945, end: 1949 },
    ],
  },
  {
    id: 'peoples-republic',
    name: 'People\'s Republic of China',
    start: 1949, end: 2025,
    region: 'modern',
    icon: '🇨🇳',
    description: 'Mao Zedong proclaims the People\'s Republic in 1949. The Great Leap Forward and Cultural Revolution cause tens of millions of deaths. Deng Xiaoping\'s 1978 reforms launch the most rapid economic development in history, transforming China into the world\'s second-largest economy.',
    periods: [
      { name: 'Mao Era', start: 1949, end: 1976 },
      { name: 'Reform & Opening', start: 1978, end: 2012 },
      { name: 'Xi Jinping Era', start: 2012, end: 2025 },
    ],
  },
];
