export const franceCategories = [
  { id: 'ancient',    name: 'Ancient & Medieval',      color: '#78716C' },
  { id: 'monarchy',   name: 'Monarchy',                 color: '#C084FC' },
  { id: 'republics',  name: 'Republics & Empires',      color: '#3B82F6' },
  { id: 'conflicts',  name: 'Major Conflicts',          color: '#EF4444' },
  { id: 'culture',    name: 'Culture & Enlightenment',  color: '#10B981' },
];

export const franceItems = [
  {
    id: 'gaul-roman',
    name: 'Gaul & Roman Gaul',
    start: -51, end: 486,
    region: 'ancient',
    icon: '🏛️',
    description: 'Julius Caesar\'s conquest of Gaul (58–51 BCE) brings the region firmly into the Roman world. For over five centuries, Roman Gaul is one of the most prosperous provinces in the empire, giving France its language roots, legal traditions, and many of its oldest cities.',
    periods: [
      { name: 'Gallic Wars', start: -58, end: -51 },
      { name: 'Roman Gaul', start: -51, end: 486 },
    ],
  },
  {
    id: 'frankish-kingdoms',
    name: 'Frankish Kingdoms',
    start: 486, end: 987,
    region: 'ancient',
    icon: '⚔️',
    description: 'Clovis unites the Frankish tribes and defeats the last Roman governor in 486, founding the Merovingian dynasty. The Carolingians under Charlemagne build a vast empire. After its division in 843, West Francia becomes the kernel of modern France.',
    periods: [
      { name: 'Merovingians', start: 486, end: 751 },
      { name: 'Carolingians', start: 751, end: 987 },
    ],
  },
  {
    id: 'capetian',
    name: 'Capetian Dynasty',
    start: 987, end: 1328,
    region: 'monarchy',
    icon: '👑',
    description: 'Hugh Capet founds the dynasty that will rule France for 341 years. Under the Capetians, the French monarchy gradually extends its authority, the Gothic cathedral tradition flourishes, and Paris grows into Europe\'s greatest city.',
    periods: [],
  },
  {
    id: 'valois-hundred-years',
    name: 'Valois Dynasty & Hundred Years War',
    start: 1328, end: 1589,
    region: 'monarchy',
    icon: '🏹',
    description: 'The Valois kings fight the prolonged Hundred Years War against England (1337–1453), during which Joan of Arc galvanises French resistance. The war ends with England expelled from France. Religious civil wars between Catholics and Huguenots tear the kingdom apart in the late 16th century.',
    periods: [
      { name: 'Hundred Years War', start: 1337, end: 1453 },
      { name: 'Renaissance Valois', start: 1453, end: 1562 },
      { name: 'Wars of Religion', start: 1562, end: 1589 },
    ],
  },
  {
    id: 'bourbon-monarchy',
    name: 'Bourbon Dynasty',
    start: 1589, end: 1792,
    region: 'monarchy',
    icon: '🌸',
    description: 'Henry IV ends the Wars of Religion and founds the Bourbon dynasty. Louis XIV — the Sun King — builds Versailles and makes France the cultural and military superpower of Europe. Louis XVI\'s financial crisis and autocracy ignite the Revolution.',
    periods: [
      { name: 'Henry IV & Richelieu', start: 1589, end: 1661 },
      { name: 'Sun King Louis XIV', start: 1661, end: 1715 },
      { name: 'Enlightenment & Crisis', start: 1715, end: 1792 },
    ],
  },
  {
    id: 'revolution-republic',
    name: 'Revolution & First Republic',
    start: 1789, end: 1804,
    region: 'republics',
    icon: '🗽',
    description: 'The storming of the Bastille in 1789 launches the most consequential revolution in modern history. The monarchy is abolished, the king guillotined, and the Declaration of the Rights of Man proclaimed. The Terror follows, then the Directory, before Napoleon seizes power.',
    periods: [
      { name: 'Constitutional Monarchy', start: 1789, end: 1792 },
      { name: 'The Terror', start: 1793, end: 1794 },
      { name: 'Directory', start: 1795, end: 1799 },
      { name: 'Consulate', start: 1799, end: 1804 },
    ],
  },
  {
    id: 'napoleon-empire',
    name: 'First Empire — Napoleon',
    start: 1804, end: 1815,
    region: 'republics',
    icon: '⚔️',
    description: 'Napoleon Bonaparte crowns himself Emperor and reshapes Europe through military genius and legal reform. The Napoleonic Code becomes the basis of civil law across much of the world. Overreach in Russia and the Peninsular War ultimately lead to defeat at Waterloo.',
    periods: [
      { name: 'Napoleonic Wars', start: 1804, end: 1812 },
      { name: 'Decline & Fall', start: 1812, end: 1815 },
    ],
  },
  {
    id: 'restoration-orleans',
    name: 'Restoration & July Monarchy',
    start: 1815, end: 1870,
    region: 'monarchy',
    icon: '🌺',
    description: 'The Bourbons are briefly restored, then overthrown again in 1830 in favour of the more liberal Louis-Philippe. The Second Republic of 1848 is swiftly replaced by Napoleon III\'s Second Empire, which modernises Paris but ends in defeat in the Franco-Prussian War.',
    periods: [
      { name: 'Bourbon Restoration', start: 1815, end: 1830 },
      { name: 'July Monarchy', start: 1830, end: 1848 },
      { name: 'Second Republic', start: 1848, end: 1852 },
      { name: 'Second Empire', start: 1852, end: 1870 },
    ],
  },
  {
    id: 'third-republic',
    name: 'Third Republic',
    start: 1870, end: 1940,
    region: 'republics',
    icon: '🗼',
    description: 'France\'s longest-lasting republic, born from defeat in the Franco-Prussian War. It oversees the Belle Époque, the Dreyfus Affair, colonial expansion, WWI (losing 1.4 million soldiers), the art movements of Paris, and finally falls to Nazi Germany in 1940.',
    periods: [
      { name: 'Early Republic', start: 1870, end: 1914 },
      { name: 'World War I', start: 1914, end: 1918 },
      { name: 'Interwar', start: 1918, end: 1940 },
    ],
  },
  {
    id: 'wwii-vichy',
    name: 'WWII & Vichy France',
    start: 1940, end: 1944,
    region: 'conflicts',
    icon: '🪖',
    description: 'Germany invades and France falls in just six weeks in 1940. The collaborationist Vichy regime under Pétain governs unoccupied France, while de Gaulle leads the Free French from London. The D-Day landings of 1944 and the Resistance liberate the country.',
    periods: [],
  },
  {
    id: 'fourth-fifth-republic',
    name: 'Fourth & Fifth Republics',
    start: 1944, end: 2025,
    region: 'republics',
    icon: '🇫🇷',
    description: 'Post-war France rebuilds under American aid, undergoes rapid economic modernisation (the Trente Glorieuses), fights colonial wars in Indochina and Algeria, and under de Gaulle\'s Fifth Republic becomes a nuclear power and founding member of the European Union.',
    periods: [
      { name: 'Fourth Republic', start: 1944, end: 1958 },
      { name: 'De Gaulle', start: 1958, end: 1969 },
      { name: 'Modern France', start: 1969, end: 2025 },
    ],
  },
  {
    id: 'french-culture',
    name: 'French Culture & Enlightenment',
    start: 1637, end: 2025,
    region: 'culture',
    icon: '🎨',
    description: 'France has been the world\'s cultural capital for centuries: Descartes and the Enlightenment philosophes, Impressionism, Existentialism, the French cinema New Wave, haute cuisine, and fashion. French was the language of European diplomacy for 300 years.',
    periods: [
      { name: 'Classicism & Enlightenment', start: 1637, end: 1789 },
      { name: 'Romanticism & Realism', start: 1789, end: 1900 },
      { name: 'Modernism & Beyond', start: 1900, end: 2025 },
    ],
  },
];
