export const indiaCategories = [
  { id: 'ancient',    name: 'Ancient Civilisations',  color: '#78716C' },
  { id: 'imperial',   name: 'Imperial Dynasties',     color: '#EAB308' },
  { id: 'medieval',   name: 'Medieval Kingdoms',      color: '#C084FC' },
  { id: 'colonial',   name: 'Colonial Period',        color: '#EF4444' },
  { id: 'modern',     name: 'Modern India',           color: '#10B981' },
];

export const indiaItems = [
  {
    id: 'indus-valley',
    name: 'Indus Valley Civilisation',
    start: -2600, end: -1900,
    region: 'ancient',
    icon: '🏙️',
    description: 'One of the world\'s earliest and most sophisticated urban civilisations flourishes in the Indus and Saraswati river valleys. Mohenjo-daro and Harappa feature advanced drainage systems, standardised weights and measures, multi-storey buildings, and a still-undeciphered script. At its peak, the IVC may have had more people than contemporary Mesopotamia and Egypt combined.',
    periods: [
      { name: 'Early Harappan', start: -3300, end: -2600 },
      { name: 'Mature Harappan', start: -2600, end: -1900 },
      { name: 'Late Harappan', start: -1900, end: -1300 },
    ],
  },
  {
    id: 'vedic-period',
    name: 'Vedic Period',
    start: -1500, end: -500,
    region: 'ancient',
    icon: '🕉️',
    description: 'Indo-Aryan migrations bring Sanskrit, the Vedic religion, and the caste system to northern India. The Rigveda — one of the world\'s oldest religious texts — is composed. Epic literature (Mahabharata, Ramayana) takes shape. The philosophical Upanishads lay the groundwork for Hinduism and Buddhism.',
    periods: [
      { name: 'Early Vedic', start: -1500, end: -1000 },
      { name: 'Later Vedic', start: -1000, end: -600 },
      { name: 'Mahajanapadas', start: -600, end: -321 },
    ],
  },
  {
    id: 'maurya-empire',
    name: 'Maurya Empire',
    start: -322, end: -185,
    region: 'imperial',
    icon: '☸️',
    description: 'Chandragupta Maurya unifies most of the Indian subcontinent for the first time. His grandson Ashoka, after the horrific Kalinga War, converts to Buddhism and spreads its message of non-violence through rock edicts across his empire. The Maurya capital Pataliputra is one of the ancient world\'s greatest cities.',
    periods: [
      { name: 'Chandragupta', start: -322, end: -297 },
      { name: 'Ashoka', start: -268, end: -232 },
      { name: 'Decline', start: -232, end: -185 },
    ],
  },
  {
    id: 'gupta-empire',
    name: 'Gupta Empire',
    start: 320, end: 550,
    region: 'imperial',
    icon: '🌟',
    description: 'The Gupta period is India\'s golden age. Mathematics flourishes — zero, the decimal system, and the concept of infinity are developed. Kalidasa writes his masterpieces. Astronomy, medicine, and metallurgy reach heights not surpassed for centuries. The iron pillar of Delhi has stood rust-free for 1,600 years.',
    periods: [
      { name: 'Golden Age', start: 320, end: 467 },
      { name: 'Decline', start: 467, end: 550 },
    ],
  },
  {
    id: 'delhi-sultanate',
    name: 'Delhi Sultanate',
    start: 1206, end: 1526,
    region: 'medieval',
    icon: '🕌',
    description: 'Successive Islamic dynasties rule northern India from Delhi, repelling the Mongol invasions and sponsoring a rich Indo-Islamic synthesis in art and architecture. The Qutub Minar, built by the first sultan, still stands. This period introduces Persian as India\'s court language.',
    periods: [
      { name: 'Slave Dynasty', start: 1206, end: 1290 },
      { name: 'Khilji & Tughlaq', start: 1290, end: 1414 },
      { name: 'Sayyid & Lodi', start: 1414, end: 1526 },
    ],
  },
  {
    id: 'mughal-empire',
    name: 'Mughal Empire',
    start: 1526, end: 1857,
    region: 'imperial',
    icon: '🏯',
    description: 'Babur\'s victory at Panipat establishes the Mughal Empire, which at its height under Akbar and Aurangzeb controls most of the subcontinent. Akbar\'s policy of religious tolerance, the Taj Mahal, and a sophisticated bureaucracy mark the empire\'s peak. The 18th century decline leaves a power vacuum filled by the British.',
    periods: [
      { name: 'Babur to Akbar', start: 1526, end: 1605 },
      { name: 'Jahangir to Shah Jahan', start: 1605, end: 1658 },
      { name: 'Aurangzeb', start: 1658, end: 1707 },
      { name: 'Decline', start: 1707, end: 1857 },
    ],
  },
  {
    id: 'maratha-empire',
    name: 'Maratha Empire',
    start: 1674, end: 1818,
    region: 'medieval',
    icon: '⚔️',
    description: 'Shivaji Maharaj founds the Maratha Empire, which grows to challenge Mughal dominance and becomes the largest power in 18th-century India. At its height the Maratha Confederacy controls much of the subcontinent, finally falling to British military power in the Anglo-Maratha Wars.',
    periods: [
      { name: 'Shivaji\'s Kingdom', start: 1674, end: 1707 },
      { name: 'Maratha Confederacy', start: 1707, end: 1818 },
    ],
  },
  {
    id: 'british-raj',
    name: 'British Raj',
    start: 1858, end: 1947,
    region: 'colonial',
    icon: '🏴',
    description: 'After the 1857 uprising, the British Crown assumes direct rule from the East India Company. The Raj builds railways and telegraphs but exploits India\'s resources and deindustrialises its economy. The independence movement grows from Congress Party founding (1885) through Gandhi\'s campaigns of non-violent resistance.',
    periods: [
      { name: 'Crown Rule', start: 1858, end: 1900 },
      { name: 'Independence Movement', start: 1900, end: 1942 },
      { name: 'Quit India & Partition', start: 1942, end: 1947 },
    ],
  },
  {
    id: 'republic-india',
    name: 'Republic of India',
    start: 1947, end: 2025,
    region: 'modern',
    icon: '🇮🇳',
    description: 'India gains independence on 15 August 1947 but is simultaneously partitioned into India and Pakistan amid sectarian violence killing up to two million. Nehru\'s secular socialist India navigates the Cold War through non-alignment. The 1991 economic liberalisation transforms India into one of the world\'s fastest-growing economies.',
    periods: [
      { name: 'Nehru Era', start: 1947, end: 1964 },
      { name: 'Indira Gandhi', start: 1966, end: 1984 },
      { name: 'Economic Liberalisation', start: 1991, end: 2014 },
      { name: 'Modi Era', start: 2014, end: 2025 },
    ],
  },
];
