export const indonesiaCategories = [
  { id: 'ancient',      name: 'Ancient & Hindu-Buddhist', color: '#F59E0B' },
  { id: 'islamic',      name: 'Islamic Sultanates',       color: '#10B981' },
  { id: 'colonial',     name: 'Dutch Colonial Era',       color: '#78716C' },
  { id: 'independence', name: 'Independence Struggle',    color: '#EF4444' },
  { id: 'modern',       name: 'Modern Indonesia',         color: '#3B82F6' },
];

export const indonesiaItems = [
  {
    id: 'early-kingdoms',
    name: 'Early Kingdoms & Austronesian Settlement',
    start: -2500, end: 650,
    region: 'ancient',
    icon: '🏺',
    description: "The Indonesian archipelago — 17,500 islands stretching 5,100km — was settled by Austronesian peoples migrating from Taiwan through the Philippines (c. 4000–2000 BCE). Homo floresiensis ('Flores Man') — a separate hominin species — inhabited the islands until approximately 50,000 years ago. Indian traders and Brahmin priests brought Hinduism and Buddhism from the 1st century CE; Sanskrit inscriptions appear from the 4th century. Kutai Kingdom in Borneo (c. 4th century) is Indonesia's oldest known Hindu polity. Early wet-rice agriculture made Java — with its fertile volcanic soils — the archipelago's demographic and political centre.",
    periods: [
      { name: 'Austronesian Settlement', start: -2500, end: -500 },
      { name: 'Indian Cultural Influence', start: 100, end: 650 },
    ],
  },
  {
    id: 'srivijaya',
    name: 'Srivijaya Empire',
    start: 650, end: 1377,
    region: 'ancient',
    icon: '⛵',
    description: "Srivijaya — a Mahayana Buddhist maritime empire based in Palembang, Sumatra — dominated the western Indonesian archipelago and Malay Peninsula from the 7th to 13th centuries. By controlling the Straits of Malacca (the world's most important maritime chokepoint), Srivijaya extracted tolls from all ships passing between the Indian Ocean and South China Sea. It was a major centre of Buddhist learning; Chinese pilgrim Yijing studied there for years on his way to India. Arab, Indian, Chinese, and Southeast Asian merchants all traded in its ports. Srivijaya declined as regional powers — the Chola kingdom of South India raided it (1025), and the rise of rival Javanese kingdoms — undermined its supremacy.",
    periods: [
      { name: 'Srivijaya Ascendancy', start: 650, end: 900 },
      { name: 'Srivijaya at Height', start: 900, end: 1100 },
      { name: 'Decline', start: 1100, end: 1377 },
    ],
  },
  {
    id: 'majapahit',
    name: 'Majapahit Empire',
    start: 1293, end: 1527,
    region: 'ancient',
    icon: '🏰',
    description: "Majapahit (1293–1527), based in East Java, was the last and greatest Hindu-Buddhist empire in Southeast Asia. Under Prime Minister Gajah Mada (c. 1290–1364), it claimed suzerainty over much of the Indonesian archipelago, parts of the Malay Peninsula, and possibly the Philippines. Gajah Mada's 'Palapa Oath' — to abstain from spices until he had unified the archipelago — became a nationalist symbol; the first Indonesian satellite (1976) was named Palapa. Majapahit's court produced refined literary and artistic culture. The temples of Borobudur (built c. 800 CE, the world's largest Buddhist monument) and Prambanan (10th century Hindu complex) were already ancient monuments during Majapahit's height. Islam spread through coastal ports; Majapahit gradually declined as Islamic sultanates rose.",
    periods: [
      { name: 'Early Majapahit', start: 1293, end: 1350 },
      { name: 'Gajah Mada\'s Expansion', start: 1350, end: 1389 },
      { name: 'Decline & Fall', start: 1389, end: 1527 },
    ],
  },
  {
    id: 'islamic-sultanates',
    name: 'Islamic Sultanates',
    start: 1200, end: 1700,
    region: 'islamic',
    icon: '🕌',
    description: "Islam arrived in the Indonesian archipelago through Arab and Indian Muslim traders from the 9th century. The first Islamic kingdoms emerged on the coasts of northern Sumatra (Samudra Pasai, c. 1267). The Sultanate of Malacca (1400–1511), controlling the Malacca Strait, became a major centre of Islam's spread; when the Portuguese captured it (1511), Muslim merchants dispersed to Aceh, Demak, and Banten, accelerating Islam's spread. Demak (Java's first Islamic sultanate) ended Majapahit's rule. The Sultanate of Mataram unified much of Java in the 17th century. The Ternate and Tidore sultanates in the Maluku islands ('Spice Islands') controlled the world's only source of cloves and nutmeg — making them among the most commercially valuable territories on earth and drawing European powers into competition.",
    periods: [
      { name: 'Early Islamic Kingdoms', start: 1200, end: 1450 },
      { name: 'Spread of Islam Across Archipelago', start: 1450, end: 1600 },
      { name: 'Mataram & Spice Sultanates', start: 1600, end: 1700 },
    ],
  },
  {
    id: 'voc',
    name: 'Dutch East India Company (VOC)',
    start: 1602, end: 1799,
    region: 'colonial',
    icon: '⚓',
    description: "The Dutch East India Company (Vereenigde Oost-Indische Compagnie, VOC) was founded in 1602 as history's first publicly traded joint-stock company with quasi-governmental powers — it could wage war, negotiate treaties, mint coins, and establish colonies. It established Batavia (Jakarta) in 1619 under Jan Pieterszoon Coen, who massacred the local population. The VOC's quest for nutmeg monopoly led to the Banda Islands massacre (1621) — virtually the entire population of the Banda Islands was killed or enslaved to ensure Dutch control of the world's only nutmeg source. The VOC became enormously profitable — paying 40% annual dividends — but accumulated debts, corruption, and competition eventually bankrupted it. The VOC was dissolved on December 31, 1799; its possessions transferred to the Dutch state.",
    periods: [
      { name: 'VOC Establishment & Batavia', start: 1602, end: 1650 },
      { name: 'VOC Height & Spice Monopoly', start: 1650, end: 1720 },
      { name: 'VOC Decline & Bankruptcy', start: 1720, end: 1799 },
    ],
  },
  {
    id: 'dutch-colonial',
    name: 'Dutch East Indies',
    start: 1800, end: 1942,
    region: 'colonial',
    icon: '🏛️',
    description: "The Netherlands took direct control after VOC bankruptcy, creating the Dutch East Indies. The Cultivation System (cultuurstelsel, 1830–1870) required Indonesian farmers to devote a fifth of their land (or 60 days' labour) to export crops for the Dutch government — generating enormous profits for the Netherlands but causing famines in Java. The Dutch-Aceh War (1873–1904) — the Netherlands' longest and costliest colonial conflict — eventually subjugated the fiercely resistant Acehnese. The early 20th century brought the 'Ethical Policy' (infrastructure, education, limited welfare) alongside continued suppression of independence movements. Budi Utomo (1908) — the first nationalist organisation — marked the awakening of Indonesian nationalism. Sukarno (born 1901) became the dominant nationalist voice; he and other leaders were repeatedly arrested.",
    periods: [
      { name: 'Cultivation System', start: 1830, end: 1870 },
      { name: 'Aceh War & Full Control', start: 1873, end: 1914 },
      { name: 'Nationalist Awakening', start: 1908, end: 1942 },
    ],
  },
  {
    id: 'japanese-independence',
    name: 'Japanese Occupation & Independence',
    start: 1942, end: 1950,
    region: 'independence',
    icon: '⚡',
    description: "Japan swept through the Dutch East Indies in early 1942, defeating the Dutch in eight days. Japanese occupation (1942–45) dismantled Dutch authority and empowered Indonesian nationalists — the Japanese trained an Indonesian military force (PETA) and allowed nationalist organisation. The occupation also brought forced labour (romusha) that killed hundreds of thousands. When Japan surrendered on August 15, 1945, Sukarno (pressured by younger nationalists) proclaimed Indonesian independence on August 17, 1945. The Dutch refused to accept decolonisation, launching two 'Police Actions' (1947–48). The Indonesian National Revolution combined guerrilla warfare with international diplomacy. International pressure — including US pressure on the Netherlands — and the United Nations' intervention forced Dutch recognition of Indonesian sovereignty on December 27, 1949.",
    periods: [
      { name: 'Japanese Occupation', start: 1942, end: 1945 },
      { name: 'Independence Proclaimed', start: 1945, end: 1946 },
      { name: 'National Revolution', start: 1946, end: 1950 },
    ],
  },
  {
    id: 'sukarno-suharto',
    name: 'Sukarno & Suharto Eras',
    start: 1950, end: 1998,
    region: 'modern',
    icon: '🌴',
    description: "Sukarno's 'Guided Democracy' (from 1957) was an authoritarian nationalism that balanced the Army and Communist Party (PKI) against each other. Indonesia was a founding voice of the Non-Aligned Movement; the Bandung Conference (1955) gathered 29 Asian and African nations. An alleged communist coup attempt on September 30, 1965, triggered a counter-coup by General Suharto. In the subsequent anti-communist massacres (1965–66), an estimated 500,000–1,000,000 Indonesians — communists, ethnic Chinese, and others — were killed in one of the 20th century's worst mass killings. Suharto's 'New Order' (1966–1998) was a developmentalist authoritarian state: GDP grew rapidly (the 'Indonesian miracle'), but built on corruption, cronyism, and military repression. East Timor was brutally invaded and annexed in 1975 (Indonesian withdrawal in 1999; independence 2002).",
    periods: [
      { name: 'Sukarno Era', start: 1950, end: 1966 },
      { name: 'Suharto New Order', start: 1966, end: 1997 },
      { name: 'Asian Financial Crisis & Fall', start: 1997, end: 1998 },
    ],
  },
  {
    id: 'democratic-indonesia',
    name: 'Democratic Indonesia (Reformasi)',
    start: 1998, end: 2025,
    region: 'modern',
    icon: '🇮🇩',
    description: "The 1997–98 Asian financial crisis devastated Indonesia; mass protests forced Suharto's resignation (May 21, 1998) after 32 years. 'Reformasi' (Reform) opened a democratic era: competitive elections, decentralisation of power to regions, free press, and civilian control of the military. After Habibie (1998–99), Abdurrahman Wahid, and Megawati Sukarnoputri, Susilo Bambang Yudhoyono (2004–2014) and Joko 'Jokowi' Widodo (2014–2024) provided stable democratic government. Indonesia became the world's third-largest democracy and the largest Muslim-majority democracy. East Timor's independence (2002) and the 2004 Indian Ocean tsunami (170,000 Indonesian dead) were defining moments. Indonesia announced plans to relocate its capital from Jakarta to 'Nusantara' in East Kalimantan (due to Jakarta's subsidence and congestion). Prabowo Subianto, Suharto's son-in-law, was elected president in 2024.",
    periods: [
      { name: 'Reformasi & Early Democracy', start: 1998, end: 2004 },
      { name: 'SBY & Democratic Consolidation', start: 2004, end: 2014 },
      { name: 'Jokowi Era & New Capital', start: 2014, end: 2025 },
    ],
  },
];
