export const nigeriaCategories = [
  { id: 'ancient',      name: 'Ancient Cultures',        color: '#F59E0B' },
  { id: 'medieval',     name: 'Medieval Kingdoms',       color: '#C084FC' },
  { id: 'colonial',     name: 'Colonial Period',         color: '#78716C' },
  { id: 'independence', name: 'Independence Era',        color: '#3B82F6' },
  { id: 'modern',       name: 'Modern Nigeria',          color: '#10B981' },
];

export const nigeriaItems = [
  {
    id: 'nok-culture',
    name: 'Nok Culture & Iron Age',
    start: -1500, end: 300,
    region: 'ancient',
    icon: '🏺',
    description: "The Nok culture (c. 1500 BCE–300 CE) produced Sub-Saharan Africa's earliest known terracotta sculpture — naturalistic human and animal figures of extraordinary sophistication. Named for the village where fragments were first found (1943), Nok artisans also smelted iron by at least 500 BCE, making them among the earliest iron-users in Africa. The Nok people were the cultural ancestors of many Nigerian peoples. Their disappearance remains unexplained — possibly drought, disease, or population dispersal — but their artistic and technological legacy endured in subsequent Nigerian cultures.",
    periods: [
      { name: 'Early Nok Culture', start: -1500, end: -500 },
      { name: 'Iron Age Nok', start: -500, end: 300 },
    ],
  },
  {
    id: 'benin-kingdom',
    name: 'Kingdom of Benin & Yoruba States',
    start: 900, end: 1897,
    region: 'medieval',
    icon: '🦁',
    description: "The Kingdom of Benin (centred in present-day Edo State) was one of Africa's most sophisticated pre-colonial states. The Oba (king) presided over an elaborate court culture; Benin's bronze-casters produced the famous Benin Bronzes — over a thousand plaques and sculptures depicting court life with extraordinary realism and artistry. These were looted by a British punitive expedition in 1897 and are now at the centre of an international repatriation debate. Benin's oral tradition preserves over 300 years of dynastic history. The Yoruba city-states (Ife, Oyo, Ibadan) developed parallel urban civilisations with sophisticated art, governance, and trade networks.",
    periods: [
      { name: 'Early Benin & Yoruba', start: 900, end: 1300 },
      { name: 'Benin Empire Height', start: 1300, end: 1700 },
      { name: 'Late Benin', start: 1700, end: 1897 },
    ],
  },
  {
    id: 'kanem-bornu',
    name: 'Kanem-Bornu & Hausa States',
    start: 700, end: 1903,
    region: 'medieval',
    icon: '👑',
    description: "The Kanem-Bornu Empire (9th–19th century) was one of Africa's longest-lasting states, centred around Lake Chad and controlling trans-Saharan trade routes. At its peak it was a major Islamic centre of learning and commerce, trading with North Africa and the Middle East. The Hausa city-states (Kano, Katsina, Zaria, Daura, Gobir, Rano, Biram) were the most important trading and manufacturing centres of the western Sudan region. In 1804, the Fulani scholar Usman dan Fodio launched an Islamic jihad, creating the Sokoto Caliphate — which became the largest empire in 19th-century Africa, absorbing most Hausa states. The Caliphate's hierarchical structure of emirates was incorporated into British indirect rule after conquest (1903).",
    periods: [
      { name: 'Kanem-Bornu Empire', start: 700, end: 1700 },
      { name: 'Hausa States', start: 1000, end: 1804 },
      { name: 'Sokoto Caliphate', start: 1804, end: 1903 },
    ],
  },
  {
    id: 'slave-trade',
    name: 'Atlantic Slave Trade',
    start: 1472, end: 1851,
    region: 'colonial',
    icon: '⛓️',
    description: "Portuguese explorers reached the Nigerian coast in 1472. The Niger Delta ports — Bonny, Calabar, Lagos, Badagry — became major nodes of the Atlantic slave trade from the 16th through 19th centuries. An estimated 3.5 million enslaved Africans were shipped from the Bight of Benin and Bight of Biafra alone. Local rulers profited from the trade as intermediaries, which shaped political structures across the region. Britain abolished the slave trade in 1807 and used its naval squadron to intercept slavers; illegal trade continued for decades. The legitimate commerce in palm oil that replaced it drew British merchants further inland and set the stage for formal colonisation.",
    periods: [
      { name: 'Portuguese Contact & Early Trade', start: 1472, end: 1650 },
      { name: 'Height of Slave Trade', start: 1650, end: 1807 },
      { name: 'Suppression & Palm Oil Era', start: 1807, end: 1851 },
    ],
  },
  {
    id: 'british-colonialism',
    name: 'British Colonial Rule',
    start: 1851, end: 1960,
    region: 'colonial',
    icon: '🏳️',
    description: "Britain declared a protectorate over Lagos (1861) to suppress the slave trade and protect commerce. Frederick Lugard's conquest of the north (1900–1903) defeated the Sokoto Caliphate and created the Protectorates of Northern and Southern Nigeria. Lord Lugard amalgamated them into a single Nigeria on January 1, 1914 — a bureaucratic convenience that joined peoples with little in common. Indirect rule governed through existing chiefs, preserving and sometimes creating traditional authority. Educated Nigerians began demanding representation from the 1920s. Herbert Macaulay (grandfather of Nigerian nationalism) founded the Nigerian National Democratic Party (1923). WWII accelerated decolonisation; the Richards Constitution (1946) and subsequent constitutions advanced self-governance. In 1954, a federal constitution was adopted, preparing for independence.",
    periods: [
      { name: 'Conquest & Early Administration', start: 1851, end: 1914 },
      { name: 'Amalgamation & Indirect Rule', start: 1914, end: 1945 },
      { name: 'Towards Independence', start: 1945, end: 1960 },
    ],
  },
  {
    id: 'independence',
    name: 'Independence & First Republic',
    start: 1960, end: 1967,
    region: 'independence',
    icon: '🇳🇬',
    description: "Nigeria achieved independence on October 1, 1960 — a moment of enormous hope for the continent's most populous nation. Abubakar Tafawa Balewa became the first Prime Minister; Nnamdi Azikiwe became Governor-General then President. The federal structure divided power among three regions — Northern, Eastern, and Western — dominated respectively by the Hausa-Fulani (NPC), Igbo (NCNC), and Yoruba (AG). Ethnic tensions intensified as each group competed for resources and federal power. Electoral fraud in the 1964 federal elections and the 1965 Western Regional election triggered crisis. On January 15, 1966, army officers (mostly Igbo) staged a coup, killing Balewa and key Northern leaders — beginning a cycle of military intervention that would last for decades.",
    periods: [
      { name: 'Independence & Federal Republic', start: 1960, end: 1964 },
      { name: 'Political Crisis', start: 1964, end: 1967 },
    ],
  },
  {
    id: 'biafra-war',
    name: 'Nigerian Civil War (Biafra)',
    start: 1967, end: 1970,
    region: 'independence',
    icon: '💥',
    description: "Anti-Igbo pogroms in the North (1966) triggered the flight of millions of Igbo back to the Eastern Region. On May 30, 1967, Colonel Odumegwu Ojukwu declared the Eastern Region's secession as the Republic of Biafra. The federal government under General Yakubu Gowon launched a military campaign to reunite Nigeria. The war became notorious for the Biafran famine — a deliberate blockade strategy created catastrophic starvation. Images of starving children shocked the world and transformed global humanitarian consciousness. Between 1 and 3 million died, predominantly from famine. Biafra surrendered on January 15, 1970. Gowon's policy of 'no victor, no vanquished' and rapid reintegration prevented the worst of post-war recrimination.",
    periods: [
      { name: 'Biafran Secession', start: 1967, end: 1968 },
      { name: 'War & Famine', start: 1968, end: 1970 },
    ],
  },
  {
    id: 'oil-military',
    name: 'Oil Boom & Military Rule',
    start: 1970, end: 1999,
    region: 'modern',
    icon: '🛢️',
    description: "Oil transformed Nigeria after the 1973 OPEC price shock. Nigeria joined OPEC (1971); revenues funded rapid infrastructure development but also corruption on a colossal scale. A succession of military coups (Murtala Muhammed 1975, killed 1976; Obasanjo 1976–79; Buhari 1983–85; Babangida 1985–93; Abacha 1993–98) punctuated brief democratic interludes. The Ogoni people's campaign (led by Ken Saro-Wiwa) against Shell's devastating environmental impact in the Niger Delta ended with Saro-Wiwa's execution in 1995, triggering international sanctions. When dictator Sani Abacha died suddenly in 1998, transition to democracy was finally achieved. The oil 'curse' produced massive inequality, environmental destruction, and chronic underdevelopment despite petroleum wealth.",
    periods: [
      { name: 'Oil Boom & Early Military Rule', start: 1970, end: 1985 },
      { name: 'Babangida & Abacha Era', start: 1985, end: 1998 },
      { name: 'Transition to Democracy', start: 1998, end: 1999 },
    ],
  },
  {
    id: 'modern-nigeria',
    name: 'Modern Nigeria',
    start: 1999, end: 2025,
    region: 'modern',
    icon: '🌍',
    description: "Nigeria's Fourth Republic (from 1999) has maintained democratic governance through multiple elections and peaceful transfers of power. Olusegun Obasanjo (1999–2007), Umaru Yar'Adua, Goodluck Jonathan, and Muhammadu Buhari (2015–23) each faced endemic corruption, infrastructure deficits, and security crises. Boko Haram's insurgency in the northeast (from 2009) devastated the region and kidnapped 276 Chibok schoolgirls (2014). The #EndSARS protests (2020) against police brutality became a generational moment. Despite challenges, Nigeria is Africa's largest economy (overtook South Africa in 2014), most populous nation (over 220 million people), and a global centre of culture — Nollywood (world's second-largest film industry), Afrobeats music (Burna Boy, Wizkid, Davido), and a rapidly growing tech sector.",
    periods: [
      { name: 'Obasanjo & Early Democracy', start: 1999, end: 2011 },
      { name: 'Boko Haram & Jonathan', start: 2011, end: 2015 },
      { name: 'Buhari & Tinubu Era', start: 2015, end: 2025 },
    ],
  },
];
