export const ukCategories = [
  { id: 'political',  name: 'Political Eras',    color: '#6366F1' },
  { id: 'monarchy',   name: 'Monarchy',           color: '#C084FC' },
  { id: 'empire',     name: 'Empire',             color: '#EF4444' },
  { id: 'conflicts',  name: 'Major Conflicts',    color: '#F97316' },
  { id: 'culture',    name: 'Culture & Society',  color: '#10B981' },
];

export const ukItems = [
  {
    id: 'roman-britain',
    name: 'Roman Britain',
    start: -43, end: 410,
    region: 'political',
    icon: '🏛️',
    description: 'Roman conquest and occupation of Britain for nearly 400 years. The Romans built Londinium (London), Hadrian\'s Wall, and an extensive road network that still underlies modern roads. Latin, Christianity, and urban culture were introduced.',
    periods: [
      { name: 'Conquest', start: -43, end: 100 },
      { name: 'Hadrian\'s Wall', start: 122, end: 410 },
    ],
  },
  {
    id: 'anglo-saxon',
    name: 'Anglo-Saxon England',
    start: 410, end: 1066,
    region: 'political',
    icon: '⚔️',
    description: 'After Roman withdrawal, Germanic tribes — Angles, Saxons, and Jutes — settle Britain. The Heptarchy of seven kingdoms slowly unifies into England. Viking raids and the Danelaw transform the cultural landscape.',
    periods: [
      { name: 'Heptarchy', start: 410, end: 829 },
      { name: 'Viking Age', start: 793, end: 1013 },
      { name: 'Late Anglo-Saxon', start: 900, end: 1066 },
    ],
  },
  {
    id: 'norman-plantagenet',
    name: 'Norman & Plantagenet England',
    start: 1066, end: 1399,
    region: 'monarchy',
    icon: '🏰',
    description: 'William the Conqueror\'s victory at Hastings transforms English society, language, and governance. The Plantagenets preside over the Magna Carta (1215), the birth of Parliament, and the Hundred Years War with France.',
    periods: [
      { name: 'Norman', start: 1066, end: 1154 },
      { name: 'Plantagenet', start: 1154, end: 1399 },
    ],
  },
  {
    id: 'wars-of-roses-tudor',
    name: 'Wars of the Roses & Tudor Dynasty',
    start: 1455, end: 1603,
    region: 'monarchy',
    icon: '🌹',
    description: 'Civil war between the Houses of York and Lancaster ends with Henry VII founding the Tudor dynasty. Henry VIII\'s break with Rome creates the Church of England. Elizabeth I presides over a golden age of exploration and literature.',
    periods: [
      { name: 'Wars of Roses', start: 1455, end: 1485 },
      { name: 'Henry VIII', start: 1509, end: 1547 },
      { name: 'Elizabethan Age', start: 1558, end: 1603 },
    ],
  },
  {
    id: 'stuart-commonwealth',
    name: 'Stuart & Commonwealth Period',
    start: 1603, end: 1714,
    region: 'monarchy',
    icon: '👑',
    description: 'The Stuarts inherit the throne but clash with Parliament over religion and royal authority. Civil war ends with Charles I\'s execution. Cromwell\'s Commonwealth gives way to the Restoration. The Glorious Revolution of 1688 establishes constitutional monarchy.',
    periods: [
      { name: 'Early Stuarts', start: 1603, end: 1642 },
      { name: 'Civil War', start: 1642, end: 1651 },
      { name: 'Commonwealth', start: 1649, end: 1660 },
      { name: 'Restoration', start: 1660, end: 1714 },
    ],
  },
  {
    id: 'georgian-era',
    name: 'Georgian Era',
    start: 1714, end: 1830,
    region: 'political',
    icon: '⚙️',
    description: 'The Hanoverian kings preside over the Act of Union with Scotland, the loss of the American colonies, and most crucially, the Industrial Revolution — transforming Britain from an agrarian economy into the world\'s first industrial power.',
    periods: [
      { name: 'Early Georgian', start: 1714, end: 1760 },
      { name: 'Industrial Revolution', start: 1760, end: 1830 },
    ],
  },
  {
    id: 'victorian-era',
    name: 'Victorian Era',
    start: 1837, end: 1901,
    region: 'monarchy',
    icon: '🎩',
    description: 'Queen Victoria\'s 63-year reign marks the height of British power. The empire expands to cover a quarter of the world\'s land surface. Railways, the Great Exhibition of 1851, democratic reforms, and the rise of the middle class define the age.',
    periods: [
      { name: 'Early Victorian', start: 1837, end: 1870 },
      { name: 'High Victorian', start: 1870, end: 1901 },
    ],
  },
  {
    id: 'british-empire',
    name: 'British Empire',
    start: 1583, end: 1997,
    region: 'empire',
    icon: '🌍',
    description: 'At its height in the 1920s, the British Empire was the largest in history, covering 24% of the Earth\'s land area and governing 458 million people. It shaped the modern world through language, law, trade, and — more darkly — colonialism, slavery, and exploitation.',
    periods: [
      { name: 'Early Empire', start: 1583, end: 1783 },
      { name: 'Imperial Height', start: 1815, end: 1914 },
      { name: 'Decolonisation', start: 1945, end: 1997 },
    ],
  },
  {
    id: 'world-wars',
    name: 'World Wars',
    start: 1914, end: 1945,
    region: 'conflicts',
    icon: '⚔️',
    description: 'Britain fights two devastating world wars within a generation. WWI costs 900,000 British lives; WWII sees the Dunkirk evacuation, the Blitz, and Churchill\'s defiance against Nazi Germany. Victory comes at the cost of empire and economic supremacy.',
    periods: [
      { name: 'World War I', start: 1914, end: 1918 },
      { name: 'Interwar', start: 1918, end: 1939 },
      { name: 'World War II', start: 1939, end: 1945 },
    ],
  },
  {
    id: 'modern-britain',
    name: 'Modern Britain',
    start: 1945, end: 2025,
    region: 'political',
    icon: '🏙️',
    description: 'Post-war Britain creates the NHS and welfare state, loses its empire, and joins (then leaves) the European Union. From Attlee\'s reforms through Thatcher\'s revolution, Blair\'s New Labour, Brexit, and beyond, Britain reinvents itself in a changed world.',
    periods: [
      { name: 'Welfare State', start: 1945, end: 1979 },
      { name: 'Thatcher Era', start: 1979, end: 1997 },
      { name: 'New Labour', start: 1997, end: 2010 },
      { name: 'Brexit Era', start: 2016, end: 2025 },
    ],
  },
  {
    id: 'uk-culture',
    name: 'Culture & Arts',
    start: 1558, end: 2025,
    region: 'culture',
    icon: '🎭',
    description: 'Britain\'s cultural output has shaped the world: Shakespeare\'s plays, the novel form, the British music invasion of the 1960s, the BBC, and a literary tradition from Dickens to Rowling. The English language itself is the world\'s most widely spoken.',
    periods: [
      { name: 'Shakespeare & Renaissance', start: 1558, end: 1660 },
      { name: 'Enlightenment & Romanticism', start: 1660, end: 1850 },
      { name: 'Modern Culture', start: 1850, end: 2025 },
    ],
  },
];
