export const usCategories = [
  { id: 'colonial',   name: 'Colonial Era',           color: '#78716C' },
  { id: 'federal',    name: 'Federal Eras',            color: '#3B82F6' },
  { id: 'conflicts',  name: 'Conflicts',               color: '#EF4444' },
  { id: 'society',    name: 'Civil Rights & Society',  color: '#10B981' },
  { id: 'economy',    name: 'Economy & Technology',    color: '#F97316' },
];

export const usItems = [
  {
    id: 'colonial-period',
    name: 'Colonial Period',
    start: 1607, end: 1776,
    region: 'colonial',
    icon: '⛵',
    description: 'European — primarily British — settlers establish colonies along the eastern seaboard. Jamestown (1607) is the first permanent English settlement. The colonies develop distinct political cultures, economies based on tobacco and cotton (worked by enslaved Africans), and an increasing sense of shared identity that will fuel revolution.',
    periods: [
      { name: 'Early Settlement', start: 1607, end: 1700 },
      { name: 'Pre-Revolution', start: 1700, end: 1776 },
    ],
  },
  {
    id: 'american-revolution',
    name: 'American Revolution',
    start: 1775, end: 1783,
    region: 'conflicts',
    icon: '🗽',
    description: 'Thirteen colonies declare independence from Britain in 1776, enshrining Enlightenment ideals of liberty and self-governance. Washington\'s Continental Army defeats the British with French help. The Treaty of Paris (1783) recognises the United States as an independent nation.',
    periods: [],
  },
  {
    id: 'early-republic',
    name: 'Early Republic & Expansion',
    start: 1789, end: 1860,
    region: 'federal',
    icon: '📜',
    description: 'The Constitution is ratified and Washington becomes the first president. The Louisiana Purchase doubles the nation\'s territory; the Lewis and Clark Expedition maps the west. "Manifest Destiny" drives expansion across the continent at the expense of Native American peoples.',
    periods: [
      { name: 'Founding Era', start: 1789, end: 1820 },
      { name: 'Manifest Destiny', start: 1820, end: 1860 },
    ],
  },
  {
    id: 'civil-war',
    name: 'Civil War',
    start: 1861, end: 1865,
    region: 'conflicts',
    icon: '⚔️',
    description: 'The deadliest conflict in American history. The Confederate South secedes over slavery; the Union under Lincoln fights to preserve the nation. The Emancipation Proclamation (1863) transforms the war\'s moral stakes. 620,000–750,000 soldiers die before Lee surrenders at Appomattox.',
    periods: [],
  },
  {
    id: 'reconstruction-gilded',
    name: 'Reconstruction & Gilded Age',
    start: 1865, end: 1900,
    region: 'federal',
    icon: '🏭',
    description: 'Reconstruction attempts to integrate formerly enslaved people into civic life but is abandoned by 1877, leaving the Jim Crow South. The Gilded Age brings explosive industrialisation, railroads, Carnegie\'s steel, and Rockefeller\'s oil — alongside vast inequality and labour conflict.',
    periods: [
      { name: 'Reconstruction', start: 1865, end: 1877 },
      { name: 'Gilded Age', start: 1877, end: 1900 },
    ],
  },
  {
    id: 'progressive-interwar',
    name: 'Progressive Era & Roaring Twenties',
    start: 1900, end: 1929,
    region: 'federal',
    icon: '📻',
    description: 'Reform movements tackle inequality, child labour, and political corruption. Women gain the vote in 1920. WWI transforms the US into a global power. The Roaring Twenties bring jazz, the Harlem Renaissance, consumer culture, and Prohibition — before the stock market crash.',
    periods: [
      { name: 'Progressive Era', start: 1900, end: 1917 },
      { name: 'World War I', start: 1917, end: 1918 },
      { name: 'Roaring Twenties', start: 1920, end: 1929 },
    ],
  },
  {
    id: 'depression-wwii',
    name: 'Great Depression & World War II',
    start: 1929, end: 1945,
    region: 'conflicts',
    icon: '🪖',
    description: 'The 1929 Wall Street Crash triggers the Great Depression; FDR\'s New Deal reshapes the role of government. Pearl Harbour brings the US into WWII. American industrial might and the sacrifice of 400,000 lives help defeat the Axis. The Manhattan Project ends the war — and transforms global security.',
    periods: [
      { name: 'Great Depression', start: 1929, end: 1941 },
      { name: 'World War II', start: 1941, end: 1945 },
    ],
  },
  {
    id: 'cold-war',
    name: 'Cold War Era',
    start: 1947, end: 1991,
    region: 'conflicts',
    icon: '☢️',
    description: 'The US and Soviet Union engage in a global ideological struggle that shapes every aspect of the post-war world: the Berlin Airlift, Korean War, Cuban Missile Crisis, Vietnam War, the Space Race, and the nuclear arms race. Reagan\'s escalation contributes to the Soviet collapse in 1991.',
    periods: [
      { name: 'Truman–Eisenhower', start: 1947, end: 1961 },
      { name: 'Vietnam & Détente', start: 1961, end: 1979 },
      { name: 'Reagan & Endgame', start: 1979, end: 1991 },
    ],
  },
  {
    id: 'civil-rights',
    name: 'Civil Rights Movement',
    start: 1954, end: 1968,
    region: 'society',
    icon: '✊',
    description: 'The Supreme Court\'s Brown v. Board ruling begins the legal dismantling of segregation. Rosa Parks, Martin Luther King Jr., the March on Washington, the Civil Rights Act (1964), and the Voting Rights Act (1965) transform American society. King\'s assassination in 1968 marks the movement\'s tragic apex.',
    periods: [],
  },
  {
    id: 'post-cold-war',
    name: 'Post-Cold War America',
    start: 1991, end: 2025,
    region: 'federal',
    icon: '🌐',
    description: 'The US stands as the world\'s sole superpower. The internet revolution, 9/11 and the War on Terror, the 2008 financial crisis, the Obama presidency, and the polarisation of American politics under Trump mark an era of both global dominance and deep domestic division.',
    periods: [
      { name: 'Clinton Era', start: 1993, end: 2001 },
      { name: '9/11 & War on Terror', start: 2001, end: 2009 },
      { name: 'Obama Era', start: 2009, end: 2017 },
      { name: 'Polarisation & Pandemic', start: 2017, end: 2025 },
    ],
  },
];
