export const artCategories = [
  { id: 'visual-art',  name: 'Visual Art',         color: '#8B5CF6' },
  { id: 'music',       name: 'Music',               color: '#EC4899' },
  { id: 'architecture',name: 'Architecture',        color: '#F97316' },
  { id: 'literature',  name: 'Literature',          color: '#3B82F6' },
  { id: 'film-media',  name: 'Film & Media',        color: '#EF4444' },
  { id: 'performing',  name: 'Performing Arts',     color: '#10B981' },
];

export const artItems = [
  {
    id: 'prehistoric-art',
    name: 'Prehistoric Art',
    start: -40000, end: -3000,
    region: 'visual-art',
    icon: '🦬',
    description: "The oldest known human art dates to at least 40,000 years ago. The Chauvet Cave (France, c. 36,000 BCE) and Lascaux (c. 17,000 BCE) contain breathtaking paintings of horses, aurochs, and lions. Venus figurines (c. 25,000 BCE) — small statuettes of female forms — appear from France to Siberia. Blombos Cave (South Africa) contains ochre engravings and shell beads dated to 75,000 BCE. Rock art traditions persist across Africa, Australia, and the Americas for tens of thousands of years. Prehistoric art demonstrates aesthetic sense, symbolic thinking, and possibly ritual or spiritual function at the very dawn of behavioural modernity.",
    periods: [
      { name: 'Upper Palaeolithic Cave Art', start: -40000, end: -10000 },
      { name: 'Neolithic & Megalithic Art', start: -10000, end: -3000 },
    ],
  },
  {
    id: 'ancient-world-art',
    name: 'Ancient World Art',
    start: -3100, end: 500,
    region: 'visual-art',
    icon: '🏺',
    description: "The ancient world produced enduring art across civilisations. Egyptian art (3100 BCE–395 CE) maintained strict conventions for 3,000 years: figures shown in twisted perspective, hieratic scale (rulers shown larger), vibrant tomb paintings, monumental sculpture (Sphinx, Ramesses statues). Greek art evolved from rigid Archaic kouroi to the Classical ideal (Pheidias's Athena, Praxiteles's Aphrodite) to Hellenistic dramatic realism (Laocoön, Winged Victory). Roman art absorbed and transmitted Greek traditions: portrait sculpture (extraordinarily realistic), mosaic floors (Pompeii), wall frescoes, triumphal reliefs (Trajan's Column). Indian sculpture (Mauryan to Gupta) developed the Buddhist image from aniconic symbols to idealised human form.",
    periods: [
      { name: 'Egyptian Art', start: -3100, end: -332 },
      { name: 'Greek Art', start: -700, end: -31 },
      { name: 'Roman Art', start: -100, end: 400 },
    ],
  },
  {
    id: 'medieval-art',
    name: 'Byzantine & Medieval Art',
    start: 300, end: 1400,
    region: 'visual-art',
    icon: '⛪',
    description: "Byzantine art (4th–15th century CE) developed a distinct sacred aesthetic: gold-background mosaics, rigid frontal icons, hieratic figures that conveyed spiritual rather than physical reality. Ravenna's mosaics (5th–6th century) are the masterpieces. Icon painting became a profound theological art; the Iconoclasm controversy (726–843 CE) nearly destroyed the tradition. Western medieval art served the Church: illuminated manuscripts (Book of Kells, Lindisfarne Gospels), Romanesque sculpture (tympana with Last Judgement scenes), and Gothic innovations — stained glass windows (Chartres, Sainte-Chapelle) transforming architecture into scripture in light. Tapestries (Bayeux, Dame à la Licorne) and manuscript illumination reached extraordinary refinement.",
    periods: [
      { name: 'Early Byzantine', start: 300, end: 700 },
      { name: 'Romanesque Art', start: 950, end: 1150 },
      { name: 'Gothic Art', start: 1150, end: 1400 },
    ],
  },
  {
    id: 'renaissance-art',
    name: 'Renaissance Art',
    start: 1400, end: 1600,
    region: 'visual-art',
    icon: '🎨',
    description: "The Renaissance — 'rebirth' of classical art — emerged in Florence with Brunelleschi (linear perspective, c. 1420), Donatello (first freestanding nude since antiquity), and Masaccio (dramatic chiaroscuro). The High Renaissance (1490–1527) produced the most celebrated works in Western art: Leonardo da Vinci's Mona Lisa (c. 1503–19) and Last Supper (1497); Michelangelo's Sistine Chapel ceiling (1508–12), David (1504), and Pietà; Raphael's School of Athens (1509–11). The Northern Renaissance (Van Eyck's oil painting technique, Dürer's engravings, Holbein's portraits) transformed art in Germany, Flanders, and England. Venice developed its own luminous colour tradition (Bellini, Titian, Tintoretto, Veronese).",
    periods: [
      { name: 'Early Renaissance', start: 1400, end: 1490 },
      { name: 'High Renaissance', start: 1490, end: 1527 },
      { name: 'Mannerism & Late Renaissance', start: 1527, end: 1600 },
    ],
  },
  {
    id: 'baroque-rococo',
    name: 'Baroque, Rococo & Neoclassicism',
    start: 1600, end: 1800,
    region: 'visual-art',
    icon: '🖼️',
    description: "Baroque art (c. 1600–1750) embraced drama, movement, and emotional intensity. Caravaggio's revolutionary tenebrism (extreme chiaroscuro) shocked and influenced all European painting. Rubens's sweeping canvases epitomised Flemish Baroque; Rembrandt transformed portraiture and self-portraiture in the Dutch Republic; Vermeer (Girl with a Pearl Earring) captured intimate domestic light; Velázquez's Las Meninas (1656) remains one of art's greatest enigmas. Bernini dominated Baroque sculpture and architecture. Rococo (c. 1720–1780) lightened the palette with pastel colours and playful sensuality (Watteau, Fragonard). Neoclassicism (c. 1770–1830) reacted with moral severity, drawing on ancient Rome: Jacques-Louis David's Oath of the Horatii (1784) embodied Revolutionary virtue.",
    periods: [
      { name: 'Baroque', start: 1600, end: 1720 },
      { name: 'Rococo', start: 1720, end: 1780 },
      { name: 'Neoclassicism', start: 1770, end: 1800 },
    ],
  },
  {
    id: 'romanticism-realism',
    name: 'Romanticism & Realism',
    start: 1800, end: 1880,
    region: 'visual-art',
    icon: '🌊',
    description: "Romanticism elevated emotion, imagination, and the sublime over reason. Caspar David Friedrich (Wanderer above the Sea of Fog, 1818) captured spiritual solitude in landscape. Théodore Géricault's Raft of the Medusa (1819) shocked the Salon with raw tragedy. Eugène Delacroix (Liberty Leading the People, 1830) brought Romantic colour and movement. J.M.W. Turner dissolved landscape into light and atmosphere, anticipating Impressionism. John Constable's naturalistic landscapes influenced French painters. Realism (from c. 1848) rejected Romantic idealisation for the honest depiction of contemporary life: Gustave Courbet painted peasants and stone-breakers without sentimentality; Jean-François Millet dignified rural labour; Honoré Daumier satirised bourgeois society.",
    periods: [
      { name: 'Romanticism', start: 1800, end: 1850 },
      { name: 'Realism', start: 1848, end: 1880 },
    ],
  },
  {
    id: 'impressionism',
    name: 'Impressionism & Post-Impressionism',
    start: 1860, end: 1910,
    region: 'visual-art',
    icon: '🌻',
    description: "Impressionism (c. 1860–1886) revolutionised painting by capturing fleeting effects of light and atmosphere with visible brushwork. Monet (Haystacks, Water Lilies, Rouen Cathedral series), Renoir, Degas (ballerinas and cafés), Pissarro, and Sisley exhibited independently after rejection by the official Salon. The camera's rise liberated painting from documentary realism. Post-Impressionism opened new directions: Paul Cézanne reduced forms to geometric essentials, laying the groundwork for Cubism; Vincent van Gogh (Starry Night, Sunflowers) used swirling brushwork and pure colour to express inner emotion; Paul Gauguin fled to Tahiti seeking primitivism; Georges Seurat developed Pointillism from scientific colour theory.",
    periods: [
      { name: 'Impressionism', start: 1863, end: 1886 },
      { name: 'Post-Impressionism', start: 1886, end: 1910 },
    ],
  },
  {
    id: 'modern-art',
    name: 'Modern Art Movements',
    start: 1905, end: 1970,
    region: 'visual-art',
    icon: '🟦',
    description: "The 20th century saw art fragment into rapid succession of movements. Fauvism (Matisse, Derain; 1905) shocked with pure, arbitrary colour. Cubism (Picasso and Braque, 1907–14) shattered single-point perspective, showing multiple viewpoints simultaneously — Les Demoiselles d'Avignon (1907) marks the break with all tradition. Dada (1916, Zürich and New York) rejected reason itself — Duchamp's readymades (Fountain: a urinal, 1917) questioned what art is. Surrealism (André Breton, Dalí, Magritte, Ernst) accessed the unconscious through dreamlike imagery. Abstract Expressionism (Pollock's drip painting, Rothko's colour fields) made New York the postwar art capital. Pop Art (Warhol, Lichtenstein) dissolved the boundary between high art and mass culture.",
    periods: [
      { name: 'Fauvism & Cubism', start: 1905, end: 1920 },
      { name: 'Dada & Surrealism', start: 1916, end: 1945 },
      { name: 'Abstract Expressionism & Pop Art', start: 1945, end: 1970 },
    ],
  },
  {
    id: 'contemporary-art',
    name: 'Contemporary Art',
    start: 1970, end: 2025,
    region: 'visual-art',
    icon: '🖼️',
    description: "Contemporary art since 1970 has been characterised by pluralism, conceptualism, and globalisation. Conceptual art (Kosuth, LeWitt) held that the idea is the work; minimalism (Judd, Andre) stripped art to essential form. Installation art transformed entire spaces (Christo's wrappings, James Turrell's light rooms). Street art moved from graffiti (Jean-Michel Basquiat, Keith Haring) to the gallery-disrupting provocations of Banksy. Photography and video art became fully accepted media. Damien Hirst and the YBAs (Young British Artists) generated 1990s controversy. The digital revolution created new media art, generative art, and NFTs (2021 boom). Contemporary art has become genuinely global, with major centres in Lagos, Shanghai, São Paulo, and Mumbai alongside New York and London.",
    periods: [
      { name: 'Conceptual & Minimal Art', start: 1970, end: 1990 },
      { name: 'Installation & Street Art', start: 1980, end: 2010 },
      { name: 'Digital & Global Art', start: 2000, end: 2025 },
    ],
  },
  {
    id: 'ancient-medieval-music',
    name: 'Ancient & Medieval Music',
    start: -3000, end: 1400,
    region: 'music',
    icon: '🎵',
    description: "Music's history stretches to the earliest human cultures — bone flutes have been found from 40,000 BCE. Sumerian and Egyptian musicians played harps, lyres, and wind instruments at court and temple. Greek music theory (modes, intervals, harmonics) was developed by Pythagoras and transmitted to Western music theory. Gregorian chant (named for Pope Gregory I, c. 590–604 CE) — monophonic sacred singing — became the foundation of Western music. Polyphony (multiple simultaneous vocal lines) emerged in the 9th century (organum) and developed through the Notre-Dame school (Léonin, Pérotin) into the rich motets of the Ars nova (14th century). Troubadours and trouvères pioneered secular song in medieval Europe; Hildegard von Bingen composed extraordinarily vivid sacred music.",
    periods: [
      { name: 'Ancient Music', start: -3000, end: 500 },
      { name: 'Gregorian Chant & Early Polyphony', start: 500, end: 1300 },
      { name: 'Ars Nova & Troubadours', start: 1300, end: 1400 },
    ],
  },
  {
    id: 'classical-music',
    name: 'Classical Music',
    start: 1600, end: 1900,
    region: 'music',
    icon: '🎻',
    description: "Western classical music's Golden Age. The Baroque period (1600–1750): Johann Sebastian Bach synthesised all European musical traditions — fugues, cantatas, and the Brandenburg Concertos stand as music's greatest intellectual architecture; Antonio Vivaldi (The Four Seasons) made the violin concerto a form; George Frideric Handel's Messiah became the most performed choral work in history. The Classical period (1750–1820): Joseph Haydn perfected the symphony and string quartet; Wolfgang Amadeus Mozart (Don Giovanni, Jupiter Symphony, Requiem) achieved supernatural perfection in every form in a brief 35 years. The Romantic era (1820–1900): Beethoven's titanic symphonies (especially 9th, with choral finale) expanded music's emotional range; Schubert, Chopin, Liszt, Brahms, and Tchaikovsky followed; Wagner's music dramas (Ring cycle) transformed opera and all subsequent music.",
    periods: [
      { name: 'Baroque (Bach, Vivaldi, Handel)', start: 1600, end: 1750 },
      { name: 'Classical (Haydn, Mozart)', start: 1750, end: 1820 },
      { name: 'Romantic (Beethoven to Mahler)', start: 1820, end: 1900 },
    ],
  },
  {
    id: 'modern-music',
    name: '20th-Century Music',
    start: 1900, end: 2000,
    region: 'music',
    icon: '🎷',
    description: "The 20th century saw music fragment and democratise. Early modernist classical music: Debussy's impressionism, Stravinsky's The Rite of Spring (1913 riot at premiere), Schoenberg's 12-tone serialism, Shostakovich's Soviet-era symphonies. American vernacular music transformed the world: Blues (Robert Johnson, Bessie Smith) emerged from African-American experience in the Deep South; Jazz (Louis Armstrong, Duke Ellington, Miles Davis's Kind of Blue, John Coltrane) became America's classical music. Rock and Roll (Elvis, Chuck Berry, 1950s) evolved through the Beatles' revolution, Rolling Stones, Led Zeppelin, Bob Dylan's folk-rock, to Punk (Sex Pistols, 1977), New Wave, and Grunge. Soul (Aretha Franklin, Marvin Gaye, Stevie Wonder), Disco, Electronic/Techno, Hip-hop (Grandmaster Flash, Public Enemy, Tupac, Jay-Z) each created new traditions.",
    periods: [
      { name: 'Blues, Jazz & Classical Modernism', start: 1900, end: 1950 },
      { name: 'Rock & Roll Revolution', start: 1950, end: 1975 },
      { name: 'Punk, Electronic & Hip-Hop', start: 1975, end: 2000 },
    ],
  },
  {
    id: 'ancient-architecture',
    name: 'Ancient Architecture',
    start: -3100, end: 500,
    region: 'architecture',
    icon: '🏛️',
    description: "Ancient civilisations produced architectural achievements that remain unmatched for their combination of scale, precision, and aesthetic power. Egypt: the Great Pyramid at Giza (2560 BCE, 146m tall) was the world's tallest structure for 3,800 years; the Temple of Karnak is the largest religious complex ever built. Greece: the Doric, Ionic, and Corinthian orders established proportional systems still copied today; the Parthenon (447–432 BCE) embodies mathematical perfection in marble. Rome: the Pantheon's unreinforced concrete dome (43m diameter, 118 CE) wasn't surpassed until the 15th century; Roman aqueducts, baths, amphitheatres (Colosseum, 70–80 CE), and road infrastructure demonstrated engineering mastery. Indian temple architecture (Sanchi stupa, Brihadeeswarar Temple) developed distinct forms of equal sophistication.",
    periods: [
      { name: 'Egyptian Architecture', start: -3100, end: -332 },
      { name: 'Greek Architecture', start: -700, end: -31 },
      { name: 'Roman Architecture', start: -100, end: 400 },
    ],
  },
  {
    id: 'medieval-renaissance-architecture',
    name: 'Medieval & Renaissance Architecture',
    start: 500, end: 1600,
    region: 'architecture',
    icon: '⛪',
    description: "Byzantine architecture (Hagia Sophia, 537 CE — its dome appears to float on a ring of windows) inspired both Islamic and Eastern Orthodox church design. Romanesque architecture (c. 1000–1150) used massive walls, round arches, and barrel vaults. The Gothic revolution (c. 1140, Abbot Suger at Saint-Denis) introduced the pointed arch, ribbed vault, and flying buttress — allowing soaring thin walls filled with stained glass. Notre-Dame de Paris (begun 1163), Chartres, Cologne, and Westminster Abbey reached for heaven in stone. Renaissance architecture (Brunelleschi's dome over Florence Cathedral, 1436; Palladio's villas and churches) revived classical proportions and introduced the architectural treatise; Palladio's Four Books of Architecture (1570) shaped building from 18th-century England to colonial America.",
    periods: [
      { name: 'Byzantine & Romanesque', start: 500, end: 1150 },
      { name: 'Gothic', start: 1140, end: 1400 },
      { name: 'Renaissance Architecture', start: 1400, end: 1600 },
    ],
  },
  {
    id: 'modern-architecture',
    name: 'Modern & Contemporary Architecture',
    start: 1850, end: 2025,
    region: 'architecture',
    icon: '🏙️',
    description: "The iron-and-steel revolution created new structural possibilities: the Crystal Palace (1851), Eiffel Tower (1889), and the first skyscrapers (Chicago, 1880s). Art Nouveau (Gaudí's Sagrada Família, Barcelona; Horta's Brussels buildings) brought organic ornament. The Bauhaus (Gropius, 1919–1933) developed modernist principles: form follows function, industrial materials, social purpose; Mies van der Rohe and Le Corbusier distilled this into the International Style — glass curtain walls, flat roofs, open plans. The mid-20th century saw the global spread of the glass tower. Postmodernism (Venturi, Philip Johnson) added wit, ornament, and historical reference. Late 20th-century 'starchitects' — Frank Gehry (Guggenheim Bilbao), Zaha Hadid, Norman Foster, Herzog & de Meuron — created iconic signature buildings.",
    periods: [
      { name: 'Industrial & Art Nouveau', start: 1850, end: 1920 },
      { name: 'Bauhaus & International Style', start: 1919, end: 1970 },
      { name: 'Postmodern & Contemporary', start: 1970, end: 2025 },
    ],
  },
  {
    id: 'ancient-medieval-literature',
    name: 'Ancient & Medieval Literature',
    start: -2700, end: 1450,
    region: 'literature',
    icon: '📜',
    description: "The oldest surviving literature: the Epic of Gilgamesh (c. 2100 BCE, Sumerian/Akkadian) — a king's quest for immortality, including a flood narrative parallel to Noah's. Homer's Iliad and Odyssey (c. 8th century BCE) founded European literature; the Odyssey's influence never ceased. Virgil's Aeneid (19 BCE) legitimised Rome with an epic origin myth; Ovid's Metamorphoses surveyed mythology's transformations. Indian epics: the Mahabharata (including the Bhagavad Gita) and Ramayana. The Tale of Genji (Murasaki Shikibu, c. 1000 CE, Japan) is often called the world's first novel. Dante's Divine Comedy (1308–1320) is medieval Europe's supreme literary achievement — a visionary journey through Hell, Purgatory, and Heaven that synthesised all medieval thought. Chaucer's Canterbury Tales (c. 1390) brought vernacular English to high literature.",
    periods: [
      { name: 'Ancient Literature', start: -2700, end: -200 },
      { name: 'Classical Roman & Asian Literature', start: -200, end: 600 },
      { name: 'Medieval Literature', start: 600, end: 1450 },
    ],
  },
  {
    id: 'renaissance-enlightenment-literature',
    name: 'Renaissance & Enlightenment Literature',
    start: 1500, end: 1800,
    region: 'literature',
    icon: '📚',
    description: "The printing press (Gutenberg, c. 1450) transformed literature's reach. William Shakespeare (1564–1616) wrote 37 plays and 154 sonnets that explore every dimension of human experience — Hamlet, Macbeth, King Lear, A Midsummer Night's Dream, The Tempest — in language of inexhaustible richness. Miguel de Cervantes's Don Quixote (1605–15) is often called the first modern novel — a meta-fictional exploration of reality, illusion, and idealism. John Milton's Paradise Lost (1667) retold humanity's fall in epic verse. Jonathan Swift's Gulliver's Travels (1726) satirised politics and human nature. Voltaire's Candide (1759) skewered optimism. Goethe's Faust (1808–32) dramatised humanity's striving. The 18th-century novel emerged: Defoe's Robinson Crusoe (1719), Richardson, Fielding, Sterne's Tristram Shandy.",
    periods: [
      { name: 'Shakespeare & Cervantes', start: 1500, end: 1620 },
      { name: '17th-Century Literature', start: 1620, end: 1700 },
      { name: 'Enlightenment Literature', start: 1700, end: 1800 },
    ],
  },
  {
    id: 'the-novel',
    name: 'The Novel & 19th-Century Literature',
    start: 1813, end: 1900,
    region: 'literature',
    icon: '📖',
    description: "The 19th century was the novel's golden age. Jane Austen (Pride and Prejudice, 1813; Emma) combined social comedy with profound moral insight in stories of domestic life. Charles Dickens (Oliver Twist, David Copperfield, Bleak House, Great Expectations) exposed Victorian poverty and hypocrisy in serialised fiction. The Brontë sisters transformed the novel: Charlotte's Jane Eyre (1847), Emily's Wuthering Heights (1847). In Russia: Tolstoy's War and Peace (1869) and Anna Karenina (1878) — the 19th century novel at its greatest scale and humanity; Dostoyevsky's Crime and Punishment, The Brothers Karamazov explored guilt, faith, and freedom with unequalled psychological intensity. In France: Flaubert's Madame Bovary (1857), Zola's Naturalism. In America: Herman Melville's Moby Dick (1851), Mark Twain's Adventures of Huckleberry Finn (1884).",
    periods: [
      { name: 'Romantic Novel (Austen, Scott)', start: 1813, end: 1850 },
      { name: 'Victorian Novel (Dickens)', start: 1837, end: 1870 },
      { name: 'Realist Masters (Tolstoy, Dostoyevsky, Zola)', start: 1857, end: 1900 },
    ],
  },
  {
    id: 'modernist-literature',
    name: 'Modernist & 20th-Century Literature',
    start: 1900, end: 1980,
    region: 'literature',
    icon: '✍️',
    description: "WWI shattered Victorian confidence and gave rise to literary Modernism — experimentation with stream of consciousness, unreliable narrators, non-linear time. James Joyce's Ulysses (1922) mapped a single Dublin day into 18 stylistically distinct chapters of revolutionary complexity. Virginia Woolf's Mrs Dalloway (1925) and The Waves perfected interior consciousness. Marcel Proust's In Search of Lost Time (1913–27) explored memory across 3,000 pages. Franz Kafka's The Trial and The Metamorphosis captured modern alienation. Ernest Hemingway's stripped prose, F. Scott Fitzgerald's The Great Gatsby (1925), and William Faulkner's Southern Gothic defined American Modernism. Post-WWII: Samuel Beckett's Waiting for Godot (1953), Camus, Sartre's existentialist fiction, Gabriel García Márquez's One Hundred Years of Solitude (1967) launched Magical Realism.",
    periods: [
      { name: 'Modernism (Joyce, Woolf, Proust)', start: 1900, end: 1939 },
      { name: 'Post-War Literature', start: 1945, end: 1970 },
      { name: 'Postmodern & Global Literature', start: 1960, end: 1980 },
    ],
  },
  {
    id: 'cinema',
    name: 'Cinema',
    start: 1895, end: 2025,
    region: 'film-media',
    icon: '🎬',
    description: "The Lumière Brothers' first public film screening (Paris, December 28, 1895) launched cinema. The silent era produced masters of visual storytelling: Charlie Chaplin (The Kid, City Lights, Modern Times), Buster Keaton, Sergei Eisenstein (Battleship Potemkin, 1925 — montage theory). Sound arrived with The Jazz Singer (1927). Hollywood's Golden Age (1930s–1950s): Citizen Kane (Orson Welles, 1941), Casablanca, Hitchcock's thrillers. Parallel national cinemas: Italian Neorealism (Rossellini, De Sica), Japanese masters (Kurosawa's Rashomon, Seven Samurai; Ozu), Bergman's Swedish art cinema. The French New Wave (Godard, Truffaut, 1958–68) revolutionised film language. 'New Hollywood' (Coppola, Scorsese, Kubrick, Spielberg) from the early 1970s. CGI transformed visual effects (Jurassic Park, 1993). Streaming (Netflix, 2007) disrupted cinema distribution. Korean (Parasite, 2019 Best Picture), Indian (Bollywood), and global cinemas now command worldwide audiences.",
    periods: [
      { name: 'Silent Era', start: 1895, end: 1927 },
      { name: "Hollywood Golden Age", start: 1927, end: 1960 },
      { name: 'New Wave & Art Cinema', start: 1958, end: 1980 },
      { name: 'Blockbusters to Streaming', start: 1975, end: 2025 },
    ],
  },
  {
    id: 'theatre-opera',
    name: 'Theatre, Opera & Performing Arts',
    start: -500, end: 2025,
    region: 'performing',
    icon: '🎭',
    description: "Greek theatre (from c. 534 BCE) invented Western dramatic form: tragedy (Aeschylus, Sophocles, Euripides — Oedipus, Medea, Electra) and comedy (Aristophanes, Menander) performed in great open-air theatres to thousands of citizens. Opera emerged in Florence c. 1600 (Monteverdi's Orfeo, 1607) as a fusion of music, drama, and spectacle. Opera's golden age: Mozart (Don Giovanni, The Magic Flute), Verdi (Aida, Rigoletto, La Traviata, Otello), Wagner (Tristan und Isolde, Ring cycle — totale Kunstwerk), Puccini (La Bohème, Tosca, Madama Butterfly), and Strauss. Ballet developed from French court entertainment (Louis XIV) through Romantic ballet (Giselle, Swan Lake — Tchaikovsky's score) to Diaghilev's Ballets Russes (1909–1929, with Stravinsky, Nijinsky, Picasso). The 20th century brought Broadway musical theatre (Gershwin, Rodgers & Hammerstein, Sondheim, Lloyd Webber) and modern dance (Martha Graham, Merce Cunningham).",
    periods: [
      { name: 'Greek & Roman Theatre', start: -500, end: 400 },
      { name: 'Opera & Ballet Origins', start: 1600, end: 1850 },
      { name: 'Romantic & Verdi/Wagner Era', start: 1830, end: 1910 },
      { name: 'Broadway & Modern Dance', start: 1920, end: 2025 },
    ],
  },
];
