export const regions = [
  { id: 'middle-east', name: 'Middle East', color: '#F59E0B' },
  { id: 'africa', name: 'Africa', color: '#10B981' },
  { id: 'europe', name: 'Europe', color: '#6366F1' },
  { id: 'east-asia', name: 'East Asia', color: '#EF4444' },
  { id: 'south-asia', name: 'South Asia', color: '#EC4899' },
  { id: 'americas', name: 'Americas', color: '#8B5CF6' },
  { id: 'central-asia', name: 'Central Asia', color: '#14B8A6' },
];

export const civilisations = [
  {
    id: 'mesopotamia',
    name: 'Mesopotamia',
    start: -3500,
    end: -539,
    region: 'middle-east',
    icon: '🏺',
    description: 'The cradle of civilisation between the Tigris and Euphrates rivers. Home to Sumer, Akkad, Babylon, and Assyria — where writing, law, and urban life first emerged.',
    periods: [
      { name: 'Sumer', start: -3500, end: -2334 },
      { name: 'Akkadian Empire', start: -2334, end: -2154 },
      { name: 'Babylonian Empire', start: -1894, end: -1595 },
      { name: 'Assyrian Empire', start: -911, end: -609 },
      { name: 'Neo-Babylonian', start: -626, end: -539 },
    ],
  },
  {
    id: 'ancient-egypt',
    name: 'Ancient Egypt',
    start: -3100,
    end: -30,
    region: 'africa',
    icon: '🔺',
    description: 'One of the longest-lasting civilisations in history, spanning over 3,000 years along the Nile. Built the pyramids, developed hieroglyphics, and created an extraordinarily rich culture.',
    periods: [
      { name: 'Old Kingdom', start: -2686, end: -2181 },
      { name: 'Middle Kingdom', start: -2055, end: -1650 },
      { name: 'New Kingdom', start: -1550, end: -1077 },
      { name: 'Ptolemaic', start: -305, end: -30 },
    ],
  },
  {
    id: 'phoenicia',
    name: 'Phoenicia',
    start: -1500,
    end: -300,
    region: 'middle-east',
    icon: '⛵',
    description: 'A seafaring civilisation based in modern-day Lebanon. The Phoenicians invented the alphabet, founded Carthage, and established trade networks across the entire Mediterranean.',
    periods: [],
  },
  {
    id: 'ancient-china-shang',
    name: 'Shang Dynasty',
    start: -1600,
    end: -1046,
    region: 'east-asia',
    icon: '🐉',
    description: 'The first historically verified Chinese dynasty. Developed early Chinese writing, bronze casting, and established the foundations of Chinese civilisation.',
    periods: [],
  },
  {
    id: 'ancient-china-zhou',
    name: 'Zhou Dynasty',
    start: -1046,
    end: -256,
    region: 'east-asia',
    icon: '🐉',
    description: 'The longest-reigning dynasty in Chinese history. The era of Confucius, Laozi, and the Hundred Schools of Thought that shaped Chinese philosophy.',
    periods: [
      { name: 'Western Zhou', start: -1046, end: -771 },
      { name: 'Eastern Zhou', start: -770, end: -256 },
    ],
  },
  {
    id: 'persian-achaemenid',
    name: 'Persian Empire (Achaemenid)',
    start: -550,
    end: -330,
    region: 'middle-east',
    icon: '🦁',
    description: 'The first true superpower — at its height stretching from Egypt to India. Founded by Cyrus the Great, known for tolerance, infrastructure, and the Royal Road.',
    periods: [],
  },
  {
    id: 'classical-greece',
    name: 'Classical Greece',
    start: -508,
    end: -146,
    region: 'europe',
    icon: '🏛️',
    description: 'The birthplace of democracy, philosophy, theatre, and Western civilisation. Home to Athens, Sparta, and the great thinkers — Socrates, Plato, and Aristotle.',
    periods: [
      { name: 'Golden Age of Athens', start: -480, end: -404 },
      { name: 'Hellenistic Period', start: -323, end: -146 },
    ],
  },
  {
    id: 'maurya',
    name: 'Maurya Empire',
    start: -322,
    end: -185,
    region: 'south-asia',
    icon: '☸️',
    description: 'The first empire to unify most of the Indian subcontinent. Under Emperor Ashoka, it became a beacon of Buddhist values and non-violence.',
    periods: [],
  },
  {
    id: 'qin-dynasty',
    name: 'Qin Dynasty',
    start: -221,
    end: -206,
    region: 'east-asia',
    icon: '🏯',
    description: 'Though short-lived, the Qin unified China for the first time, standardised writing and measurement, and began construction of the Great Wall.',
    periods: [],
  },
  {
    id: 'han-dynasty',
    name: 'Han Dynasty',
    start: -206,
    end: 220,
    region: 'east-asia',
    icon: '🐉',
    description: 'A golden age of Chinese civilisation lasting over 400 years. Established the Silk Road, advanced paper-making, and created a model of governance that lasted millennia.',
    periods: [
      { name: 'Western Han', start: -206, end: 9 },
      { name: 'Eastern Han', start: 25, end: 220 },
    ],
  },
  {
    id: 'roman-empire',
    name: 'Roman Empire',
    start: -27,
    end: 476,
    region: 'europe',
    icon: '🏛️',
    description: 'From Augustus to the fall of the West — the Roman Empire shaped Western law, language, engineering, and culture. At its peak it ruled over 70 million people.',
    periods: [
      { name: 'Pax Romana', start: 27, end: 180 },
      { name: 'Crisis of the Third Century', start: 235, end: 284 },
    ],
  },
  {
    id: 'maya',
    name: 'Maya Civilisation',
    start: -2000,
    end: 1500,
    region: 'americas',
    icon: '🌽',
    description: 'A Mesoamerican civilisation renowned for its mathematics, astronomy, calendar systems, and monumental architecture including stepped pyramids.',
    periods: [
      { name: 'Classic Period', start: 250, end: 900 },
    ],
  },
  {
    id: 'byzantine',
    name: 'Byzantine Empire',
    start: 330,
    end: 1453,
    region: 'europe',
    icon: '⛪',
    description: 'The Eastern Roman Empire, centred on Constantinople. Preserved Greek and Roman knowledge through the Middle Ages and was a major centre of art, learning, and Christianity.',
    periods: [
      { name: 'Justinian Era', start: 527, end: 565 },
      { name: 'Macedonian Renaissance', start: 867, end: 1056 },
    ],
  },
  {
    id: 'gupta',
    name: 'Gupta Empire',
    start: 320,
    end: 550,
    region: 'south-asia',
    icon: '🕉️',
    description: 'The Golden Age of India. Advances in mathematics (including the concept of zero), astronomy, literature, and art flourished during this period.',
    periods: [],
  },
  {
    id: 'tang-dynasty',
    name: 'Tang Dynasty',
    start: 618,
    end: 907,
    region: 'east-asia',
    icon: '🐉',
    description: 'Often considered the high point of Chinese civilisation. A cosmopolitan golden age of poetry, art, and technology that influenced all of East Asia.',
    periods: [],
  },
  {
    id: 'umayyad-caliphate',
    name: 'Umayyad Caliphate',
    start: 661,
    end: 750,
    region: 'middle-east',
    icon: '☪️',
    description: 'The second of the four major caliphates. At its peak, the largest empire the world had yet seen, stretching from Spain to Central Asia.',
    periods: [],
  },
  {
    id: 'abbasid-caliphate',
    name: 'Abbasid Caliphate',
    start: 750,
    end: 1258,
    region: 'middle-east',
    icon: '☪️',
    description: 'The Islamic Golden Age. Baghdad became the world\'s centre of learning, science, and culture. Algebra, optics, and medicine all advanced dramatically.',
    periods: [
      { name: 'Islamic Golden Age', start: 786, end: 1258 },
    ],
  },
  {
    id: 'viking-age',
    name: 'Viking Age',
    start: 793,
    end: 1066,
    region: 'europe',
    icon: '⚔️',
    description: 'Norse seafarers from Scandinavia explored, traded, and raided across Europe, reaching North America centuries before Columbus.',
    periods: [],
  },
  {
    id: 'song-dynasty',
    name: 'Song Dynasty',
    start: 960,
    end: 1279,
    region: 'east-asia',
    icon: '🐉',
    description: 'An era of remarkable technological innovation — gunpowder, the compass, movable type printing, and the world\'s first paper money all emerged during the Song.',
    periods: [],
  },
  {
    id: 'mongol-empire',
    name: 'Mongol Empire',
    start: 1206,
    end: 1368,
    region: 'central-asia',
    icon: '🏇',
    description: 'The largest contiguous land empire in history, founded by Genghis Khan. Connected East and West through trade and cultural exchange along the Silk Road.',
    periods: [],
  },
  {
    id: 'aztec',
    name: 'Aztec Empire',
    start: 1428,
    end: 1521,
    region: 'americas',
    icon: '🦅',
    description: 'A powerful Mesoamerican empire centred on Tenochtitlan (modern Mexico City), with advanced agriculture, architecture, and a complex social structure.',
    periods: [],
  },
  {
    id: 'ottoman',
    name: 'Ottoman Empire',
    start: 1299,
    end: 1922,
    region: 'middle-east',
    icon: '🌙',
    description: 'One of the largest and longest-lasting empires in history. At its height it controlled Southeast Europe, Western Asia, and North Africa from its capital in Constantinople.',
    periods: [
      { name: 'Classical Age', start: 1453, end: 1566 },
    ],
  },
  {
    id: 'inca',
    name: 'Inca Empire',
    start: 1438,
    end: 1533,
    region: 'americas',
    icon: '🏔️',
    description: 'The largest empire in pre-Columbian America, stretching along the Andes. Built Machu Picchu and an extraordinary road network without the use of the wheel.',
    periods: [],
  },
  {
    id: 'ming-dynasty',
    name: 'Ming Dynasty',
    start: 1368,
    end: 1644,
    region: 'east-asia',
    icon: '🐉',
    description: 'Rebuilt the Great Wall, constructed the Forbidden City, and sent Zheng He\'s treasure fleets across the Indian Ocean. A period of cultural and economic flourishing.',
    periods: [],
  },
  {
    id: 'mughal',
    name: 'Mughal Empire',
    start: 1526,
    end: 1857,
    region: 'south-asia',
    icon: '🕌',
    description: 'A powerful Islamic empire in the Indian subcontinent. Built the Taj Mahal and presided over a remarkable fusion of Persian, Indian, and Islamic cultures.',
    periods: [
      { name: 'Golden Age', start: 1556, end: 1707 },
    ],
  },
  {
    id: 'qing-dynasty',
    name: 'Qing Dynasty',
    start: 1644,
    end: 1912,
    region: 'east-asia',
    icon: '🐉',
    description: 'The last imperial dynasty of China. Expanded Chinese territory to its greatest extent and presided over both a prosperous golden age and a turbulent decline.',
    periods: [],
  },
  {
    id: 'british-empire',
    name: 'British Empire',
    start: 1583,
    end: 1997,
    region: 'europe',
    icon: '🇬🇧',
    description: 'The largest empire in history by territorial extent. At its peak it governed nearly a quarter of the world\'s population and land area.',
    periods: [
      { name: 'Height of Empire', start: 1815, end: 1914 },
    ],
  },
];
