export const regions = [
  { id: 'middle-east', name: 'Middle East', color: '#F59E0B' },
  { id: 'africa', name: 'Africa', color: '#10B981' },
  { id: 'europe', name: 'Europe', color: '#6366F1' },
  { id: 'east-asia', name: 'East Asia', color: '#EF4444' },
  { id: 'south-asia', name: 'South Asia', color: '#EC4899' },
  { id: 'southeast-asia', name: 'Southeast Asia', color: '#F97316' },
  { id: 'americas', name: 'Americas', color: '#8B5CF6' },
  { id: 'central-asia', name: 'Central Asia', color: '#14B8A6' },
];

export const civilisations = [
  // =========================================================
  // MIDDLE EAST
  // =========================================================
  {
    id: 'mesopotamia',
    name: 'Mesopotamia',
    start: -3500,
    end: -539,
    region: 'middle-east',
    icon: '🏺',
    description: 'The cradle of civilisation between the Tigris and Euphrates rivers. Home to Sumer, Akkad, Babylon, and Assyria — where writing, law, and urban life first emerged.',
    periods: [
      { name: 'Sumer', start: -3500, end: -2334 },
      { name: 'Akkadian Empire', start: -2334, end: -2154 },
      { name: 'Babylonian Empire', start: -1894, end: -1595 },
      { name: 'Assyrian Empire', start: -911, end: -609 },
      { name: 'Neo-Babylonian', start: -626, end: -539 },
    ],
  },
  {
    id: 'phoenicia',
    name: 'Phoenicia',
    start: -1500,
    end: -300,
    region: 'middle-east',
    icon: '⛵',
    description: 'A seafaring civilisation based in modern-day Lebanon. The Phoenicians invented the alphabet, founded Carthage, and established trade networks across the entire Mediterranean.',
    periods: [],
  },
  {
    id: 'persian-achaemenid',
    name: 'Persian Empire (Achaemenid)',
    start: -550,
    end: -330,
    region: 'middle-east',
    icon: '🦁',
    description: 'The first true superpower — at its height stretching from Egypt to India. Founded by Cyrus the Great, known for tolerance, infrastructure, and the Royal Road.',
    periods: [],
  },
  {
    id: 'seleucid',
    name: 'Seleucid Empire',
    start: -312,
    end: -63,
    region: 'middle-east',
    icon: '⚔️',
    description: 'One of the successor states of Alexander the Great\'s empire. Ruled a vast territory from Anatolia to Central Asia, blending Greek and Eastern cultures in the Hellenistic tradition.',
    periods: [],
  },
  {
    id: 'parthian',
    name: 'Parthian Empire',
    start: -247,
    end: 224,
    region: 'middle-east',
    icon: '🏹',
    description: 'A major Iranian political and cultural power that rivalled Rome for centuries. Famous for their mounted archers and the Silk Road trade that passed through their territory.',
    periods: [],
  },
  {
    id: 'sassanid',
    name: 'Sassanid Empire',
    start: 224,
    end: 651,
    region: 'middle-east',
    icon: '🦁',
    description: 'The last great pre-Islamic Persian empire. A cultural golden age that saw advances in art, architecture, and science, and served as Rome\'s greatest rival in the East.',
    periods: [],
  },
  {
    id: 'umayyad-caliphate',
    name: 'Umayyad Caliphate',
    start: 661,
    end: 750,
    region: 'middle-east',
    icon: '☪️',
    description: 'The second of the four major caliphates. At its peak, the largest empire the world had yet seen, stretching from Spain to Central Asia.',
    periods: [],
  },
  {
    id: 'abbasid-caliphate',
    name: 'Abbasid Caliphate',
    start: 750,
    end: 1258,
    region: 'middle-east',
    icon: '☪️',
    description: 'The Islamic Golden Age. Baghdad became the world\'s centre of learning, science, and culture. Algebra, optics, and medicine all advanced dramatically.',
    periods: [
      { name: 'Islamic Golden Age', start: 786, end: 1258 },
    ],
  },
  {
    id: 'ottoman',
    name: 'Ottoman Empire',
    start: 1299,
    end: 1922,
    region: 'middle-east',
    icon: '🌙',
    description: 'One of the largest and longest-lasting empires in history. At its height it controlled Southeast Europe, Western Asia, and North Africa from its capital in Constantinople.',
    periods: [
      { name: 'Classical Age', start: 1453, end: 1566 },
    ],
  },
  {
    id: 'safavid',
    name: 'Safavid Empire',
    start: 1501,
    end: 1736,
    region: 'middle-east',
    icon: '🕌',
    description: 'Established Shia Islam as Iran\'s official religion and presided over a cultural renaissance. Isfahan became one of the world\'s most beautiful cities under Shah Abbas.',
    periods: [
      { name: 'Golden Age', start: 1587, end: 1629 },
    ],
  },

  // =========================================================
  // AFRICA
  // =========================================================
  {
    id: 'ancient-egypt',
    name: 'Ancient Egypt',
    start: -3100,
    end: -30,
    region: 'africa',
    icon: '🔺',
    description: 'One of the longest-lasting civilisations in history, spanning over 3,000 years along the Nile. Built the pyramids, developed hieroglyphics, and created an extraordinarily rich culture.',
    periods: [
      { name: 'Old Kingdom', start: -2686, end: -2181 },
      { name: 'Middle Kingdom', start: -2055, end: -1650 },
      { name: 'New Kingdom', start: -1550, end: -1077 },
      { name: 'Ptolemaic', start: -305, end: -30 },
    ],
  },
  {
    id: 'kush',
    name: 'Kingdom of Kush',
    start: -1070,
    end: 350,
    region: 'africa',
    icon: '🏛️',
    description: 'A powerful Nubian kingdom south of Egypt that at times ruled Egypt itself. Built more pyramids than Egypt and was a major iron-producing centre of the ancient world.',
    periods: [
      { name: 'Napatan Period', start: -750, end: -590 },
      { name: 'Meroitic Period', start: -590, end: 350 },
    ],
  },
  {
    id: 'carthage',
    name: 'Carthage',
    start: -814,
    end: -146,
    region: 'africa',
    icon: '⛵',
    description: 'A powerful Phoenician city-state in North Africa that dominated western Mediterranean trade. Under Hannibal, it nearly conquered Rome in the Punic Wars.',
    periods: [],
  },
  {
    id: 'axum',
    name: 'Kingdom of Axum',
    start: 100,
    end: 940,
    region: 'africa',
    icon: '⛪',
    description: 'A major trading empire in modern-day Ethiopia and Eritrea. One of the first states to adopt Christianity, it minted its own coins and erected towering stone obelisks.',
    periods: [],
  },
  {
    id: 'ghana-empire',
    name: 'Ghana Empire',
    start: 300,
    end: 1200,
    region: 'africa',
    icon: '👑',
    description: 'The first great West African empire, known as the "Land of Gold". Controlled trans-Saharan gold and salt trade routes and built a sophisticated system of governance.',
    periods: [],
  },
  {
    id: 'ethiopian-empire',
    name: 'Ethiopian Empire',
    start: 1270,
    end: 1974,
    region: 'africa',
    icon: '🦁',
    description: 'One of the longest-lived states in Africa, claiming descent from King Solomon. One of only two African nations never colonised by a European power.',
    periods: [
      { name: 'Solomonic Dynasty', start: 1270, end: 1974 },
    ],
  },
  {
    id: 'mali-empire',
    name: 'Mali Empire',
    start: 1235,
    end: 1600,
    region: 'africa',
    icon: '👑',
    description: 'A West African empire famous for Mansa Musa, possibly the wealthiest person in history. Timbuktu became a world centre of Islamic learning and scholarship.',
    periods: [],
  },
  {
    id: 'great-zimbabwe',
    name: 'Great Zimbabwe',
    start: 1100,
    end: 1450,
    region: 'africa',
    icon: '🏰',
    description: 'A medieval African city and trading centre in southern Africa. Its massive stone ruins — built without mortar — are among the most impressive structures in pre-colonial Africa.',
    periods: [],
  },
  {
    id: 'songhai',
    name: 'Songhai Empire',
    start: 1430,
    end: 1591,
    region: 'africa',
    icon: '👑',
    description: 'The largest empire in African history by territory. Succeeded Mali and made Timbuktu and Djenné flourishing centres of trade, religion, and learning.',
    periods: [],
  },
  {
    id: 'kongo',
    name: 'Kingdom of Kongo',
    start: 1390,
    end: 1914,
    region: 'africa',
    icon: '🌍',
    description: 'A powerful Central African kingdom that engaged in diplomacy with Portugal and the Vatican. Its history was deeply affected by the transatlantic slave trade.',
    periods: [],
  },
  {
    id: 'zulu',
    name: 'Zulu Kingdom',
    start: 1816,
    end: 1897,
    region: 'africa',
    icon: '🛡️',
    description: 'A powerful Southern African state forged by Shaka Zulu through military innovation. Famously defeated a British force at Isandlwana before being conquered.',
    periods: [],
  },

  // =========================================================
  // EUROPE
  // =========================================================
  {
    id: 'classical-greece',
    name: 'Classical Greece',
    start: -508,
    end: -146,
    region: 'europe',
    icon: '🏛️',
    description: 'The birthplace of democracy, philosophy, theatre, and Western civilisation. Home to Athens, Sparta, and the great thinkers — Socrates, Plato, and Aristotle.',
    periods: [
      { name: 'Golden Age of Athens', start: -480, end: -404 },
      { name: 'Hellenistic Period', start: -323, end: -146 },
    ],
  },
  {
    id: 'roman-empire',
    name: 'Roman Empire',
    start: -27,
    end: 476,
    region: 'europe',
    icon: '🏛️',
    description: 'From Augustus to the fall of the West — the Roman Empire shaped Western law, language, engineering, and culture. At its peak it ruled over 70 million people.',
    periods: [
      { name: 'Pax Romana', start: 27, end: 180 },
      { name: 'Crisis of the Third Century', start: 235, end: 284 },
    ],
  },
  {
    id: 'byzantine',
    name: 'Byzantine Empire',
    start: 330,
    end: 1453,
    region: 'europe',
    icon: '⛪',
    description: 'The Eastern Roman Empire, centred on Constantinople. Preserved Greek and Roman knowledge through the Middle Ages and was a major centre of art, learning, and Christianity.',
    periods: [
      { name: 'Justinian Era', start: 527, end: 565 },
      { name: 'Macedonian Renaissance', start: 867, end: 1056 },
    ],
  },
  {
    id: 'frankish',
    name: 'Frankish / Carolingian Empire',
    start: 481,
    end: 843,
    region: 'europe',
    icon: '⚜️',
    description: 'From Clovis to Charlemagne — the Franks united much of Western Europe after Rome\'s fall. Charlemagne was crowned Emperor in 800, reviving the idea of a European empire.',
    periods: [
      { name: 'Carolingian Dynasty', start: 751, end: 843 },
    ],
  },
  {
    id: 'viking-age',
    name: 'Viking Age',
    start: 793,
    end: 1066,
    region: 'europe',
    icon: '⚔️',
    description: 'Norse seafarers from Scandinavia explored, traded, and raided across Europe, reaching North America centuries before Columbus.',
    periods: [],
  },
  {
    id: 'kievan-rus',
    name: 'Kievan Rus\'',
    start: 882,
    end: 1240,
    region: 'europe',
    icon: '🏰',
    description: 'A federation of Slavic tribes centred on Kyiv that became the cultural ancestor of modern Russia, Ukraine, and Belarus. Adopted Orthodox Christianity in 988.',
    periods: [],
  },
  {
    id: 'holy-roman-empire',
    name: 'Holy Roman Empire',
    start: 962,
    end: 1806,
    region: 'europe',
    icon: '👑',
    description: 'A complex political entity in Central Europe that claimed to be the successor of Rome. A patchwork of kingdoms, duchies, and city-states that shaped European politics for centuries.',
    periods: [],
  },
  {
    id: 'venice',
    name: 'Republic of Venice',
    start: 697,
    end: 1797,
    region: 'europe',
    icon: '🦁',
    description: 'A maritime republic that dominated Mediterranean trade for centuries. A centre of art, architecture, and commerce, Venice was one of the wealthiest cities in the world.',
    periods: [
      { name: 'Height of Power', start: 1200, end: 1500 },
    ],
  },
  {
    id: 'portugal',
    name: 'Portuguese Empire',
    start: 1139,
    end: 1999,
    region: 'europe',
    icon: '⛵',
    description: 'The first global maritime empire. Portuguese navigators pioneered the Age of Discovery, establishing trade posts from Brazil to Japan and transforming global trade.',
    periods: [
      { name: 'Age of Discovery', start: 1415, end: 1543 },
    ],
  },
  {
    id: 'spanish-empire',
    name: 'Spanish Empire',
    start: 1492,
    end: 1976,
    region: 'europe',
    icon: '🏴',
    description: 'One of the first global empires and the first to be called "the empire on which the sun never sets". Conquered vast territories in the Americas, Asia, and Africa.',
    periods: [
      { name: 'Golden Age', start: 1492, end: 1659 },
    ],
  },
  {
    id: 'dutch-republic',
    name: 'Dutch Republic / Empire',
    start: 1581,
    end: 1795,
    region: 'europe',
    icon: '🌷',
    description: 'A small republic that became a global superpower through trade, banking, and naval might. The Dutch Golden Age produced Rembrandt, Vermeer, and the world\'s first stock exchange.',
    periods: [
      { name: 'Dutch Golden Age', start: 1588, end: 1672 },
    ],
  },
  {
    id: 'french-colonial',
    name: 'French Colonial Empire',
    start: 1534,
    end: 1980,
    region: 'europe',
    icon: '🇫🇷',
    description: 'The second-largest colonial empire in history. From New France in Canada to vast territories across Africa and Indochina, France\'s global reach shaped the modern world.',
    periods: [
      { name: 'Second Colonial Empire', start: 1830, end: 1962 },
    ],
  },
  {
    id: 'russian-empire',
    name: 'Russian Empire',
    start: 1721,
    end: 1917,
    region: 'europe',
    icon: '🦅',
    description: 'The third-largest empire in history, stretching from Eastern Europe across Siberia to Alaska. A land of tsars, revolution, and vast cultural achievement.',
    periods: [],
  },
  {
    id: 'british-empire',
    name: 'British Empire',
    start: 1583,
    end: 1997,
    region: 'europe',
    icon: '🇬🇧',
    description: 'The largest empire in history by territorial extent. At its peak it governed nearly a quarter of the world\'s population and land area.',
    periods: [
      { name: 'Height of Empire', start: 1815, end: 1914 },
    ],
  },
  {
    id: 'austro-hungarian',
    name: 'Austro-Hungarian Empire',
    start: 1867,
    end: 1918,
    region: 'europe',
    icon: '🦅',
    description: 'A dual monarchy in Central Europe uniting Austria and Hungary. A multi-ethnic empire whose collapse after World War I reshaped the map of Europe.',
    periods: [],
  },

  // =========================================================
  // EAST ASIA
  // =========================================================
  {
    id: 'ancient-china-shang',
    name: 'Shang Dynasty',
    start: -1600,
    end: -1046,
    region: 'east-asia',
    icon: '🐉',
    description: 'The first historically verified Chinese dynasty. Developed early Chinese writing, bronze casting, and established the foundations of Chinese civilisation.',
    periods: [],
  },
  {
    id: 'ancient-china-zhou',
    name: 'Zhou Dynasty',
    start: -1046,
    end: -256,
    region: 'east-asia',
    icon: '🐉',
    description: 'The longest-reigning dynasty in Chinese history. The era of Confucius, Laozi, and the Hundred Schools of Thought that shaped Chinese philosophy.',
    periods: [
      { name: 'Western Zhou', start: -1046, end: -771 },
      { name: 'Eastern Zhou', start: -770, end: -256 },
    ],
  },
  {
    id: 'qin-dynasty',
    name: 'Qin Dynasty',
    start: -221,
    end: -206,
    region: 'east-asia',
    icon: '🏯',
    description: 'Though short-lived, the Qin unified China for the first time, standardised writing and measurement, and began construction of the Great Wall.',
    periods: [],
  },
  {
    id: 'han-dynasty',
    name: 'Han Dynasty',
    start: -206,
    end: 220,
    region: 'east-asia',
    icon: '🐉',
    description: 'A golden age of Chinese civilisation lasting over 400 years. Established the Silk Road, advanced paper-making, and created a model of governance that lasted millennia.',
    periods: [
      { name: 'Western Han', start: -206, end: 9 },
      { name: 'Eastern Han', start: 25, end: 220 },
    ],
  },
  {
    id: 'tang-dynasty',
    name: 'Tang Dynasty',
    start: 618,
    end: 907,
    region: 'east-asia',
    icon: '🐉',
    description: 'Often considered the high point of Chinese civilisation. A cosmopolitan golden age of poetry, art, and technology that influenced all of East Asia.',
    periods: [],
  },
  {
    id: 'heian-japan',
    name: 'Nara & Heian Japan',
    start: 710,
    end: 1185,
    region: 'east-asia',
    icon: '🏯',
    description: 'Japan\'s classical era. The imperial court at Kyoto produced The Tale of Genji, refined court culture, and distinctly Japanese art forms while adopting Chinese influences.',
    periods: [
      { name: 'Nara Period', start: 710, end: 794 },
      { name: 'Heian Period', start: 794, end: 1185 },
    ],
  },
  {
    id: 'goryeo',
    name: 'Goryeo Dynasty (Korea)',
    start: 918,
    end: 1392,
    region: 'east-asia',
    icon: '🇰🇷',
    description: 'A Korean dynasty that gave Korea its Western name. Produced the world\'s first metal movable type and the Tripitaka Koreana, a masterpiece of Buddhist scripture.',
    periods: [],
  },
  {
    id: 'song-dynasty',
    name: 'Song Dynasty',
    start: 960,
    end: 1279,
    region: 'east-asia',
    icon: '🐉',
    description: 'An era of remarkable technological innovation — gunpowder, the compass, movable type printing, and the world\'s first paper money all emerged during the Song.',
    periods: [],
  },
  {
    id: 'kamakura-muromachi',
    name: 'Kamakura & Muromachi Japan',
    start: 1185,
    end: 1573,
    region: 'east-asia',
    icon: '⚔️',
    description: 'The age of the samurai and shoguns. Zen Buddhism, tea ceremony, Noh theatre, and the warrior code of bushido defined Japanese culture during this period.',
    periods: [
      { name: 'Kamakura', start: 1185, end: 1333 },
      { name: 'Muromachi', start: 1336, end: 1573 },
    ],
  },
  {
    id: 'ming-dynasty',
    name: 'Ming Dynasty',
    start: 1368,
    end: 1644,
    region: 'east-asia',
    icon: '🐉',
    description: 'Rebuilt the Great Wall, constructed the Forbidden City, and sent Zheng He\'s treasure fleets across the Indian Ocean. A period of cultural and economic flourishing.',
    periods: [],
  },
  {
    id: 'joseon',
    name: 'Joseon Dynasty (Korea)',
    start: 1392,
    end: 1897,
    region: 'east-asia',
    icon: '🇰🇷',
    description: 'Korea\'s longest-lived dynasty. Created Hangul, the Korean alphabet, and established a Confucian-based society renowned for its scholarship, art, and bureaucratic governance.',
    periods: [],
  },
  {
    id: 'tokugawa',
    name: 'Tokugawa Shogunate',
    start: 1603,
    end: 1868,
    region: 'east-asia',
    icon: '🏯',
    description: 'Over 250 years of peace and isolation under the Tokugawa shoguns. A flourishing of Japanese arts — kabuki, ukiyo-e, haiku — alongside rigid social order.',
    periods: [],
  },
  {
    id: 'qing-dynasty',
    name: 'Qing Dynasty',
    start: 1644,
    end: 1912,
    region: 'east-asia',
    icon: '🐉',
    description: 'The last imperial dynasty of China. Expanded Chinese territory to its greatest extent and presided over both a prosperous golden age and a turbulent decline.',
    periods: [],
  },
  {
    id: 'meiji-japan',
    name: 'Imperial Japan',
    start: 1868,
    end: 1947,
    region: 'east-asia',
    icon: '🇯🇵',
    description: 'Japan\'s rapid modernisation from feudal state to industrial world power in barely a generation. The Meiji Restoration transformed every aspect of Japanese society.',
    periods: [
      { name: 'Meiji Era', start: 1868, end: 1912 },
    ],
  },

  // =========================================================
  // SOUTH ASIA
  // =========================================================
  {
    id: 'maurya',
    name: 'Maurya Empire',
    start: -322,
    end: -185,
    region: 'south-asia',
    icon: '☸️',
    description: 'The first empire to unify most of the Indian subcontinent. Under Emperor Ashoka, it became a beacon of Buddhist values and non-violence.',
    periods: [],
  },
  {
    id: 'kushan',
    name: 'Kushan Empire',
    start: 30,
    end: 375,
    region: 'south-asia',
    icon: '🛕',
    description: 'A Central Asian dynasty that ruled over much of northern India, Afghanistan, and Central Asia. Facilitated Silk Road trade and the spread of Buddhism to East Asia.',
    periods: [],
  },
  {
    id: 'chola',
    name: 'Chola Dynasty',
    start: 300,
    end: 1279,
    region: 'south-asia',
    icon: '🐅',
    description: 'One of the longest-ruling dynasties in world history. Built a powerful navy that dominated the Indian Ocean, and created masterpieces of Dravidian temple architecture.',
    periods: [
      { name: 'Imperial Chola', start: 850, end: 1279 },
    ],
  },
  {
    id: 'gupta',
    name: 'Gupta Empire',
    start: 320,
    end: 550,
    region: 'south-asia',
    icon: '🕉️',
    description: 'The Golden Age of India. Advances in mathematics (including the concept of zero), astronomy, literature, and art flourished during this period.',
    periods: [],
  },
  {
    id: 'delhi-sultanate',
    name: 'Delhi Sultanate',
    start: 1206,
    end: 1526,
    region: 'south-asia',
    icon: '🕌',
    description: 'A succession of Islamic dynasties that ruled from Delhi. Repelled Mongol invasions and established Persian-influenced court culture across northern India.',
    periods: [],
  },
  {
    id: 'mughal',
    name: 'Mughal Empire',
    start: 1526,
    end: 1857,
    region: 'south-asia',
    icon: '🕌',
    description: 'A powerful Islamic empire in the Indian subcontinent. Built the Taj Mahal and presided over a remarkable fusion of Persian, Indian, and Islamic cultures.',
    periods: [
      { name: 'Golden Age', start: 1556, end: 1707 },
    ],
  },
  {
    id: 'maratha',
    name: 'Maratha Empire',
    start: 1674,
    end: 1818,
    region: 'south-asia',
    icon: '🐎',
    description: 'A Hindu empire that challenged and eventually replaced Mughal dominance across much of India. Founded by the warrior king Shivaji.',
    periods: [],
  },
  {
    id: 'sikh-empire',
    name: 'Sikh Empire',
    start: 1799,
    end: 1849,
    region: 'south-asia',
    icon: '☬',
    description: 'A powerful state in the Punjab founded by Maharaja Ranjit Singh. One of the last major independent powers in India before British conquest.',
    periods: [],
  },
  {
    id: 'british-raj',
    name: 'British Raj',
    start: 1858,
    end: 1947,
    region: 'south-asia',
    icon: '🇬🇧',
    description: 'Direct British rule over the Indian subcontinent. A period of railways, industrialisation, and growing nationalist movements that culminated in independence.',
    periods: [],
  },

  // =========================================================
  // SOUTHEAST ASIA
  // =========================================================
  {
    id: 'srivijaya',
    name: 'Srivijaya',
    start: 650,
    end: 1377,
    region: 'southeast-asia',
    icon: '⛵',
    description: 'A powerful maritime empire based in Sumatra that controlled the Strait of Malacca. A major centre of Buddhist learning and a gateway for trade between India and China.',
    periods: [],
  },
  {
    id: 'khmer',
    name: 'Khmer Empire',
    start: 802,
    end: 1431,
    region: 'southeast-asia',
    icon: '🛕',
    description: 'Builders of Angkor Wat, the largest religious monument in the world. At its peak, the Khmer Empire was one of the most powerful states in Southeast Asia.',
    periods: [
      { name: 'Classical Period', start: 802, end: 1220 },
    ],
  },
  {
    id: 'majapahit',
    name: 'Majapahit Empire',
    start: 1293,
    end: 1527,
    region: 'southeast-asia',
    icon: '🌺',
    description: 'The last great Hindu-Buddhist empire of Southeast Asia, based in Java. Controlled much of the Indonesian archipelago and parts of the Malay Peninsula.',
    periods: [],
  },

  // =========================================================
  // AMERICAS
  // =========================================================
  {
    id: 'olmec',
    name: 'Olmec Civilisation',
    start: -1500,
    end: -400,
    region: 'americas',
    icon: '🗿',
    description: 'Often called the "mother culture" of Mesoamerica. Created colossal stone heads, developed early writing and calendar systems, and influenced all later civilisations in the region.',
    periods: [],
  },
  {
    id: 'maya',
    name: 'Maya Civilisation',
    start: -2000,
    end: 1500,
    region: 'americas',
    icon: '🌽',
    description: 'A Mesoamerican civilisation renowned for its mathematics, astronomy, calendar systems, and monumental architecture including stepped pyramids.',
    periods: [
      { name: 'Classic Period', start: 250, end: 900 },
    ],
  },
  {
    id: 'mississippian',
    name: 'Mississippian Culture',
    start: 800,
    end: 1600,
    region: 'americas',
    icon: '🏔️',
    description: 'A mound-building civilisation in eastern North America. Cahokia, near modern St Louis, was one of the largest pre-Columbian cities north of Mexico.',
    periods: [],
  },
  {
    id: 'toltec',
    name: 'Toltec Empire',
    start: 900,
    end: 1168,
    region: 'americas',
    icon: '⚔️',
    description: 'A militaristic Mesoamerican civilisation centred at Tula. Revered by the Aztecs as legendary warriors and master builders.',
    periods: [],
  },
  {
    id: 'aztec',
    name: 'Aztec Empire',
    start: 1428,
    end: 1521,
    region: 'americas',
    icon: '🦅',
    description: 'A powerful Mesoamerican empire centred on Tenochtitlan (modern Mexico City), with advanced agriculture, architecture, and a complex social structure.',
    periods: [],
  },
  {
    id: 'inca',
    name: 'Inca Empire',
    start: 1438,
    end: 1533,
    region: 'americas',
    icon: '🏔️',
    description: 'The largest empire in pre-Columbian America, stretching along the Andes. Built Machu Picchu and an extraordinary road network without the use of the wheel.',
    periods: [],
  },
  {
    id: 'colonial-americas',
    name: 'Colonial Americas',
    start: 1492,
    end: 1825,
    region: 'americas',
    icon: '⛵',
    description: 'European colonisation transformed the Americas through settlement, exploitation, and the devastating exchange of diseases, forever altering the continent\'s peoples and cultures.',
    periods: [
      { name: 'Spanish Colonies', start: 1492, end: 1825 },
      { name: 'British Colonies', start: 1607, end: 1783 },
    ],
  },

  // =========================================================
  // CENTRAL ASIA
  // =========================================================
  {
    id: 'khwarezmia',
    name: 'Khwarezmian Empire',
    start: 1077,
    end: 1231,
    region: 'central-asia',
    icon: '🏰',
    description: 'A Persianate Sunni Muslim dynasty that ruled a vast territory from Iran to Central Asia. Its destruction by the Mongols triggered one of history\'s greatest conquests.',
    periods: [],
  },
  {
    id: 'mongol-empire',
    name: 'Mongol Empire',
    start: 1206,
    end: 1368,
    region: 'central-asia',
    icon: '🏇',
    description: 'The largest contiguous land empire in history, founded by Genghis Khan. Connected East and West through trade and cultural exchange along the Silk Road.',
    periods: [],
  },
  {
    id: 'timurid',
    name: 'Timurid Empire',
    start: 1370,
    end: 1507,
    region: 'central-asia',
    icon: '⚔️',
    description: 'Founded by Timur (Tamerlane), this Persianate empire was a cultural powerhouse. Samarkand became a dazzling centre of art, architecture, and astronomy.',
    periods: [],
  },
];
