export const economicsCategories = [
  { id: 'ancient-trade', name: 'Ancient Trade Networks',    color: '#F59E0B' },
  { id: 'medieval',      name: 'Medieval Commerce',         color: '#78716C' },
  { id: 'mercantilism',  name: 'Colonial & Mercantilism',   color: '#EAB308' },
  { id: 'industrial',    name: 'Industrial Economics',      color: '#3B82F6' },
  { id: 'finance',       name: 'Modern Finance',            color: '#EF4444' },
  { id: 'global',        name: 'Global Economy',            color: '#10B981' },
];

export const economicsItems = [
  {
    id: 'early-trade',
    name: 'Early Trade Networks',
    start: -3500, end: -500,
    region: 'ancient-trade',
    icon: '🏺',
    description: "Trade is as old as human civilisation. Mesopotamian merchants ('tamkārum') operated on credit 4,000 years ago — clay tablets from Ur (c. 2000 BCE) record partnerships, loans at interest, and business disputes in language familiar to modern accountants. The Phoenicians (c. 1200–800 BCE) established the ancient Mediterranean's most extensive trading network, founding Carthage and colonies across North Africa, Spain, and Sardinia. Trade in obsidian, amber, lapis lazuli, tin, and copper crossed enormous distances in the Bronze Age — the Uluburun shipwreck (c. 1300 BCE off Turkey) carried goods from Cyprus, Canaan, Egypt, Greece, and the Baltic. The Indus Valley civilisation traded with Mesopotamia; Egyptian goods reached sub-Saharan Africa.",
    periods: [
      { name: 'Mesopotamian Commerce', start: -3500, end: -2000 },
      { name: 'Bronze Age Trade Networks', start: -2000, end: -1200 },
      { name: 'Phoenician & Greek Trade', start: -1200, end: -500 },
    ],
  },
  {
    id: 'silk-road-roman',
    name: 'Silk Road & Classical Trade',
    start: -130, end: 1453,
    region: 'ancient-trade',
    icon: '⚓',
    description: "The Silk Road — not a single road but a network of overland and sea routes — linked China, Central Asia, India, the Middle East, and the Mediterranean. Zhang Qian's diplomatic missions (138–125 BCE) opened the route for the Han dynasty; silk, porcelain, paper, and spices flowed westward; glass, gold, and silver flowed east. The Roman Empire was the great consumer: Pliny the Elder complained that Rome sent a hundred million sesterces per year to India and Arabia for luxury goods. The Indian Ocean sea route (using monsoon winds, known to Greek and Arab sailors) connected Africa, Arabia, India, and Southeast Asia in a complementary maritime network. The Parthian and later Sassanid empires profited as middlemen. Arab traders eventually dominated Indian Ocean commerce from the 7th century CE.",
    periods: [
      { name: 'Han Dynasty Silk Road Opens', start: -130, end: 200 },
      { name: 'Roman & Sassanid Trade', start: 200, end: 700 },
      { name: 'Arab-Dominated Indian Ocean', start: 700, end: 1453 },
    ],
  },
  {
    id: 'islamic-commerce',
    name: 'Islamic Golden Age Commerce',
    start: 700, end: 1400,
    region: 'medieval',
    icon: '🕌',
    description: "Arab and Persian merchants created the medieval world's most extensive trading networks, bridging the Indian Ocean, Mediterranean, Sahara, and Central Asian routes. The Prophet Muhammad himself was a merchant; Islam's ethical framework (prohibiting interest but allowing profit-sharing partnerships) shaped Islamic commercial law. By 1000 CE, Arab dhows carried goods from East Africa to China. Bills of exchange (suftaja) allowed merchants to transfer money across vast distances without transporting coins — a crucial financial innovation. The Cairo Geniza documents (a cache of medieval Jewish merchant letters) reveal the cosmopolitan commercial world of the Mediterranean and Indian Ocean. Cities like Baghdad, Cairo, Samarkand, and Malacca became global commercial hubs.",
    periods: [
      { name: 'Umayyad & Abbasid Trade Expansion', start: 700, end: 1000 },
      { name: 'Islamic Commerce at its Height', start: 1000, end: 1300 },
      { name: 'Mongol Disruption & Recovery', start: 1206, end: 1400 },
    ],
  },
  {
    id: 'hanseatic-league',
    name: 'Hanseatic League',
    start: 1241, end: 1669,
    region: 'medieval',
    icon: '🏰',
    description: "The Hanseatic League was a medieval merchant confederation linking over 200 towns across northern Europe — from London and Bruges to Riga and Novgorod. Founded formally in 1241 (Hamburg-Lübeck treaty), it standardised weights and measures, established legal protections for merchants, operated in common buildings (Kontore) in foreign cities, and maintained its own fleet and sometimes military force. Its commodities: Baltic grain, timber, amber, furs, fish, cloth, and salt. The Hanse gave trading cities collective bargaining power against princes and kings — an early form of economic organisation that transcended political boundaries. It began declining in the 15th century as national states grew stronger and new Atlantic trade routes bypassed its Baltic focus.",
    periods: [
      { name: 'Hanseatic League Formation', start: 1241, end: 1356 },
      { name: 'Height of Power', start: 1356, end: 1500 },
      { name: 'Decline', start: 1500, end: 1669 },
    ],
  },
  {
    id: 'italian-banking',
    name: 'Italian Banking & Commercial Revolution',
    start: 1200, end: 1500,
    region: 'medieval',
    icon: '💰',
    description: "Medieval Italian merchants — Venetians, Genoese, Florentines — developed the financial instruments of modern capitalism. The commenda (a medieval partnership for a single voyage) separated active and passive partners, allowing merchants to pool capital and share risk. Letters of credit (lettere di cambio) allowed money to be transferred across Europe without physical transport — essential for financing papal taxation and crusades. The Bardi and Peruzzi banking families financed Edward III of England's wars (and were ruined when he defaulted). The Medici Bank (founded 1397) pioneered the holding-company structure and foreign-exchange trading. Luca Pacioli's Summa de Arithmetica (1494) codified double-entry bookkeeping — the accounting system all modern businesses use.",
    periods: [
      { name: 'Venetian & Genoese Commerce', start: 1200, end: 1350 },
      { name: 'Florentine Banking (Medici)', start: 1350, end: 1494 },
      { name: 'Pacioli & Bookkeeping Revolution', start: 1494, end: 1500 },
    ],
  },
  {
    id: 'commercial-capitalism',
    name: 'Commercial Capitalism & Colonial Trade',
    start: 1492, end: 1700,
    region: 'mercantilism',
    icon: '🌍',
    description: "Columbus's voyages (1492) and Vasco da Gama's rounding of Africa (1498) created a single integrated global economy for the first time. The Atlantic became a commercial highway: silver from Potosí (Bolivia) and Mexico flowed to Spain and then to China (paying for luxury goods); sugar from Brazil and the Caribbean enriched Portugal and later England and France; enslaved Africans were the labour that made plantation agriculture possible. The 'Colombian exchange' of crops, animals, and diseases transformed every continent's ecology and economy. Antwerp (1500s) and Amsterdam (1600s) became the world's commercial capitals. Joint-stock companies — the VOC (1602), EIC (1600) — pooled capital from thousands of shareholders to finance intercontinental trading empires, inventing the publicly traded corporation.",
    periods: [
      { name: 'Age of Discovery Trade', start: 1492, end: 1580 },
      { name: 'Atlantic Triangle Trade', start: 1580, end: 1650 },
      { name: 'Joint-Stock Companies (VOC/EIC)', start: 1600, end: 1700 },
    ],
  },
  {
    id: 'mercantilism-smith',
    name: 'Mercantilism & Birth of Economics',
    start: 1650, end: 1800,
    region: 'mercantilism',
    icon: '📊',
    description: "Mercantilism — the dominant economic doctrine of 1600–1750 — held that national wealth consisted of gold and silver, to be maximised through a trade surplus. Colonies existed to supply raw materials and buy manufactures from the mother country. Navigation Acts, tariffs, monopolies, and regulated companies enforced this system. The Physiocrats (Quesnay, Turgot, c. 1750–1780) argued that land — not trade — was the source of all wealth; their 'Tableau économique' was the first systematic economic model. Adam Smith's The Wealth of Nations (1776) demolished mercantilism: specialisation and the division of labour, not bullion accumulation, created prosperity; free markets — guided by the 'invisible hand' — allocate resources more efficiently than government direction. Smith founded modern economics.",
    periods: [
      { name: 'Height of Mercantilism', start: 1650, end: 1750 },
      { name: 'Physiocrats', start: 1750, end: 1780 },
      { name: 'Adam Smith & Classical Economics', start: 1776, end: 1800 },
    ],
  },
  {
    id: 'industrial-economics',
    name: 'Industrial Revolution Economics',
    start: 1760, end: 1870,
    region: 'industrial',
    icon: '🏭',
    description: "The Industrial Revolution (beginning c. 1760, UK) transformed economic structures more profoundly than any prior event. Factory production replaced artisanal craft; steam power multiplied human productive capacity; the factory system created the modern urban working class (proletariat). Thomas Malthus (An Essay on the Principle of Population, 1798) warned that population growth would always outpace food production — a pessimistic view that underpinned the 'dismal science' moniker. David Ricardo developed comparative advantage (each nation should specialise in what it produces most efficiently) and labour theory of value. John Stuart Mill synthesised and humanised classical economics. The first industrial banks (Bank of England, 1694) and stock exchanges (Amsterdam, London) financed industrial expansion. Railway speculation created the first major stock-market bubbles (Railway Mania, 1840s).",
    periods: [
      { name: 'Early Industrial Capitalism', start: 1760, end: 1820 },
      { name: 'Ricardo & Classical Political Economy', start: 1815, end: 1850 },
      { name: 'Railway Age & Industrial Finance', start: 1840, end: 1870 },
    ],
  },
  {
    id: 'first-globalisation',
    name: 'First Globalisation & Gold Standard',
    start: 1870, end: 1914,
    region: 'industrial',
    icon: '🔗',
    description: "The period 1870–1914 was the first era of true economic globalisation — in some measures more integrated than the 1980s–90s. The Gold Standard (Britain 1821, most major economies by 1879) fixed exchange rates, allowing international capital to flow freely. British capital financed railways across Argentina, India, Australia, and the United States. Transatlantic telegraph cables (1866) enabled near-instantaneous financial communication. Grain prices converged globally; mass emigration (50 million Europeans to the Americas, 1820–1914) was the largest voluntary migration in history. Corn Laws repeal (UK, 1846) established free trade as the British model. The First International trade union, the Second International, and anti-monopoly movements all reflected the social tensions of industrial capitalism.",
    periods: [
      { name: 'Gold Standard & Capital Flows', start: 1870, end: 1900 },
      { name: 'Edwardian Globalisation', start: 1900, end: 1914 },
    ],
  },
  {
    id: 'great-depression-keynes',
    name: '1929 Crash & Keynesian Revolution',
    start: 1929, end: 1945,
    region: 'finance',
    icon: '💥',
    description: "The Wall Street Crash (Black Tuesday, October 29, 1929) triggered the Great Depression — the worst economic catastrophe in modern history. US GDP fell by a third; unemployment reached 25%; a quarter of US banks failed. The Smoot-Hawley Tariff Act (1930) raised import duties, triggering retaliatory tariffs that collapsed world trade by 66%. John Maynard Keynes — the most influential economist of the 20th century — published The General Theory of Employment, Interest and Money (1936), arguing that private markets are inherently unstable and that government should use fiscal policy (public spending, tax cuts) to stabilise aggregate demand. Franklin Roosevelt's New Deal (1933–38) partially implemented Keynesian ideas. WWII public spending finally ended the Depression, validating Keynesian theory.",
    periods: [
      { name: 'Wall Street Crash', start: 1929, end: 1933 },
      { name: 'New Deal & Depression', start: 1933, end: 1939 },
      { name: 'Keynes\'s General Theory', start: 1936, end: 1945 },
    ],
  },
  {
    id: 'bretton-woods',
    name: 'Bretton Woods & Post-War Order',
    start: 1944, end: 1973,
    region: 'finance',
    icon: '🌐',
    description: "In July 1944, 730 delegates from 44 Allied nations met at Bretton Woods, New Hampshire, to design the post-war international monetary system. John Maynard Keynes (UK) and Harry Dexter White (US) debated the architecture. The resulting system: fixed exchange rates pegged to the US dollar (which was convertible to gold at $35/oz); the International Monetary Fund (IMF) to stabilise balance-of-payments crises; the World Bank to finance reconstruction and development. The Marshall Plan ($13.3 billion, 1948–52) rebuilt Western European economies and cemented US economic and political dominance. The GATT (1947) lowered trade barriers. The 'Bretton Woods' system produced 25 years of unprecedented growth — the 'Golden Age of Capitalism'. President Nixon 'closed the gold window' (August 15, 1971) — ending dollar convertibility — after France and others began demanding gold for their dollar holdings, triggering a fundamental shift to floating exchange rates.",
    periods: [
      { name: 'Bretton Woods Conference & Marshall Plan', start: 1944, end: 1955 },
      { name: 'Golden Age of Capitalism', start: 1955, end: 1971 },
      { name: 'Nixon Shock & End of Bretton Woods', start: 1971, end: 1973 },
    ],
  },
  {
    id: 'neoliberalism',
    name: 'Neoliberalism & Globalisation',
    start: 1973, end: 2008,
    region: 'global',
    icon: '📈',
    description: "The 1970s saw simultaneous inflation and unemployment ('stagflation'), which Keynesian economics seemed unable to explain. Milton Friedman and the Chicago School — monetarism (control money supply, not fiscal policy) and free markets — provided an alternative. Margaret Thatcher (UK, 1979) and Ronald Reagan (US, 1981) implemented market liberalisation: deregulation, privatisation, union-busting, tax cuts, and free trade. The 'Washington Consensus' spread these policies globally through IMF structural adjustment programmes. Financial deregulation — Glass-Steagall repeal (1999), derivatives explosion — financialised the global economy. The World Trade Organization (WTO, 1995), NAFTA (1994), and China's WTO accession (2001) deepened trade integration. Global poverty fell dramatically even as inequality within countries increased. China's integration into the world economy was the single most economically significant event of the era.",
    periods: [
      { name: 'Thatcher-Reagan Revolution', start: 1979, end: 1990 },
      { name: 'Washington Consensus & WTO', start: 1990, end: 2001 },
      { name: 'China Integration & Financialisation', start: 2001, end: 2008 },
    ],
  },
  {
    id: 'asian-tigers',
    name: 'Asian Economic Miracles',
    start: 1960, end: 2008,
    region: 'global',
    icon: '🌏',
    description: "The post-war decades produced extraordinary development successes in East Asia, challenging Western-dominated economic models. Japan rebuilt from wartime devastation to the world's second-largest economy by 1968, led by MITI-directed industrial policy (Toyota, Sony, Honda). The Four Asian Tigers — South Korea, Taiwan, Hong Kong, and Singapore — grew at 7–10% annually for decades, achieving developed-country incomes within a generation through export-oriented industrialisation, education investment, and state guidance. South Korea's chaebol (Samsung, Hyundai, LG) and Taiwan's technology sector became global players. Deng Xiaoping's 'Reform and Opening Up' policy (1978) launched China's transformation; averaging 10% growth for 35 years, China lifted 800 million people out of poverty — the largest poverty reduction in history. India's liberalisation (1991) triggered rapid growth in services and manufacturing.",
    periods: [
      { name: 'Japan\'s Post-War Miracle', start: 1945, end: 1990 },
      { name: 'Four Asian Tigers', start: 1960, end: 1997 },
      { name: 'China\'s Rise', start: 1978, end: 2008 },
    ],
  },
  {
    id: 'financial-crisis-2008',
    name: '2008 Global Financial Crisis',
    start: 2007, end: 2012,
    region: 'finance',
    icon: '💔',
    description: "The 2008 financial crisis — the worst since 1929 — was caused by an interconnected web of excessive risk-taking. US subprime mortgage lending (loans to borrowers who couldn't afford them), securitisation (packaging mortgages into complex financial instruments rated AAA by compromised rating agencies), leverage (banks borrowing 30:1 or more), and derivatives created systemic fragility. When US house prices fell (2006), losses cascaded through the global financial system. Lehman Brothers — the fourth-largest US investment bank — collapsed on September 15, 2008, triggering global panic. Governments worldwide committed $10+ trillion in bailouts and guarantees; the Federal Reserve and other central banks slashed interest rates to zero. The Eurozone sovereign debt crisis (2010–2015) — Greece, Ireland, Portugal, Spain, and Cyprus requiring bailouts — was partially caused by the 2008 crisis amplified by the euro's structural flaws.",
    periods: [
      { name: 'Subprime Crisis Begins', start: 2007, end: 2008 },
      { name: 'Lehman Collapse & Global Panic', start: 2008, end: 2009 },
      { name: 'Eurozone Debt Crisis', start: 2010, end: 2012 },
    ],
  },
  {
    id: 'digital-economy',
    name: 'Digital Economy & New Capitalism',
    start: 1994, end: 2025,
    region: 'global',
    icon: '💻',
    description: "The internet transformed commerce: Amazon (1994), eBay (1995), Google (1998) ushered in e-commerce, then the dot-com boom and bust (1995–2001). Mobile payments (M-Pesa in Kenya, 2007; Alipay, WeChat Pay in China) transformed banking in the developing world before reaching the West. The 'platform economy' — Airbnb, Uber, Amazon — extracted value from labour without the protections of traditional employment (the 'gig economy'). Bitcoin (Satoshi Nakamoto whitepaper, 2008; first transaction 2009) proposed decentralised digital money; the cryptocurrency boom and bust (2021 peak: $2.9 trillion market cap; NFT mania), and subsequent crashes, have not resolved whether blockchain finance is transformative or a speculative bubble. Post-2008 quantitative easing inflated asset prices, benefiting asset owners over workers. AI-driven productivity growth (from 2023) raises fundamental questions about the future of work.",
    periods: [
      { name: 'Dot-Com Era', start: 1994, end: 2001 },
      { name: 'Mobile & Platform Economy', start: 2007, end: 2018 },
      { name: 'Crypto, AI & New Challenges', start: 2018, end: 2025 },
    ],
  },
];
