// Years are negative for BCE, positive for CE
// We use a logarithmic-ish scale for display since events span 13.8 billion years

export const eras = [
  { name: 'Cosmic', color: '#6B21A8', start: -13_800_000_000, end: -4_600_000_000 },
  { name: 'Earth Formation', color: '#1E40AF', start: -4_600_000_000, end: -3_500_000_000 },
  { name: 'Early Life', color: '#065F46', start: -3_500_000_000, end: -252_000_000 },
  { name: 'Age of Dinosaurs', color: '#166534', start: -252_000_000, end: -66_000_000 },
  { name: 'Age of Mammals', color: '#92400E', start: -66_000_000, end: -300_000 },
  { name: 'Human Prehistory', color: '#9A3412', start: -300_000, end: -3_000 },
  { name: 'Ancient Civilisations', color: '#B45309', start: -3_000, end: 476 },
  { name: 'Medieval', color: '#6B21A8', start: 476, end: 1492 },
  { name: 'Early Modern', color: '#BE185D', start: 1492, end: 1800 },
  { name: 'Modern', color: '#DC2626', start: 1800, end: 2030 },
];

export const events = [
  {
    year: -13_800_000_000,
    title: 'The Big Bang',
    description: 'The universe begins from an infinitely dense singularity, expanding rapidly in the first fractions of a second. All matter, energy, space, and time originate from this moment.',
    era: 'Cosmic',
    icon: '💥',
  },
  {
    year: -13_600_000_000,
    title: 'First Stars Ignite',
    description: 'The first generation of stars form from clouds of hydrogen and helium, lighting up the dark universe for the first time and beginning to forge heavier elements.',
    era: 'Cosmic',
    icon: '⭐',
  },
  {
    year: -13_200_000_000,
    title: 'The Milky Way Forms',
    description: 'Our home galaxy begins to take shape as smaller proto-galaxies merge together, eventually forming the familiar spiral structure we know today.',
    era: 'Cosmic',
    icon: '🌌',
  },
  {
    year: -4_600_000_000,
    title: 'Our Solar System Forms',
    description: 'A vast cloud of gas and dust collapses under gravity, forming the Sun at its centre and the planets — including Earth — from the surrounding disc of material.',
    era: 'Earth Formation',
    icon: '☀️',
  },
  {
    year: -4_500_000_000,
    title: 'The Moon Forms',
    description: 'A Mars-sized body called Theia collides with the young Earth. The debris from this colossal impact coalesces to form our Moon.',
    era: 'Earth Formation',
    icon: '🌙',
  },
  {
    year: -3_800_000_000,
    title: 'First Life on Earth',
    description: 'The earliest known life appears — simple single-celled organisms (prokaryotes) emerge in Earth\'s primordial oceans, marking the beginning of biology.',
    era: 'Early Life',
    icon: '🦠',
  },
  {
    year: -2_400_000_000,
    title: 'The Great Oxygenation Event',
    description: 'Cyanobacteria begin producing oxygen through photosynthesis on a massive scale, transforming Earth\'s atmosphere and enabling the eventual rise of complex life.',
    era: 'Early Life',
    icon: '🫧',
  },
  {
    year: -540_000_000,
    title: 'Cambrian Explosion',
    description: 'An extraordinary burst of evolution produces most major animal groups in a geologically short period. Complex eyes, shells, and predators appear for the first time.',
    era: 'Early Life',
    icon: '🐚',
  },
  {
    year: -252_000_000,
    title: 'The Great Dying',
    description: 'The Permian-Triassic extinction event wipes out roughly 96% of marine species and 70% of terrestrial vertebrates — the most severe extinction in Earth\'s history.',
    era: 'Age of Dinosaurs',
    icon: '☠️',
  },
  {
    year: -230_000_000,
    title: 'First Dinosaurs Appear',
    description: 'The earliest dinosaurs evolve during the Triassic period, initially small and bipedal. They will go on to dominate Earth for over 160 million years.',
    era: 'Age of Dinosaurs',
    icon: '🦕',
  },
  {
    year: -150_000_000,
    title: 'Jurassic Peak',
    description: 'Dinosaurs reach their zenith of diversity. Giant sauropods roam the land, pterosaurs fill the skies, and the first birds begin to evolve from theropod dinosaurs.',
    era: 'Age of Dinosaurs',
    icon: '🦖',
  },
  {
    year: -66_000_000,
    title: 'Asteroid Impact — Dinosaurs Extinct',
    description: 'A 10km-wide asteroid strikes the Yucatán Peninsula, triggering global catastrophe. The non-avian dinosaurs are wiped out, opening the door for mammals to rise.',
    era: 'Age of Mammals',
    icon: '☄️',
  },
  {
    year: -55_000_000,
    title: 'First Primates',
    description: 'Early primates appear in tropical forests, small nocturnal creatures with grasping hands and forward-facing eyes — the distant ancestors of humans.',
    era: 'Age of Mammals',
    icon: '🐒',
  },
  {
    year: -6_000_000,
    title: 'Human–Ape Split',
    description: 'The lineages leading to humans and chimpanzees diverge. Our ancestors begin walking upright on the African savanna.',
    era: 'Age of Mammals',
    icon: '🧬',
  },
  {
    year: -300_000,
    title: 'Homo Sapiens Emerge',
    description: 'Anatomically modern humans first appear in Africa. With larger brains and sophisticated tool use, they will eventually spread across the entire globe.',
    era: 'Human Prehistory',
    icon: '🧑',
  },
  {
    year: -70_000,
    title: 'Cognitive Revolution',
    description: 'A leap in human cognitive ability enables complex language, abstract thinking, and social cooperation on an unprecedented scale.',
    era: 'Human Prehistory',
    icon: '🧠',
  },
  {
    year: -12_000,
    title: 'Agricultural Revolution',
    description: 'Humans begin farming crops and domesticating animals in the Fertile Crescent, transitioning from nomadic hunter-gatherers to settled communities.',
    era: 'Human Prehistory',
    icon: '🌾',
  },
  {
    year: -3_100,
    title: 'Ancient Egypt Unified',
    description: 'Upper and Lower Egypt are united under the first pharaoh, beginning one of history\'s longest-lasting and most influential civilisations along the Nile.',
    era: 'Ancient Civilisations',
    icon: '🏛️',
  },
  {
    year: -2_560,
    title: 'Great Pyramid of Giza Built',
    description: 'The Great Pyramid is completed for Pharaoh Khufu — a marvel of ancient engineering that remains one of the Seven Wonders of the Ancient World.',
    era: 'Ancient Civilisations',
    icon: '🔺',
  },
  {
    year: -1_750,
    title: 'Code of Hammurabi',
    description: 'One of the earliest written legal codes is established in Babylon, laying foundational principles of justice and governance.',
    era: 'Ancient Civilisations',
    icon: '⚖️',
  },
  {
    year: -508,
    title: 'Athenian Democracy Founded',
    description: 'Athens establishes a radical new form of government where citizens directly participate in political decisions — the birthplace of democracy.',
    era: 'Ancient Civilisations',
    icon: '🗳️',
  },
  {
    year: -27,
    title: 'Roman Empire Begins',
    description: 'Augustus becomes the first Roman Emperor, transforming the Republic into an Empire that will shape Western law, language, engineering, and culture for centuries.',
    era: 'Ancient Civilisations',
    icon: '🏛️',
  },
  {
    year: 330,
    title: 'Constantinople Founded',
    description: 'Emperor Constantine refounds Byzantium as Constantinople, establishing the eastern capital that will endure as the seat of the Byzantine Empire for over a thousand years.',
    era: 'Ancient Civilisations',
    icon: '⛪',
  },
  {
    year: 476,
    title: 'Fall of the Western Roman Empire',
    description: 'The last Western Roman Emperor is deposed, traditionally marking the end of antiquity and the beginning of the Middle Ages in Europe.',
    era: 'Medieval',
    icon: '⚔️',
  },
  {
    year: 622,
    title: 'Rise of Islam',
    description: 'The Prophet Muhammad\'s migration to Medina marks the start of the Islamic calendar. Islam will rapidly expand to create a vast civilisation spanning three continents.',
    era: 'Medieval',
    icon: '☪️',
  },
  {
    year: 1054,
    title: 'Great Schism',
    description: 'Christianity formally splits into the Roman Catholic Church in the West and the Eastern Orthodox Church, a division that persists to this day.',
    era: 'Medieval',
    icon: '✝️',
  },
  {
    year: 1066,
    title: 'Norman Conquest of England',
    description: 'William the Conqueror defeats King Harold at the Battle of Hastings, reshaping English language, culture, and governance.',
    era: 'Medieval',
    icon: '🏰',
  },
  {
    year: 1347,
    title: 'The Black Death',
    description: 'The bubonic plague sweeps across Europe, killing roughly a third of the population and fundamentally altering European society, economy, and culture.',
    era: 'Medieval',
    icon: '🐀',
  },
  {
    year: 1453,
    title: 'Fall of Constantinople — Ottoman Empire Rises',
    description: 'The Ottoman Turks capture Constantinople, ending the Byzantine Empire. The Ottomans build a vast empire spanning Southeast Europe, Western Asia, and North Africa.',
    era: 'Medieval',
    icon: '🌙',
  },
  {
    year: 1492,
    title: 'Columbus Reaches the Americas',
    description: 'Christopher Columbus\'s voyage across the Atlantic initiates sustained European contact with the Americas, beginning an era of exploration, colonisation, and profound global change.',
    era: 'Early Modern',
    icon: '⛵',
  },
  {
    year: 1501,
    title: 'Transatlantic Slave Trade Begins',
    description: 'The first enslaved Africans are transported across the Atlantic to the Americas. Over the next 350 years, an estimated 12.5 million people will be forcibly transported in one of history\'s greatest atrocities.',
    era: 'Early Modern',
    icon: '⛓️',
  },
  {
    year: 1517,
    title: 'Protestant Reformation',
    description: 'Martin Luther publishes his 95 Theses, challenging the Catholic Church and sparking a religious revolution that fractures Western Christianity.',
    era: 'Early Modern',
    icon: '📜',
  },
  {
    year: 1687,
    title: 'Newton\'s Principia Published',
    description: 'Isaac Newton publishes his laws of motion and universal gravitation, laying the foundation of classical physics and transforming our understanding of the natural world.',
    era: 'Early Modern',
    icon: '🍎',
  },
  {
    year: 1760,
    title: 'Industrial Revolution Begins',
    description: 'New manufacturing processes transform Britain and then the world, shifting from agrarian economies to industrial powerhouses powered by steam and coal.',
    era: 'Early Modern',
    icon: '🏭',
  },
  {
    year: 1776,
    title: 'United States Declares Independence',
    description: 'The thirteen American colonies declare independence from Britain, establishing a new nation founded on Enlightenment principles of liberty and self-governance.',
    era: 'Early Modern',
    icon: '🗽',
  },
  {
    year: 1789,
    title: 'French Revolution',
    description: 'The storming of the Bastille ignites a revolution that overthrows the monarchy, reshaping European politics and inspiring democratic movements worldwide.',
    era: 'Early Modern',
    icon: '🇫🇷',
  },
  {
    year: 1807,
    title: 'Britain Abolishes the Slave Trade',
    description: 'The British Parliament passes the Abolition of the Slave Trade Act, beginning the long process of ending slavery across the British Empire.',
    era: 'Modern',
    icon: '🔗',
  },
  {
    year: 1865,
    title: 'End of American Civil War & Abolition of Slavery',
    description: 'The 13th Amendment abolishes slavery throughout the United States following the bloodiest conflict in American history.',
    era: 'Modern',
    icon: '🕊️',
  },
  {
    year: 1914,
    title: 'World War I Begins',
    description: 'The assassination of Archduke Franz Ferdinand triggers a devastating global conflict. Over 20 million die in a war that redraws the map of Europe and the Middle East.',
    era: 'Modern',
    icon: '⚔️',
  },
  {
    year: 1939,
    title: 'World War II Begins',
    description: 'Nazi Germany invades Poland, starting the deadliest conflict in human history. Over 70 million people will die, including 6 million in the Holocaust.',
    era: 'Modern',
    icon: '💣',
  },
  {
    year: 1945,
    title: 'Atomic Bombs & End of WWII',
    description: 'The United States drops atomic bombs on Hiroshima and Nagasaki, ushering in the nuclear age and ending the Second World War.',
    era: 'Modern',
    icon: '☢️',
  },
  {
    year: 1969,
    title: 'Moon Landing',
    description: 'Neil Armstrong and Buzz Aldrin become the first humans to walk on the Moon, a defining achievement of the Space Age and human ingenuity.',
    era: 'Modern',
    icon: '🌕',
  },
  {
    year: 1983,
    title: 'The Internet is Born',
    description: 'ARPANET adopts TCP/IP, creating the foundational protocol of the modern Internet and beginning the most transformative communications revolution in history.',
    era: 'Modern',
    icon: '🌐',
  },
  {
    year: 1989,
    title: 'Fall of the Berlin Wall',
    description: 'The Berlin Wall falls, symbolising the end of the Cold War and the beginning of German reunification and a new era in global politics.',
    era: 'Modern',
    icon: '🧱',
  },
  {
    year: 2012,
    title: 'Deep Learning Revolution',
    description: 'AlexNet wins the ImageNet challenge by a massive margin, demonstrating the power of deep neural networks and igniting the modern AI revolution.',
    era: 'Modern',
    icon: '🤖',
  },
  {
    year: 2022,
    title: 'The Age of AI',
    description: 'Large language models like ChatGPT bring AI into the mainstream, demonstrating human-level language understanding and transforming how we interact with technology.',
    era: 'Modern',
    icon: '🧠',
  },
];
