// Years are negative for BCE, positive for CE
// We use a logarithmic-ish scale for display since events span 13.8 billion years

export const eras = [
  { name: 'Cosmic', color: '#6B21A8', start: -13_800_000_000, end: -4_600_000_000 },
  { name: 'Earth Formation', color: '#1E40AF', start: -4_600_000_000, end: -3_500_000_000 },
  { name: 'Early Life', color: '#065F46', start: -3_500_000_000, end: -252_000_000 },
  { name: 'Age of Dinosaurs', color: '#166534', start: -252_000_000, end: -66_000_000 },
  { name: 'Age of Mammals', color: '#92400E', start: -66_000_000, end: -300_000 },
  { name: 'Human Prehistory', color: '#9A3412', start: -300_000, end: -3_000 },
  { name: 'Ancient Civilisations', color: '#B45309', start: -3_000, end: 476 },
  { name: 'Medieval', color: '#6B21A8', start: 476, end: 1492 },
  { name: 'Early Modern', color: '#BE185D', start: 1492, end: 1800 },
  { name: 'Modern', color: '#DC2626', start: 1800, end: 2030 },
];

export const events = [
  {
    year: -13_800_000_000,
    title: 'The Big Bang',
    description: 'The universe begins from an infinitely dense singularity, expanding rapidly in the first fractions of a second. All matter, energy, space, and time originate from this moment.',
    era: 'Cosmic',
    icon: '💥',
  },
  {
    year: -13_799_620_000,
    title: 'The First Atoms Form',
    description: 'Around 380,000 years after the Big Bang, the universe cools enough for electrons to bind to nuclei, forming the first atoms. Light streams freely for the first time — the origin of the Cosmic Microwave Background.',
    era: 'Cosmic',
    icon: '⚛️',
  },
  {
    year: -13_600_000_000,
    title: 'First Stars Ignite',
    description: 'The first generation of stars form from clouds of hydrogen and helium, lighting up the dark universe for the first time and beginning to forge heavier elements.',
    era: 'Cosmic',
    icon: '⭐',
  },
  {
    year: -13_200_000_000,
    title: 'The Milky Way Forms',
    description: 'Our home galaxy begins to take shape as smaller proto-galaxies merge together, eventually forming the familiar spiral structure we know today.',
    era: 'Cosmic',
    icon: '🌌',
  },
  {
    year: -10_000_000_000,
    title: 'The Cosmic Web Takes Shape',
    description: 'Dark matter and gravity sculpt the universe into a vast cosmic web of galaxy clusters, filaments, and enormous voids spanning hundreds of millions of light-years.',
    era: 'Cosmic',
    icon: '🕸️',
  },
  {
    year: -4_600_000_000,
    title: 'Our Solar System Forms',
    description: 'A vast cloud of gas and dust collapses under gravity, forming the Sun at its centre and the planets — including Earth — from the surrounding disc of material.',
    era: 'Earth Formation',
    icon: '☀️',
  },
  {
    year: -4_500_000_000,
    title: 'The Moon Forms',
    description: 'A Mars-sized body called Theia collides with the young Earth. The debris from this colossal impact coalesces to form our Moon.',
    era: 'Earth Formation',
    icon: '🌙',
  },
  {
    year: -3_800_000_000,
    title: 'First Life on Earth',
    description: 'The earliest known life appears — simple single-celled organisms (prokaryotes) emerge in Earth\'s primordial oceans, marking the beginning of biology.',
    era: 'Early Life',
    icon: '🦠',
  },
  {
    year: -2_400_000_000,
    title: 'The Great Oxygenation Event',
    description: 'Cyanobacteria begin producing oxygen through photosynthesis on a massive scale, transforming Earth\'s atmosphere and enabling the eventual rise of complex life.',
    era: 'Early Life',
    icon: '🫧',
  },
  {
    year: -2_100_000_000,
    title: 'First Complex Cells',
    description: 'Eukaryotic cells with a true nucleus emerge, probably through one cell engulfing another in a process called endosymbiosis. This leap in cellular complexity paves the way for all multicellular life.',
    era: 'Early Life',
    icon: '🔬',
  },
  {
    year: -635_000_000,
    title: 'Ediacaran Fauna Appear',
    description: 'The first large, complex organisms appear in the oceans — bizarre soft-bodied creatures unlike anything alive today, representing life\'s first experiment with large body plans.',
    era: 'Early Life',
    icon: '🪸',
  },
  {
    year: -540_000_000,
    title: 'Cambrian Explosion',
    description: 'An extraordinary burst of evolution produces most major animal groups in a geologically short period. Complex eyes, shells, and predators appear for the first time.',
    era: 'Early Life',
    icon: '🐚',
  },
  {
    year: -470_000_000,
    title: 'Plants Colonise the Land',
    description: 'The first plants move from water to land, beginning the transformation of barren rock into green landscapes. Soils form, the atmosphere stabilises, and terrestrial food chains become possible.',
    era: 'Early Life',
    icon: '🌿',
  },
  {
    year: -252_000_000,
    title: 'The Great Dying',
    description: 'The Permian-Triassic extinction event wipes out roughly 96% of marine species and 70% of terrestrial vertebrates — the most severe extinction in Earth\'s history.',
    era: 'Age of Dinosaurs',
    icon: '☠️',
  },
  {
    year: -230_000_000,
    title: 'First Dinosaurs Appear',
    description: 'The earliest dinosaurs evolve during the Triassic period, initially small and bipedal. They will go on to dominate Earth for over 160 million years.',
    era: 'Age of Dinosaurs',
    icon: '🦕',
  },
  {
    year: -200_000_000,
    title: 'Pangaea Begins to Break Apart',
    description: 'The supercontinent Pangaea begins rifting into separate landmasses that will eventually become today\'s continents, reshaping ocean currents, climate, and the evolution of isolated species.',
    era: 'Age of Dinosaurs',
    icon: '🗺️',
  },
  {
    year: -150_000_000,
    title: 'Jurassic Peak',
    description: 'Dinosaurs reach their zenith of diversity. Giant sauropods roam the land, pterosaurs fill the skies, and the first birds begin to evolve from theropod dinosaurs.',
    era: 'Age of Dinosaurs',
    icon: '🦖',
  },
  {
    year: -130_000_000,
    title: 'First Flowering Plants',
    description: 'Angiosperms appear and begin a takeover that will transform terrestrial ecosystems. Their co-evolution with insect pollinators creates the explosive diversity of both groups.',
    era: 'Age of Dinosaurs',
    icon: '🌸',
  },
  {
    year: -66_000_000,
    title: 'Asteroid Impact — Dinosaurs Extinct',
    description: 'A 10km-wide asteroid strikes the Yucatán Peninsula, triggering global catastrophe. The non-avian dinosaurs are wiped out, opening the door for mammals to rise.',
    era: 'Age of Mammals',
    icon: '☄️',
  },
  {
    year: -55_000_000,
    title: 'First Primates',
    description: 'Early primates appear in tropical forests, small nocturnal creatures with grasping hands and forward-facing eyes — the distant ancestors of humans.',
    era: 'Age of Mammals',
    icon: '🐒',
  },
  {
    year: -6_000_000,
    title: 'Human–Ape Split',
    description: 'The lineages leading to humans and chimpanzees diverge. Our ancestors begin walking upright on the African savanna.',
    era: 'Age of Mammals',
    icon: '🧬',
  },
  {
    year: -2_500_000,
    title: 'First Stone Tools',
    description: 'Homo habilis begins deliberately knapping stone tools in East Africa, marking the dawn of technology and a cognitive leap that separates the hominin lineage from other apes.',
    era: 'Age of Mammals',
    icon: '🪨',
  },
  {
    year: -800_000,
    title: 'Mastery of Fire',
    description: 'Homo erectus gains control of fire, enabling cooking, warmth, protection from predators, and social gathering — arguably the most transformative technology before agriculture.',
    era: 'Age of Mammals',
    icon: '🔥',
  },
  {
    year: -300_000,
    title: 'Homo Sapiens Emerge',
    description: 'Anatomically modern humans first appear in Africa. With larger brains and sophisticated tool use, they will eventually spread across the entire globe.',
    era: 'Human Prehistory',
    icon: '🧑',
  },
  {
    year: -100_000,
    title: 'Humans Leave Africa',
    description: 'Anatomically modern humans begin migrating out of Africa, eventually reaching every continent and adapting to environments from Arctic tundra to tropical rainforests.',
    era: 'Human Prehistory',
    icon: '🌍',
  },
  {
    year: -70_000,
    title: 'Cognitive Revolution',
    description: 'A leap in human cognitive ability enables complex language, abstract thinking, and social cooperation on an unprecedented scale.',
    era: 'Human Prehistory',
    icon: '🧠',
  },
  {
    year: -40_000,
    title: 'Cave Paintings',
    description: 'Early humans create stunning artwork on cave walls across Europe and Southeast Asia, representing the oldest known examples of figurative art and symbolic expression.',
    era: 'Human Prehistory',
    icon: '🎨',
  },
  {
    year: -30_000,
    title: 'Extinction of Neanderthals',
    description: 'The last Neanderthals disappear from Europe, leaving Homo sapiens as the sole surviving human species. Their DNA lives on in modern non-African populations.',
    era: 'Human Prehistory',
    icon: '💀',
  },
  {
    year: -12_000,
    title: 'Agricultural Revolution',
    description: 'Humans begin farming crops and domesticating animals in the Fertile Crescent, transitioning from nomadic hunter-gatherers to settled communities.',
    era: 'Human Prehistory',
    icon: '🌾',
  },
  {
    year: -8_000,
    title: 'First Cities Emerge',
    description: 'Settlements like Çatalhöyük and Jericho grow into some of the world\'s first proto-urban centres, concentrating thousands of people and laying the groundwork for civilisation.',
    era: 'Human Prehistory',
    icon: '🏘️',
  },
  {
    year: -5_500,
    title: 'Invention of the Wheel',
    description: 'The wheel is invented in Mesopotamia, initially used for pottery before being adapted for transport. It becomes one of the most transformative mechanical innovations in human history.',
    era: 'Human Prehistory',
    icon: '⚙️',
  },
  {
    year: -3_500,
    title: 'Bronze Age Begins',
    description: 'The alloying of copper and tin produces bronze, a metal hard enough for effective weapons and tools. The Bronze Age transforms warfare, trade, and social hierarchies across Eurasia.',
    era: 'Human Prehistory',
    icon: '🔱',
  },
  {
    year: -3_300,
    title: 'Writing Invented — Cuneiform',
    description: 'The Sumerians develop cuneiform, one of the earliest writing systems, pressing wedge-shaped marks into clay tablets. Writing enables record-keeping, law, literature, and the transmission of knowledge across generations.',
    era: 'Ancient Civilisations',
    icon: '📝',
  },
  {
    year: -3_100,
    title: 'Ancient Egypt Unified',
    description: 'Upper and Lower Egypt are united under the first pharaoh, beginning one of history\'s longest-lasting and most influential civilisations along the Nile.',
    era: 'Ancient Civilisations',
    icon: '🏛️',
  },
  {
    year: -2_600,
    title: 'Indus Valley Civilisation Flourishes',
    description: 'One of the world\'s earliest urban civilisations thrives along the Indus River with advanced drainage systems, standardised weights, and planned cities like Mohenjo-daro and Harappa.',
    era: 'Ancient Civilisations',
    icon: '🏙️',
  },
  {
    year: -2_560,
    title: 'Great Pyramid of Giza Built',
    description: 'The Great Pyramid is completed for Pharaoh Khufu — a marvel of ancient engineering that remains one of the Seven Wonders of the Ancient World.',
    era: 'Ancient Civilisations',
    icon: '🔺',
  },
  {
    year: -1_750,
    title: 'Code of Hammurabi',
    description: 'One of the earliest written legal codes is established in Babylon, laying foundational principles of justice and governance.',
    era: 'Ancient Civilisations',
    icon: '⚖️',
  },
  {
    year: -1_500,
    title: 'Vedas Composed — Hinduism Emerges',
    description: 'The Rigveda and other sacred texts are composed in ancient India, establishing the foundations of Hinduism — the world\'s oldest major religion still widely practised today.',
    era: 'Ancient Civilisations',
    icon: '🕉️',
  },
  {
    year: -1_200,
    title: 'The Iron Age Begins',
    description: 'Iron smelting technology spreads across the Near East and Mediterranean, replacing bronze as the dominant metal. Stronger and more abundant, iron transforms agriculture, warfare, and toolmaking.',
    era: 'Ancient Civilisations',
    icon: '🗡️',
  },
  {
    year: -600,
    title: 'Thales & the Birth of Philosophy',
    description: 'Thales of Miletus seeks natural explanations for the world rather than mythological ones, pioneering rational inquiry and earning his place as the first Western philosopher.',
    era: 'Ancient Civilisations',
    icon: '💭',
  },
  {
    year: -563,
    title: 'Birth of the Buddha',
    description: 'Siddhartha Gautama is born in present-day Nepal. His teachings on suffering, impermanence, and the path to enlightenment will found one of the world\'s great religions.',
    era: 'Ancient Civilisations',
    icon: '☸️',
  },
  {
    year: -508,
    title: 'Athenian Democracy Founded',
    description: 'Athens establishes a radical new form of government where citizens directly participate in political decisions — the birthplace of democracy.',
    era: 'Ancient Civilisations',
    icon: '🗳️',
  },
  {
    year: -334,
    title: 'Alexander the Great\'s Conquests',
    description: 'Alexander of Macedon begins a campaign that will conquer from Greece to India in just thirteen years, spreading Greek culture across the ancient world and creating the Hellenistic Age.',
    era: 'Ancient Civilisations',
    icon: '⚔️',
  },
  {
    year: -300,
    title: 'Euclid\'s Elements',
    description: 'The Greek mathematician Euclid compiles his Elements, a systematic treatise on geometry and number theory that becomes the most influential mathematics textbook in history.',
    era: 'Ancient Civilisations',
    icon: '📐',
  },
  {
    year: -268,
    title: 'Ashoka Embraces Non-Violence',
    description: 'After the devastating Kalinga War, the Maurya Emperor Ashoka converts to Buddhism and promotes non-violence and tolerance across the Indian subcontinent through his famous rock edicts.',
    era: 'Ancient Civilisations',
    icon: '☮️',
  },
  {
    year: -250,
    title: 'Archimedes\' Discoveries',
    description: 'Archimedes of Syracuse makes groundbreaking advances in mathematics, physics, and engineering, discovering the principles of buoyancy, the lever, and methods for calculating areas and volumes.',
    era: 'Ancient Civilisations',
    icon: '🔬',
  },
  {
    year: -221,
    title: 'Qin Unifies China',
    description: 'Qin Shi Huang conquers the warring states and becomes the first Emperor of a unified China, standardising weights, measures, currency, and writing across the realm.',
    era: 'Ancient Civilisations',
    icon: '🐉',
  },
  {
    year: -44,
    title: 'Julius Caesar Assassinated',
    description: 'Roman dictator Julius Caesar is stabbed to death by senators on the Ides of March, plunging Rome into civil war and ultimately ending the Republic.',
    era: 'Ancient Civilisations',
    icon: '🗡️',
  },
  {
    year: -27,
    title: 'Roman Empire Begins',
    description: 'Augustus becomes the first Roman Emperor, transforming the Republic into an Empire that will shape Western law, language, engineering, and culture for centuries.',
    era: 'Ancient Civilisations',
    icon: '🏛️',
  },
  {
    year: -4,
    title: 'Birth of Jesus of Nazareth',
    description: 'Jesus is born in Roman-occupied Judea. His life and teachings will become the foundation of Christianity, eventually the world\'s largest religion, reshaping history and culture across the globe.',
    era: 'Ancient Civilisations',
    icon: '✝️',
  },
  {
    year: 105,
    title: 'Paper Invented in China',
    description: 'Cai Lun of the Han Dynasty refines the papermaking process using bark, hemp, and rags, creating an affordable writing material that revolutionises communication and record-keeping worldwide.',
    era: 'Ancient Civilisations',
    icon: '📄',
  },
  {
    year: 200,
    title: 'Silk Road Trade Peaks',
    description: 'Overland trade routes connecting China to Rome reach their height, exchanging not just silk, spices, and gold, but ideas, religions, and technologies across an entire continent.',
    era: 'Ancient Civilisations',
    icon: '🐪',
  },
  {
    year: 330,
    title: 'Constantinople Founded',
    description: 'Emperor Constantine refounds Byzantium as Constantinople, establishing the eastern capital that will endure as the seat of the Byzantine Empire for over a thousand years.',
    era: 'Ancient Civilisations',
    icon: '⛪',
  },
  {
    year: 476,
    title: 'Fall of the Western Roman Empire',
    description: 'The last Western Roman Emperor is deposed, traditionally marking the end of antiquity and the beginning of the Middle Ages in Europe.',
    era: 'Medieval',
    icon: '⚔️',
  },
  {
    year: 622,
    title: 'Rise of Islam',
    description: 'The Prophet Muhammad\'s migration to Medina marks the start of the Islamic calendar. Islam will rapidly expand to create a vast civilisation spanning three continents.',
    era: 'Medieval',
    icon: '☪️',
  },
  {
    year: 750,
    title: 'Islamic Golden Age Begins',
    description: 'Under the Abbasid Caliphate, Baghdad becomes the intellectual capital of the world. Scholars preserve Greek knowledge and pioneer algebra, optics, medicine, and astronomy.',
    era: 'Medieval',
    icon: '📚',
  },
  {
    year: 800,
    title: 'Charlemagne Crowned Emperor',
    description: 'Pope Leo III crowns Charlemagne as Emperor of the Romans on Christmas Day, reviving the concept of a unified Western European empire and sparking a cultural renaissance.',
    era: 'Medieval',
    icon: '👑',
  },
  {
    year: 850,
    title: 'Gunpowder Invented in China',
    description: 'Chinese alchemists accidentally discover gunpowder while searching for an elixir of immortality. This explosive mixture will eventually transform warfare and reshape the balance of power worldwide.',
    era: 'Medieval',
    icon: '💣',
  },
  {
    year: 1054,
    title: 'Great Schism',
    description: 'Christianity formally splits into the Roman Catholic Church in the West and the Eastern Orthodox Church, a division that persists to this day.',
    era: 'Medieval',
    icon: '✝️',
  },
  {
    year: 1066,
    title: 'Norman Conquest of England',
    description: 'William the Conqueror defeats King Harold at the Battle of Hastings, reshaping English language, culture, and governance.',
    era: 'Medieval',
    icon: '🏰',
  },
  {
    year: 1096,
    title: 'The First Crusade',
    description: 'European armies march to the Holy Land in the first of many Crusades, igniting centuries of conflict that reshape relations between Christianity and Islam and transform trade across the Mediterranean.',
    era: 'Medieval',
    icon: '⚔️',
  },
  {
    year: 1100,
    title: 'Magnetic Compass in Navigation',
    description: 'The magnetic compass comes into widespread use for maritime navigation, first in China and soon across the Islamic world and Europe, enabling the great age of oceanic exploration.',
    era: 'Medieval',
    icon: '🧭',
  },
  {
    year: 1206,
    title: 'Delhi Sultanate Founded',
    description: 'Islamic rule is established in northern India, beginning centuries of cultural exchange and the creation of Indo-Islamic art, architecture, and governance.',
    era: 'Medieval',
    icon: '🕌',
  },
  {
    year: 1215,
    title: 'Magna Carta Sealed',
    description: 'English barons force King John to accept the Magna Carta, establishing the principle that even monarchs are subject to the law and laying groundwork for constitutional governance.',
    era: 'Medieval',
    icon: '📜',
  },
  {
    year: 1227,
    title: 'Mongol Empire at Its Peak',
    description: 'Genghis Khan dies having forged the largest contiguous land empire in history, stretching from China to Eastern Europe and reshaping trade, culture, and demographics across Eurasia.',
    era: 'Medieval',
    icon: '🏇',
  },
  {
    year: 1325,
    title: 'Mansa Musa\'s Pilgrimage to Mecca',
    description: 'The ruler of the Mali Empire makes his legendary hajj, distributing so much gold along the way that he destabilises economies. His journey puts West Africa on European maps.',
    era: 'Medieval',
    icon: '👑',
  },
  {
    year: 1347,
    title: 'The Black Death',
    description: 'The bubonic plague sweeps across Europe, killing roughly a third of the population and fundamentally altering European society, economy, and culture.',
    era: 'Medieval',
    icon: '🐀',
  },
  {
    year: 1405,
    title: 'Zheng He\'s Treasure Voyages',
    description: 'Chinese Admiral Zheng He leads massive fleets across the Indian Ocean to Southeast Asia, India, Arabia, and East Africa, demonstrating Ming China\'s naval power decades before European exploration.',
    era: 'Medieval',
    icon: '🚢',
  },
  {
    year: 1440,
    title: 'Gutenberg\'s Printing Press',
    description: 'Johannes Gutenberg develops the movable-type printing press in Mainz, Germany, making books affordable and sparking an information revolution that fuels the Renaissance and Reformation.',
    era: 'Medieval',
    icon: '🖨️',
  },
  {
    year: 1453,
    title: 'Fall of Constantinople — Ottoman Empire Rises',
    description: 'The Ottoman Turks capture Constantinople, ending the Byzantine Empire. The Ottomans build a vast empire spanning Southeast Europe, Western Asia, and North Africa.',
    era: 'Medieval',
    icon: '🌙',
  },
  {
    year: 1492,
    title: 'Columbus Reaches the Americas',
    description: 'Christopher Columbus\'s voyage across the Atlantic initiates sustained European contact with the Americas, beginning an era of exploration, colonisation, and profound global change.',
    era: 'Early Modern',
    icon: '⛵',
  },
  {
    year: 1498,
    title: 'Vasco da Gama Reaches India',
    description: 'The Portuguese navigator rounds Africa and reaches Calicut, opening a direct sea route between Europe and Asia that transforms global trade and begins the European colonial era in Asia.',
    era: 'Early Modern',
    icon: '🗺️',
  },
  {
    year: 1501,
    title: 'Transatlantic Slave Trade Begins',
    description: 'The first enslaved Africans are transported across the Atlantic to the Americas. Over the next 350 years, an estimated 12.5 million people will be forcibly transported in one of history\'s greatest atrocities.',
    era: 'Early Modern',
    icon: '⛓️',
  },
  {
    year: 1517,
    title: 'Protestant Reformation',
    description: 'Martin Luther publishes his 95 Theses, challenging the Catholic Church and sparking a religious revolution that fractures Western Christianity.',
    era: 'Early Modern',
    icon: '📜',
  },
  {
    year: 1519,
    title: 'Magellan\'s Expedition Circumnavigates the Globe',
    description: 'Ferdinand Magellan\'s expedition departs Spain and completes the first circumnavigation of the Earth, proving the planet\'s oceans are connected and revealing the true scale of the globe.',
    era: 'Early Modern',
    icon: '🌐',
  },
  {
    year: 1543,
    title: 'Copernicus\' Heliocentric Model',
    description: 'Nicolaus Copernicus publishes De revolutionibus, proposing that the Earth and planets orbit the Sun rather than the other way around, fundamentally challenging humanity\'s view of its place in the cosmos.',
    era: 'Early Modern',
    icon: '🌍',
  },
  {
    year: 1600,
    title: 'East India Company Founded',
    description: 'The English East India Company receives its royal charter, beginning a new era of corporate colonialism that will eventually control much of India and reshape global trade for centuries.',
    era: 'Early Modern',
    icon: '🏴',
  },
  {
    year: 1610,
    title: 'Galileo\'s Telescope Observations',
    description: 'Galileo Galilei turns his improved telescope to the night sky, discovering Jupiter\'s moons, lunar craters, and the phases of Venus — providing powerful evidence for the heliocentric model.',
    era: 'Early Modern',
    icon: '🔭',
  },
  {
    year: 1648,
    title: 'Peace of Westphalia',
    description: 'The treaties ending the Thirty Years\' War establish the principle of state sovereignty and religious coexistence, laying the foundation for the modern international system of nation-states.',
    era: 'Early Modern',
    icon: '🕊️',
  },
  {
    year: 1665,
    title: 'Hooke Discovers Cells',
    description: 'Robert Hooke examines cork through a microscope and coins the term "cells" to describe the tiny compartments he observes, laying the foundation for cell biology.',
    era: 'Early Modern',
    icon: '🔬',
  },
  {
    year: 1687,
    title: 'Newton\'s Principia Published',
    description: 'Isaac Newton publishes his laws of motion and universal gravitation, laying the foundation of classical physics and transforming our understanding of the natural world.',
    era: 'Early Modern',
    icon: '🍎',
  },
  {
    year: 1752,
    title: 'Franklin\'s Electricity Experiments',
    description: 'Benjamin Franklin conducts his famous kite experiment, demonstrating that lightning is electrical in nature and paving the way for the harnessing of electricity.',
    era: 'Early Modern',
    icon: '⚡',
  },
  {
    year: 1760,
    title: 'Industrial Revolution Begins',
    description: 'New manufacturing processes transform Britain and then the world, shifting from agrarian economies to industrial powerhouses powered by steam and coal.',
    era: 'Early Modern',
    icon: '🏭',
  },
  {
    year: 1769,
    title: 'Watt\'s Steam Engine',
    description: 'James Watt patents his improved steam engine with a separate condenser, dramatically increasing efficiency and powering the factories, mines, and railways of the Industrial Revolution.',
    era: 'Early Modern',
    icon: '🚂',
  },
  {
    year: 1776,
    title: 'United States Declares Independence',
    description: 'The thirteen American colonies declare independence from Britain, establishing a new nation founded on Enlightenment principles of liberty and self-governance.',
    era: 'Early Modern',
    icon: '🗽',
  },
  {
    year: 1789,
    title: 'French Revolution',
    description: 'The storming of the Bastille ignites a revolution that overthrows the monarchy, reshaping European politics and inspiring democratic movements worldwide.',
    era: 'Early Modern',
    icon: '🇫🇷',
  },
  {
    year: 1796,
    title: 'Jenner\'s Smallpox Vaccine',
    description: 'Edward Jenner demonstrates that inoculation with cowpox provides immunity to smallpox, pioneering the science of vaccination and saving countless millions of lives.',
    era: 'Early Modern',
    icon: '💉',
  },
  {
    year: 1804,
    title: 'Haiti Declares Independence',
    description: 'Enslaved people in Saint-Domingue overthrow French colonial rule in the only successful large-scale slave revolt in history, establishing the first free Black republic in the Western Hemisphere.',
    era: 'Modern',
    icon: '✊',
  },
  {
    year: 1807,
    title: 'Britain Abolishes the Slave Trade',
    description: 'The British Parliament passes the Abolition of the Slave Trade Act, beginning the long process of ending slavery across the British Empire.',
    era: 'Modern',
    icon: '🔗',
  },
  {
    year: 1837,
    title: 'The Electric Telegraph',
    description: 'Samuel Morse and others develop the electric telegraph, enabling near-instantaneous long-distance communication for the first time and shrinking the world.',
    era: 'Modern',
    icon: '📡',
  },
  {
    year: 1859,
    title: 'Darwin\'s Origin of Species',
    description: 'Charles Darwin publishes On the Origin of Species, presenting the theory of evolution by natural selection and revolutionising our understanding of life on Earth.',
    era: 'Modern',
    icon: '🐢',
  },
  {
    year: 1861,
    title: 'Germ Theory of Disease',
    description: 'Louis Pasteur and Robert Koch establish that microorganisms cause disease, overturning centuries of miasma theory and transforming medicine, surgery, and public health.',
    era: 'Modern',
    icon: '🦠',
  },
  {
    year: 1865,
    title: 'End of American Civil War & Abolition of Slavery',
    description: 'The 13th Amendment abolishes slavery throughout the United States following the bloodiest conflict in American history.',
    era: 'Modern',
    icon: '🕊️',
  },
  {
    year: 1868,
    title: 'Meiji Restoration in Japan',
    description: 'Japan ends centuries of feudal isolation and embarks on a dramatic programme of modernisation and industrialisation, transforming from a feudal society into a world power in barely a generation.',
    era: 'Modern',
    icon: '🏯',
  },
  {
    year: 1869,
    title: 'Mendeleev\'s Periodic Table',
    description: 'Dmitri Mendeleev arranges the known chemical elements by atomic weight, revealing a periodic pattern and even predicting the existence of undiscovered elements.',
    era: 'Modern',
    icon: '⚗️',
  },
  {
    year: 1876,
    title: 'Telephone Invented',
    description: 'Alexander Graham Bell patents the telephone, enabling voice communication over distances and laying the groundwork for the modern telecommunications industry.',
    era: 'Modern',
    icon: '📞',
  },
  {
    year: 1895,
    title: 'X-Rays Discovered',
    description: 'Wilhelm Roentgen discovers X-rays, allowing doctors to see inside the human body without surgery and opening an entirely new frontier in medical diagnostics.',
    era: 'Modern',
    icon: '🩻',
  },
  {
    year: 1896,
    title: 'Radioactivity Discovered',
    description: 'Henri Becquerel discovers radioactivity in uranium salts, a finding soon expanded by Marie and Pierre Curie, unlocking the secrets of the atom and transforming physics and medicine.',
    era: 'Modern',
    icon: '☢️',
  },
  {
    year: 1897,
    title: 'Radio Communication',
    description: 'Guglielmo Marconi demonstrates practical wireless telegraphy, sending signals without wires and launching the era of radio communication that connects the world.',
    era: 'Modern',
    icon: '📻',
  },
  {
    year: 1903,
    title: 'Powered Flight',
    description: 'Orville and Wilbur Wright achieve the first sustained, controlled, powered heavier-than-air flight at Kitty Hawk, North Carolina, inaugurating the age of aviation.',
    era: 'Modern',
    icon: '✈️',
  },
  {
    year: 1905,
    title: 'Einstein\'s Theory of Relativity',
    description: 'Albert Einstein publishes his special theory of relativity and the equation E=mc², revealing that mass and energy are interchangeable and rewriting the laws of physics.',
    era: 'Modern',
    icon: '🧪',
  },
  {
    year: 1914,
    title: 'World War I Begins',
    description: 'The assassination of Archduke Franz Ferdinand triggers a devastating global conflict. Over 20 million die in a war that redraws the map of Europe and the Middle East.',
    era: 'Modern',
    icon: '⚔️',
  },
  {
    year: 1920,
    title: 'Women\'s Suffrage in the US',
    description: 'The 19th Amendment grants American women the right to vote, a milestone in the global women\'s suffrage movement after decades of activism and struggle.',
    era: 'Modern',
    icon: '✊',
  },
  {
    year: 1928,
    title: 'Penicillin Discovered',
    description: 'Alexander Fleming accidentally discovers penicillin, the world\'s first antibiotic, ushering in a medical revolution that saves hundreds of millions of lives from bacterial infections.',
    era: 'Modern',
    icon: '💊',
  },
  {
    year: 1938,
    title: 'Nuclear Fission Achieved',
    description: 'Otto Hahn and Fritz Strassmann achieve nuclear fission by splitting the uranium atom, a discovery that leads to both nuclear power and the atomic bomb.',
    era: 'Modern',
    icon: '⚛️',
  },
  {
    year: 1939,
    title: 'World War II Begins',
    description: 'Nazi Germany invades Poland, starting the deadliest conflict in human history. Over 70 million people will die, including 6 million in the Holocaust.',
    era: 'Modern',
    icon: '💣',
  },
  {
    year: 1945,
    title: 'Atomic Bombs & End of WWII',
    description: 'The United States drops atomic bombs on Hiroshima and Nagasaki, ushering in the nuclear age and ending the Second World War.',
    era: 'Modern',
    icon: '☢️',
  },
  {
    year: 1947,
    title: 'Indian Independence & Partition',
    description: 'India gains independence from British rule through largely non-violent resistance led by Gandhi and Nehru, but the subcontinent is also painfully partitioned into India and Pakistan.',
    era: 'Modern',
    icon: '🇮🇳',
  },
  {
    year: 1947,
    title: 'The Transistor Invented',
    description: 'John Bardeen, Walter Brattain, and William Shockley invent the transistor at Bell Labs, a tiny semiconductor switch that becomes the building block of all modern electronics.',
    era: 'Modern',
    icon: '🔌',
  },
  {
    year: 1948,
    title: 'Universal Declaration of Human Rights',
    description: 'The United Nations adopts the Universal Declaration of Human Rights, establishing for the first time a common standard of fundamental rights and freedoms for all people.',
    era: 'Modern',
    icon: '📜',
  },
  {
    year: 1949,
    title: 'People\'s Republic of China Founded',
    description: 'Mao Zedong proclaims the People\'s Republic of China after decades of civil war, establishing a communist government over the world\'s most populous nation and reshaping the global balance of power.',
    era: 'Modern',
    icon: '🇨🇳',
  },
  {
    year: 1953,
    title: 'DNA Structure Discovered',
    description: 'James Watson and Francis Crick, building on Rosalind Franklin\'s X-ray data, reveal the double-helix structure of DNA, unlocking the molecular basis of heredity.',
    era: 'Modern',
    icon: '🧬',
  },
  {
    year: 1955,
    title: 'Civil Rights Movement',
    description: 'Rosa Parks refuses to give up her bus seat in Montgomery, Alabama, galvanising the American civil rights movement and the long struggle against racial segregation and injustice.',
    era: 'Modern',
    icon: '✊',
  },
  {
    year: 1957,
    title: 'Sputnik Launched',
    description: 'The Soviet Union launches Sputnik, the first artificial satellite, into orbit around the Earth, igniting the Space Race and marking humanity\'s first step into the cosmos.',
    era: 'Modern',
    icon: '🛰️',
  },
  {
    year: 1960,
    title: 'Year of Africa — Decolonisation Wave',
    description: 'Seventeen African nations gain independence in a single year, marking the dramatic acceleration of decolonisation across the continent and reshaping the global political order.',
    era: 'Modern',
    icon: '🌍',
  },
  {
    year: 1969,
    title: 'Moon Landing',
    description: 'Neil Armstrong and Buzz Aldrin become the first humans to walk on the Moon, a defining achievement of the Space Age and human ingenuity.',
    era: 'Modern',
    icon: '🌕',
  },
  {
    year: 1971,
    title: 'The Microprocessor',
    description: 'Intel releases the 4004, the first commercial microprocessor, placing an entire CPU on a single chip and setting the stage for the personal computer revolution.',
    era: 'Modern',
    icon: '💻',
  },
  {
    year: 1981,
    title: 'The Personal Computer',
    description: 'IBM releases its Personal Computer, popularising home and office computing. Along with Apple and others, the PC transforms work, education, and everyday life.',
    era: 'Modern',
    icon: '🖥️',
  },
  {
    year: 1983,
    title: 'The Internet is Born',
    description: 'ARPANET adopts TCP/IP, creating the foundational protocol of the modern Internet and beginning the most transformative communications revolution in history.',
    era: 'Modern',
    icon: '🌐',
  },
  {
    year: 1989,
    title: 'Fall of the Berlin Wall',
    description: 'The Berlin Wall falls, symbolising the end of the Cold War and the beginning of German reunification and a new era in global politics.',
    era: 'Modern',
    icon: '🧱',
  },
  {
    year: 1990,
    title: 'The World Wide Web',
    description: 'Tim Berners-Lee invents the World Wide Web at CERN, creating a system of hyperlinked documents accessible via the Internet that transforms how humanity shares and accesses information.',
    era: 'Modern',
    icon: '🕸️',
  },
  {
    year: 1991,
    title: 'Soviet Union Dissolves',
    description: 'The Soviet Union formally dissolves into fifteen independent republics, ending the Cold War superpower rivalry and reshaping the geopolitical order of the world.',
    era: 'Modern',
    icon: '🏳️',
  },
  {
    year: 1994,
    title: 'End of Apartheid — Mandela Elected',
    description: 'Nelson Mandela is elected President of South Africa in the country\'s first fully democratic election, ending decades of institutionalised racial segregation.',
    era: 'Modern',
    icon: '✊',
  },
  {
    year: 1997,
    title: 'Dolly the Sheep Cloned',
    description: 'Scientists at the Roslin Institute in Scotland clone Dolly the sheep from an adult cell, demonstrating that mammalian cloning is possible and sparking worldwide ethical debate.',
    era: 'Modern',
    icon: '🐑',
  },
  {
    year: 2003,
    title: 'Human Genome Sequenced',
    description: 'The Human Genome Project completes the sequencing of the entire human genome, mapping roughly 20,000 genes and opening a new era of personalised medicine and genetic research.',
    era: 'Modern',
    icon: '🧬',
  },
  {
    year: 2007,
    title: 'iPhone Released',
    description: 'Apple releases the iPhone, combining a phone, music player, and internet device into one touchscreen package. It sparks the smartphone revolution that puts computing power in billions of pockets.',
    era: 'Modern',
    icon: '📱',
  },
  {
    year: 2012,
    title: 'Deep Learning Revolution',
    description: 'AlexNet wins the ImageNet challenge by a massive margin, demonstrating the power of deep neural networks and igniting the modern AI revolution.',
    era: 'Modern',
    icon: '🤖',
  },
  {
    year: 2013,
    title: 'CRISPR Gene Editing',
    description: 'Scientists demonstrate that CRISPR-Cas9 can precisely edit DNA in living cells, providing a powerful and accessible tool for genetic engineering with vast medical and agricultural potential.',
    era: 'Modern',
    icon: '✂️',
  },
  {
    year: 2015,
    title: 'Gravitational Waves Detected',
    description: 'The LIGO observatory detects gravitational waves from two merging black holes, confirming Einstein\'s century-old prediction and opening an entirely new window on the universe.',
    era: 'Modern',
    icon: '🌊',
  },
  {
    year: 2021,
    title: 'James Webb Space Telescope Launched',
    description: 'NASA launches the James Webb Space Telescope, the most powerful space observatory ever built, designed to peer back to the earliest galaxies and reveal the origins of stars and planets.',
    era: 'Modern',
    icon: '🔭',
  },
  {
    year: 2022,
    title: 'The Age of AI',
    description: 'Large language models like ChatGPT bring AI into the mainstream, demonstrating human-level language understanding and transforming how we interact with technology.',
    era: 'Modern',
    icon: '🧠',
  },
];
