export const philosophyCategories = [
  { id: 'pre-socratic',  name: 'Pre-Socratic & Ancient Greek', color: '#F59E0B' },
  { id: 'eastern',       name: 'Eastern Philosophy',           color: '#10B981' },
  { id: 'medieval',      name: 'Medieval & Scholastic',        color: '#78716C' },
  { id: 'enlightenment', name: 'Renaissance & Enlightenment',  color: '#3B82F6' },
  { id: 'idealism',      name: 'German Idealism',              color: '#6366F1' },
  { id: 'nineteenth',    name: '19th-Century Movements',       color: '#EF4444' },
  { id: 'analytic',      name: 'Analytic & Continental',       color: '#C084FC' },
  { id: 'contemporary',  name: 'Contemporary Philosophy',      color: '#14B8A6' },
];

export const philosophyItems = [
  {
    id: 'pre-socratic',
    name: 'Pre-Socratic Philosophy',
    start: -620, end: -450,
    region: 'pre-socratic',
    icon: '🌊',
    description: "The first philosophers abandoned mythological explanations for the cosmos. Thales of Miletus (c. 624–546 BCE) proposed water as the fundamental substance. Anaximander posited the boundless (apeiron). Heraclitus held that all is flux ('you cannot step into the same river twice'). Parmenides argued that change is an illusion; being is one and unchanging. Pythagoras combined mathematics with mysticism. Empedocles proposed four elements; Democritus and Leucippus developed atomic theory (everything is atoms and void) — one of antiquity's most prescient ideas.",
    periods: [
      { name: 'Milesian School', start: -620, end: -546 },
      { name: 'Eleatics & Pluralists', start: -540, end: -450 },
    ],
  },
  {
    id: 'socrates-plato-aristotle',
    name: 'Plato & Aristotle',
    start: -469, end: -322,
    region: 'pre-socratic',
    icon: '🏛️',
    description: "Socrates (469–399 BCE) claimed to know nothing, exposing others' false knowledge through questioning (the Socratic method). Condemned by Athens for impiety, he drank hemlock. His pupil Plato (428–348 BCE) founded the Academy and developed the Theory of Forms — the eternal, perfect archetypes behind imperfect material things — along with Republic's vision of the philosopher-king. Aristotle (384–322 BCE), Plato's student and Alexander's tutor, founded the Lyceum and systematised logic (syllogism), ethics (virtue/eudaimonia), politics, biology, and metaphysics — the most encyclopaedic mind of antiquity.",
    periods: [
      { name: 'Socrates & Trial', start: -469, end: -399 },
      { name: 'Plato & the Academy', start: -387, end: -348 },
      { name: 'Aristotle & the Lyceum', start: -335, end: -322 },
    ],
  },
  {
    id: 'hellenistic-schools',
    name: 'Hellenistic Philosophical Schools',
    start: -300, end: 180,
    region: 'pre-socratic',
    icon: '📜',
    description: "Following Alexander's conquests, philosophy turned inward to personal ethics and tranquillity. The Stoics (Zeno of Citium, Epictetus, Marcus Aurelius) taught that virtue is the only true good; external events are indifferent — equanimity comes from aligning will with reason and nature. The Epicureans (Epicurus, Lucretius) sought tranquil pleasure (ataraxia) through friendship, philosophy, and modest living — not hedonism. The Pyrrhonist Sceptics suspended judgement on all questions. The Cynics (Diogenes in his barrel) rejected convention. All four schools competed in Athens and across the Hellenistic world.",
    periods: [
      { name: 'Early Stoicism & Epicureanism', start: -300, end: -100 },
      { name: 'Middle & Late Stoa', start: -100, end: 180 },
    ],
  },
  {
    id: 'classical-chinese',
    name: 'Classical Chinese Philosophy',
    start: -551, end: -221,
    region: 'eastern',
    icon: '☯️',
    description: "The 'Hundred Schools of Thought' (6th–3rd centuries BCE) produced China's most enduring philosophies during the Spring and Autumn and Warring States periods. Confucius (551–479 BCE) emphasised ritual propriety (lǐ), benevolence (rén), and filial piety as foundations of social order. Laozi's Tao Te Ching articulated Daoism — harmony with the natural Way (Tao), non-action (wu wei), simplicity. Mencius extended Confucianism, arguing human nature is fundamentally good. Zhuangzi developed Daoist mysticism with parables and paradoxes. Mozi advocated universal love and consequentialism. Han Feizi codified Legalism (rule through strict laws and punishments), adopted by the Qin dynasty.",
    periods: [
      { name: 'Confucius & Early Schools', start: -551, end: -450 },
      { name: 'Hundred Schools Period', start: -450, end: -221 },
    ],
  },
  {
    id: 'indian-philosophy',
    name: 'Indian Classical Philosophy',
    start: -800, end: 600,
    region: 'eastern',
    icon: '🪷',
    description: "India developed extraordinarily diverse philosophical traditions. The Upanishads (c. 800–200 BCE) explored the nature of Brahman (universal consciousness) and Atman (self), concluding their identity. The six orthodox darshanas (worldviews) included Nyaya (logic), Vaisheshika (atomism), Sankhya (dualism), Yoga (practice), Mimamsa (ritual exegesis), and Vedanta (Upanishadic synthesis). The heterodox schools include Buddhism (Siddhartha Gautama, c. 563–483 BCE) — the Middle Way, Four Noble Truths, Eightfold Path — and Jainism (Mahavira), with its radical ahimsa (non-violence). Buddhist philosopher Nagarjuna (c. 150–250 CE) developed Madhyamaka — the 'Middle Way' doctrine of emptiness (sunyata).",
    periods: [
      { name: 'Upanishadic Period', start: -800, end: -400 },
      { name: 'Buddhist & Jain Schools', start: -500, end: 300 },
      { name: 'Classical Systems', start: 200, end: 600 },
    ],
  },
  {
    id: 'neoplatonism',
    name: 'Neoplatonism',
    start: 204, end: 529,
    region: 'medieval',
    icon: '✨',
    description: "Plotinus (204–270 CE) synthesised Platonism, Pythagoreanism, and mystical elements into Neoplatonism — the philosophical framework that dominated late antiquity. His Enneads described reality as emanating from The One (beyond being and thought) → Nous (divine mind/intellect) → Soul → Matter. This hierarchy profoundly shaped Christian theology (Augustine), Islamic philosophy, and Renaissance Platonism. Porphyry systematised and transmitted Plotinus; Iamblichus added theurgy; Proclus completed the synthesis. Emperor Justinian closed the Platonic Academy in Athens in 529 CE, a symbolic end to pagan philosophy.",
    periods: [
      { name: 'Plotinus & Porphyry', start: 204, end: 300 },
      { name: 'Late Neoplatonism', start: 300, end: 529 },
    ],
  },
  {
    id: 'islamic-philosophy',
    name: 'Islamic Golden Age Philosophy',
    start: 800, end: 1200,
    region: 'medieval',
    icon: '📖',
    description: "Islamic philosophers synthesised Greek philosophy with Islamic theology, transmitting and extending ancient learning. Al-Kindi (801–873) introduced Aristotle to the Arab world. Al-Farabi developed political philosophy drawing on Plato's Republic. Avicenna (Ibn Sina, 980–1037) — the 'Prince of Physicians' — wrote the Canon of Medicine and developed floating man thought experiments prefiguring Cartesian doubt. Ibn Rushd (Averroes, 1126–1198) wrote influential commentaries on Aristotle so important that medieval Europeans called him simply 'The Commentator'. Al-Ghazali's Incoherence of the Philosophers critiqued Greek philosophy from a Sufi perspective, sparking debate that shaped both Islamic and Christian theology.",
    periods: [
      { name: 'Al-Kindi & Al-Farabi', start: 800, end: 1000 },
      { name: 'Avicenna & Al-Ghazali', start: 1000, end: 1111 },
      { name: 'Averroes & Late Period', start: 1126, end: 1200 },
    ],
  },
  {
    id: 'scholasticism',
    name: 'Medieval Scholasticism',
    start: 1050, end: 1350,
    region: 'medieval',
    icon: '⛪',
    description: "Medieval Christian philosophy sought to reconcile faith and reason, primarily using rediscovered Aristotle. Anselm of Canterbury (1033–1109) formulated the ontological argument for God's existence. Peter Abelard introduced rigorous dialectical method (Sic et Non). The recovery of Aristotle through Arabic translations sparked intellectual revolution; the University of Paris became Europe's philosophical centre. Thomas Aquinas (1225–1274) synthesised Aristotle with Christian theology in his Summa Theologiae — natural law, the Five Ways (proofs of God), and the immortal soul. Duns Scotus distinguished philosophy from theology; William of Ockham ('Ockham's Razor') insisted on simplest explanations and undermined scholastic metaphysics.",
    periods: [
      { name: 'Early Scholasticism', start: 1050, end: 1200 },
      { name: 'High Scholasticism (Aquinas)', start: 1200, end: 1277 },
      { name: 'Late Scholasticism (Ockham)', start: 1277, end: 1350 },
    ],
  },
  {
    id: 'renaissance-humanism',
    name: 'Renaissance Humanism',
    start: 1350, end: 1600,
    region: 'enlightenment',
    icon: '🎨',
    description: "Renaissance humanism placed humanity at the centre of intellectual life, drawing on recovered classical texts. Petrarch is called the 'father of humanism'. Pico della Mirandola's Oration on the Dignity of Man (1486) argued humans are uniquely self-determining. Erasmus of Rotterdam satirised Church corruption in Praise of Folly; Thomas More's Utopia imagined an ideal society. Niccolò Machiavelli's The Prince (1532) founded modern political science — rulers should be effective, not morally exemplary. Montaigne invented the personal essay as philosophical form. The printing press (1450s) revolutionised the transmission of ideas across Europe.",
    periods: [
      { name: 'Italian Humanism', start: 1350, end: 1450 },
      { name: 'Northern Humanism', start: 1450, end: 1600 },
    ],
  },
  {
    id: 'rationalism',
    name: 'Continental Rationalism',
    start: 1637, end: 1716,
    region: 'enlightenment',
    icon: '🔭',
    description: "Continental rationalists held that reason alone — not sensory experience — is the primary source of knowledge. René Descartes (1596–1650) doubted everything until reaching 'I think, therefore I am' (cogito ergo sum); his Meditations reconstructed knowledge on that foundation and introduced mind-body dualism. Baruch Spinoza (1632–1677) wrote the Ethics in geometric form, identifying God with Nature (pantheism) and developing one of philosophy's most rigorous systems. Gottfried Wilhelm Leibniz (1646–1716) posited monads as the fundamental constituents of reality, proposed theodicy (best of all possible worlds, satirised by Voltaire in Candide), and co-invented calculus alongside Newton.",
    periods: [
      { name: 'Descartes', start: 1637, end: 1650 },
      { name: 'Spinoza', start: 1661, end: 1677 },
      { name: 'Leibniz', start: 1686, end: 1716 },
    ],
  },
  {
    id: 'british-empiricism',
    name: 'British Empiricism',
    start: 1689, end: 1781,
    region: 'enlightenment',
    icon: '📚',
    description: "British empiricists held that all knowledge derives from sensory experience. John Locke (1632–1704) argued the mind is a blank slate (tabula rasa) at birth; his political philosophy (government by consent, natural rights to life, liberty, and property) directly influenced the American Declaration of Independence. George Berkeley (1685–1753) pushed empiricism to idealism: 'to be is to be perceived' (esse est percipi) — matter doesn't exist independently of minds. David Hume (1711–1776) radically questioned causation (we only observe constant conjunction, not necessary connection), induction, personal identity, and religion — triggering Kant's 'awakening from dogmatic slumber'.",
    periods: [
      { name: 'Locke', start: 1689, end: 1704 },
      { name: 'Berkeley', start: 1710, end: 1734 },
      { name: 'Hume', start: 1739, end: 1781 },
    ],
  },
  {
    id: 'enlightenment',
    name: 'The Enlightenment',
    start: 1685, end: 1789,
    region: 'enlightenment',
    icon: '💡',
    description: "The Enlightenment ('Age of Reason') applied rational critique to all aspects of human life — religion, politics, society. Voltaire championed religious tolerance and attacked superstition and fanaticism. Rousseau proposed the 'social contract' — political authority derives from collective agreement — and that civilisation corrupts naturally innocent humans. Montesquieu developed separation of powers in The Spirit of the Laws, directly shaping US and French constitutions. Diderot and d'Alembert's Encyclopédie (1751–1772) systematised human knowledge across 28 volumes, embodying the Enlightenment project. The movement culminated in the American Revolution (1776) and French Revolution (1789).",
    periods: [
      { name: 'Early Enlightenment', start: 1685, end: 1740 },
      { name: 'High Enlightenment', start: 1740, end: 1789 },
    ],
  },
  {
    id: 'kant',
    name: "Kant's Critical Philosophy",
    start: 1781, end: 1804,
    region: 'idealism',
    icon: '🌟',
    description: "Immanuel Kant (1724–1804) initiated a 'Copernican revolution' in philosophy. His three Critiques reshaped all subsequent philosophy. The Critique of Pure Reason (1781) argued that space, time, and causation are forms imposed by the mind on experience — we cannot know 'things in themselves' (Ding an sich). The Critique of Practical Reason (1788) grounded ethics in the Categorical Imperative: 'Act only according to that maxim by which you can at the same time will that it should become a universal law.' The Critique of Judgement (1790) addressed aesthetics and teleology. Kant's synthesis of rationalism and empiricism dominated European philosophy for two centuries.",
    periods: [
      { name: 'Critique of Pure Reason', start: 1781, end: 1788 },
      { name: 'Ethics & Aesthetics', start: 1788, end: 1804 },
    ],
  },
  {
    id: 'german-idealism',
    name: 'German Idealism & Romanticism',
    start: 1794, end: 1860,
    region: 'idealism',
    icon: '🌀',
    description: "Kant's successors radicalised his idealism. Fichte argued the self (Ich) is the ultimate reality that posits both itself and the world. Schelling developed a philosophy of nature (Naturphilosophie) and absolute idealism. Hegel (1770–1831) built the most ambitious philosophical system since Aristotle: the dialectic (thesis–antithesis–synthesis) drives the unfolding of Geist (Spirit/Mind) through history toward self-realisation. His Phenomenology of Spirit (1807) traces consciousness from bare sense experience to Absolute Knowledge. History is the progress of freedom. Marx would later 'stand Hegel on his head' — making matter primary, not mind. Schopenhauer (1788–1860) countered with a pessimistic Will as reality, influencing Nietzsche, Wagner, and Freud.",
    periods: [
      { name: 'Fichte & Schelling', start: 1794, end: 1807 },
      { name: 'Hegel', start: 1807, end: 1831 },
      { name: 'Schopenhauer', start: 1818, end: 1860 },
    ],
  },
  {
    id: 'marx-kierkegaard-nietzsche',
    name: 'Marx, Kierkegaard & Nietzsche',
    start: 1841, end: 1900,
    region: 'nineteenth',
    icon: '⚡',
    description: "Three 19th-century thinkers who exploded mainstream philosophy. Søren Kierkegaard (1813–1855) attacked Hegel's abstract system with the concrete existing individual; his 'leap of faith' and 'stages of existence' (aesthetic, ethical, religious) founded existentialism. Karl Marx (1818–1883), with Engels, developed dialectical materialism — history driven by economic class struggle; religion as 'opium of the people'; capitalism's inevitable contradictions would produce communist revolution. The Communist Manifesto (1848) and Das Kapital (1867) shaped the next century. Friedrich Nietzsche (1844–1900) declared 'God is dead', attacked slave morality, championed the Übermensch (overman) who creates values, and developed eternal recurrence — among the most discussed and misused ideas in philosophy.",
    periods: [
      { name: 'Kierkegaard', start: 1841, end: 1855 },
      { name: 'Marx & Engels', start: 1844, end: 1883 },
      { name: 'Nietzsche', start: 1878, end: 1900 },
    ],
  },
  {
    id: 'pragmatism',
    name: 'Pragmatism & American Philosophy',
    start: 1867, end: 1940,
    region: 'nineteenth',
    icon: '🔬',
    description: "Pragmatism — developed in America — judged ideas by their practical consequences. Charles Sanders Peirce (1839–1914) coined the term: the meaning of a concept is the practical effects of its object. William James (1842–1910) applied pragmatism to religion and truth: beliefs are true if they 'work' — if they help us navigate the world. John Dewey (1859–1952) developed instrumentalism: ideas are tools for problem-solving; democracy and progressive education are his legacies. Pragmatism influenced 20th-century American philosophy, law, and educational theory, and was revived by Richard Rorty in the late 20th century.",
    periods: [
      { name: 'Peirce & James', start: 1867, end: 1907 },
      { name: 'Dewey & Progressive Pragmatism', start: 1900, end: 1940 },
    ],
  },
  {
    id: 'analytic-philosophy',
    name: 'Analytic Philosophy',
    start: 1903, end: 1970,
    region: 'analytic',
    icon: '🧮',
    description: "Analytic philosophy emerged from logic and language analysis. Gottlob Frege revolutionised logic with predicate calculus. Bertrand Russell and Alfred North Whitehead attempted to reduce mathematics to logic in Principia Mathematica (1910–13). The early Wittgenstein's Tractatus Logico-Philosophicus (1921) argued meaningful propositions must picture facts; philosophy's task is to dissolve rather than solve metaphysical problems. The Vienna Circle (Carnap, Schlick, Neurath) developed logical positivism — only empirically verifiable statements or logical tautologies are meaningful; metaphysics is nonsense. Karl Popper countered with falsificationism: science advances by bold theories open to refutation, not verification. G.E. Moore championed common-sense philosophy and rigorous analysis.",
    periods: [
      { name: 'Frege, Russell & Early Wittgenstein', start: 1903, end: 1930 },
      { name: 'Vienna Circle & Logical Positivism', start: 1922, end: 1945 },
      { name: 'Popper & Ordinary Language Philosophy', start: 1934, end: 1970 },
    ],
  },
  {
    id: 'existentialism-phenomenology',
    name: 'Existentialism & Phenomenology',
    start: 1900, end: 1975,
    region: 'analytic',
    icon: '🕵️',
    description: "Phenomenology (Husserl, 1900) studied the structures of conscious experience as directly lived. Martin Heidegger's Being and Time (1927) asked the question of Being itself — Dasein ('being-there') is thrown into a world, faces anxiety, and must confront its own death to live authentically. Jean-Paul Sartre (1905–1980) declared 'existence precedes essence' — humans have no pre-given nature; we are 'condemned to be free' and responsible for who we become (Being and Nothingness, 1943). Albert Camus confronted the absurd — the conflict between humanity's need for meaning and the universe's silence. Simone de Beauvoir applied existentialism to feminism: 'one is not born, but rather becomes, woman' (The Second Sex, 1949). Maurice Merleau-Ponty grounded philosophy in embodied perception.",
    periods: [
      { name: 'Husserl & Heidegger', start: 1900, end: 1940 },
      { name: 'Sartre, Camus & de Beauvoir', start: 1940, end: 1975 },
    ],
  },
  {
    id: 'late-wittgenstein',
    name: 'Late Wittgenstein & Ordinary Language',
    start: 1945, end: 1970,
    region: 'analytic',
    icon: '🗣️',
    description: "Wittgenstein radically reversed his early views in Philosophical Investigations (1953, posthumous). Language is not a picture of facts but a set of practices — 'language games' embedded in 'forms of life'. Philosophical problems arise from misuse of language; the goal is therapy, not theory. J.L. Austin developed 'speech act theory' — utterances do things (promises, commands, declarations), not just describe. Gilbert Ryle attacked the 'ghost in the machine' (Cartesian dualism). Oxford ordinary language philosophy became the dominant mode in English-language philosophy through the 1950s–60s, profoundly influencing philosophy of mind, ethics, and linguistics.",
    periods: [
      { name: 'Philosophical Investigations', start: 1945, end: 1955 },
      { name: 'Oxford Ordinary Language School', start: 1945, end: 1970 },
    ],
  },
  {
    id: 'contemporary-philosophy',
    name: 'Contemporary & Postmodern Philosophy',
    start: 1960, end: 2025,
    region: 'contemporary',
    icon: '💬',
    description: "Post-1960 philosophy fragmented into rich diversity. French poststructuralism: Jacques Derrida's deconstruction revealed how texts undermine their own meanings; Michel Foucault analysed how power produces knowledge, sexuality, madness, and the body; Gilles Deleuze developed radical philosophy of difference and becoming. Political philosophy: John Rawls's A Theory of Justice (1971) revived social contract theory with the 'veil of ignorance'; Robert Nozick replied with libertarian rights theory. Philosophy of mind: the 'hard problem' of consciousness (Chalmers); functionalism (Putnam/Dennett). Applied ethics (Peter Singer's effective altruism). Feminist philosophy (Judith Butler on gender performativity). Philosophy of science, language, and logic continue to flourish in analytic departments worldwide.",
    periods: [
      { name: 'French Poststructuralism', start: 1960, end: 1990 },
      { name: 'Rawls & Political Philosophy', start: 1971, end: 2000 },
      { name: 'Philosophy of Mind & Applied Ethics', start: 1990, end: 2025 },
    ],
  },
];
