export const warsCategories = [
  { id: 'ancient',     name: 'Ancient Warfare',              color: '#92400E' },
  { id: 'medieval',    name: 'Medieval Conflicts',           color: '#78716C' },
  { id: 'early-modern',name: 'Colonial & Early Modern',      color: '#B45309' },
  { id: 'nineteenth',  name: 'Napoleonic & 19th Century',    color: '#3B82F6' },
  { id: 'world-wars',  name: 'World Wars',                   color: '#DC2626' },
  { id: 'modern',      name: 'Cold War & Modern',            color: '#6366F1' },
];

export const warsItems = [
  {
    id: 'persian-wars',
    name: 'Greco-Persian Wars',
    start: -499, end: -449,
    region: 'ancient',
    icon: '🏛️',
    description: "The Greco-Persian Wars (499–449 BCE) were one of antiquity's most consequential conflicts: a small collection of Greek city-states resisting the vast Achaemenid Persian Empire. The Ionian Revolt (499 BCE) triggered Darius I's punitive campaign; at Marathon (490 BCE), Athens' outnumbered hoplites defeated the Persian army in a victory that became legendary. Darius's son Xerxes led a massive invasion a decade later — the sea battle of Salamis (480 BCE), where the outnumbered Greek fleet shattered the Persian armada, and the land battle of Plataea (479 BCE) ended the Persian threat. The wars forged a distinct Greek identity, accelerated Athenian democracy, and enabled the cultural flowering of Classical Greece.",
    periods: [
      { name: 'Ionian Revolt', start: -499, end: -493 },
      { name: 'First Persian Invasion (Marathon)', start: -492, end: -490 },
      { name: 'Second Persian Invasion (Salamis/Plataea)', start: -480, end: -479 },
      { name: 'Delian League & Peace', start: -478, end: -449 },
    ],
  },
  {
    id: 'peloponnesian-war',
    name: 'Peloponnesian War',
    start: -431, end: -404,
    region: 'ancient',
    icon: '⚔️',
    description: "The Peloponnesian War (431–404 BCE) was the defining conflict of Classical Greece — Athens' naval empire against Sparta's land power. Thucydides' History of the Peloponnesian War is also history's first great work of political analysis. Athens' fatal strategic error was the Sicilian Expedition (415–413 BCE) — a catastrophic overreach that destroyed its fleet and best troops. Sparta, financed by Persian gold, eventually built a navy; the Battle of Aegospotami (405 BCE) annihilated the Athenian fleet. Athens surrendered in 404 BCE, its Long Walls demolished, its empire dissolved. The war exhausted both powers, opening the way for Macedonian dominance a generation later.",
    periods: [
      { name: 'Archidamian War', start: -431, end: -421 },
      { name: 'Peace of Nicias', start: -421, end: -415 },
      { name: 'Sicilian Expedition', start: -415, end: -413 },
      { name: 'Decelean/Ionian War', start: -413, end: -404 },
    ],
  },
  {
    id: 'alexander-conquests',
    name: 'Wars of Alexander the Great',
    start: -334, end: -323,
    region: 'ancient',
    icon: '🐎',
    description: "In eleven years (334–323 BCE), Alexander III of Macedon conquered an empire stretching from Greece to northwestern India — the largest the ancient world had seen. After defeating Darius III of Persia at the decisive Battle of Gaugamela (331 BCE), Alexander pushed east through Central Asia, into Bactria and Sogdiana (modern Afghanistan), and through the Khyber Pass into India, defeating King Porus at the Hydaspes (326 BCE). His army, after eight years of continuous campaigning, finally mutinied on the banks of the Hyphasis and refused to go further. Alexander died in Babylon in 323 BCE, aged 32, having never lost a battle. His empire fragmented among his generals (the Diadochi), but permanently hellenised the Near East and Central Asia.",
    periods: [
      { name: 'Liberation of Ionia & Egypt', start: -334, end: -332 },
      { name: 'Defeat of Persia', start: -331, end: -330 },
      { name: 'Eastern Campaigns', start: -329, end: -323 },
    ],
  },
  {
    id: 'punic-wars',
    name: 'Punic Wars',
    start: -264, end: -146,
    region: 'ancient',
    icon: '🐘',
    description: "The three Punic Wars between Rome and Carthage determined which power would dominate the Mediterranean world. The First (264–241 BCE) was primarily naval; Rome, which had no real fleet at the outset, built one from scratch and eventually won. The Second Punic War (218–201 BCE) produced Hannibal Barca — Rome's greatest antagonist. Hannibal crossed the Alps with 40,000 men and war elephants, won a series of stunning victories (Trebia, Lake Trasimene, Cannae — where 70,000 Romans were killed in a single afternoon), and occupied Italy for 15 years without a supply line. Rome refused to surrender; Scipio Africanus took the war to Spain and then to Africa. Hannibal was recalled; defeated at Zama (202 BCE). The Third Punic War (149–146 BCE) ended with Carthage's complete destruction and its people sold into slavery.",
    periods: [
      { name: 'First Punic War', start: -264, end: -241 },
      { name: 'Second Punic War (Hannibal)', start: -218, end: -201 },
      { name: 'Third Punic War', start: -149, end: -146 },
    ],
  },
  {
    id: 'roman-conquest',
    name: 'Roman Wars & Civil Wars',
    start: -100, end: 117,
    region: 'ancient',
    icon: '🦅',
    description: "Rome's rise to Mediterranean supremacy was driven by almost constant warfare. The late Republic was torn apart by civil wars: Marius vs. Sulla (88–82 BCE), Caesar vs. Pompey (49–45 BCE) — Caesar's crossing of the Rubicon launched a civil war; his assassination (44 BCE) triggered another. The final contest between Octavian and Mark Antony, decided at Actium (31 BCE), produced the Principate under Augustus. Imperial expansion continued: Trajan conquered Dacia (modern Romania) and briefly held Mesopotamia. Roman warfare combined military genius (the legion system), engineering (siege warfare, roads), and political incorporation of conquered peoples — creating an empire of 70 million across three continents.",
    periods: [
      { name: 'Late Republic Civil Wars', start: -100, end: -31 },
      { name: 'Augustan Wars', start: -31, end: 14 },
      { name: 'Imperial Expansion', start: 14, end: 117 },
    ],
  },
  {
    id: 'mongol-conquests',
    name: 'Mongol Conquests',
    start: 1206, end: 1368,
    region: 'medieval',
    icon: '🏹',
    description: "Genghis Khan (c. 1162–1227) unified the nomadic Mongol tribes in 1206 and launched the most rapid territorial expansion in history. The Mongol Empire at its peak stretched from Korea to Poland — over 24 million square kilometres, roughly 22% of Earth's land area. Campaigns were characterised by extraordinary mobility, tactical flexibility, and devastating violence: cities that resisted were massacred, those that submitted were spared. The conquest of Central Asia (1219–1221) killed an estimated 15 million people — cities like Samarkand, Merv, and Nishapur were annihilated. Baghdad fell in 1258, ending the Abbasid Caliphate. The Mongols lost only to the Mamluks of Egypt (Ain Jalut, 1260) and were repelled from Japan by typhoons (1274, 1281 — the 'divine winds', kamikaze).",
    periods: [
      { name: 'Unification & Chinese Campaigns', start: 1206, end: 1227 },
      { name: 'Conquest of Central Asia & Russia', start: 1219, end: 1242 },
      { name: 'Fall of Baghdad & Mamluk Defeat', start: 1258, end: 1260 },
      { name: 'Fragmentation & Decline', start: 1260, end: 1368 },
    ],
  },
  {
    id: 'crusades',
    name: 'The Crusades',
    start: 1095, end: 1291,
    region: 'medieval',
    icon: '✝️',
    description: "The Crusades (1095–1291) were a series of religiously motivated military campaigns launched by Western Christendom to recapture the Holy Land from Muslim rule and defend Christian interests. Pope Urban II's speech at Clermont (1095) launched the First Crusade; the crusaders captured Jerusalem in 1099 in a bloodbath. Four Crusader States were established in the Levant. Saladin, Sultan of Egypt and Syria, recaptured Jerusalem in 1187, triggering the Third Crusade (Richard I of England vs. Saladin — a fascinating contest between two great commanders). The Fourth Crusade (1202–04) infamously sacked Constantinople, fatally weakening the Byzantine Empire. The final Crusader stronghold, Acre, fell in 1291. The Crusades permanently shaped Christian-Muslim relations, transmitted Greek philosophy to Europe via Arabic translations, and opened new trade routes.",
    periods: [
      { name: 'First Crusade & Jerusalem', start: 1095, end: 1099 },
      { name: 'Crusader States', start: 1099, end: 1187 },
      { name: 'Saladin & Third Crusade', start: 1187, end: 1192 },
      { name: 'Later Crusades & Decline', start: 1202, end: 1291 },
    ],
  },
  {
    id: 'hundred-years-war',
    name: 'Hundred Years\' War',
    start: 1337, end: 1453,
    region: 'medieval',
    icon: '🏰',
    description: "The Hundred Years' War (1337–1453) was a series of conflicts between the kingdoms of England and France — at stake was the French crown and England's continental possessions. The longbow proved decisive in early English victories: Crécy (1346), Poitiers (1356), and Agincourt (1415, immortalised by Shakespeare) saw English archers decimate French knights. Henry V briefly united the crowns. Then Joan of Arc (c. 1412–1431) — a peasant girl claiming divine visions — rallied the dispirited French forces, broke the siege of Orléans (1429), and crowned Charles VII at Reims. Captured by the Burgundians, sold to the English, and burned at the stake as a heretic, she became France's national saint. By 1453 England had lost all of France except Calais; the war forged French national identity.",
    periods: [
      { name: 'English Ascendancy (Crécy, Poitiers)', start: 1337, end: 1360 },
      { name: 'Peace & Renewal', start: 1360, end: 1415 },
      { name: 'Agincourt & Henry V', start: 1415, end: 1422 },
      { name: 'Joan of Arc & French Recovery', start: 1429, end: 1453 },
    ],
  },
  {
    id: 'thirty-years-war',
    name: 'Thirty Years\' War',
    start: 1618, end: 1648,
    region: 'early-modern',
    icon: '💀',
    description: "The Thirty Years' War (1618–1648) began as a religious conflict between Catholic and Protestant states of the Holy Roman Empire but became a general European power struggle that devastated Central Europe. The defenestration of Prague (1618) triggered Bohemian Protestant revolt; the war spread and drew in Denmark, Sweden, France, and Spain. Sweden's Gustavus Adolphus was the great Protestant military commander before his death at Lützen (1632). France — a Catholic kingdom fighting for strategic interest over religion — subsidised Protestant forces. The Peace of Westphalia (1648) established the modern system of sovereign nation-states and the principle of non-interference in internal religious affairs. Germany lost an estimated 25–40% of its population; some regions lost half their people to war, plague, and famine.",
    periods: [
      { name: 'Bohemian Phase', start: 1618, end: 1625 },
      { name: 'Danish & Swedish Phases', start: 1625, end: 1635 },
      { name: 'French Phase', start: 1635, end: 1648 },
    ],
  },
  {
    id: 'seven-years-war',
    name: 'Seven Years\' War',
    start: 1756, end: 1763,
    region: 'early-modern',
    icon: '🌍',
    description: "Often called the first 'world war', the Seven Years' War (1756–1763) was fought simultaneously across five continents. Britain and Prussia faced France, Austria, Russia, Spain, and Sweden. The British victories were decisive: Plassey (1757) established British dominance in India; the Plains of Abraham (1759) captured Quebec and won Canada; British naval supremacy strangled French commerce. The Treaty of Paris (1763) reshaped the world — Britain gained Canada, Florida, and vast Indian territory, emerging as the world's dominant imperial power. Winston Churchill called it the war 'that laid the foundation of the British Empire'. The French loss was so humiliating it directly contributed to France's support for American independence and, ultimately, the French Revolution.",
    periods: [
      { name: 'European Theatre', start: 1756, end: 1763 },
      { name: 'North American Theatre (French & Indian War)', start: 1754, end: 1763 },
      { name: 'Indian Theatre (Plassey)', start: 1757, end: 1763 },
    ],
  },
  {
    id: 'napoleonic-wars',
    name: 'Napoleonic Wars',
    start: 1803, end: 1815,
    region: 'nineteenth',
    icon: '🎖️',
    description: "Napoleon Bonaparte (1769–1821) — Corsican-born artillery officer turned Emperor — dominated European warfare for a decade with a combination of speed, massed artillery, and corps system that transformed military strategy still taught at staff colleges today. At Austerlitz (1805), his decisive victory over the Austrian and Russian emperors is considered the finest tactical battle in history. He dominated Europe from the Iberian Peninsula to the Russian border. Napoleon's two fatal mistakes: the Peninsula War (from 1808), where Spanish guerrilla warfare bled French forces continuously; and the invasion of Russia (1812) — 600,000 men marched into Russia, fewer than 100,000 returned. Defeated at Waterloo (June 18, 1815) by Wellington and Blücher, he was exiled to St Helena. The Congress of Vienna (1815) reshaped Europe and established a balance-of-power system that largely held until 1914.",
    periods: [
      { name: 'Consulate & Italian Campaigns', start: 1796, end: 1805 },
      { name: 'Height: Austerlitz to Tilsit', start: 1805, end: 1807 },
      { name: 'Peninsula & Overextension', start: 1808, end: 1812 },
      { name: 'Russian Campaign & Collapse', start: 1812, end: 1815 },
    ],
  },
  {
    id: 'american-civil-war',
    name: 'American Civil War',
    start: 1861, end: 1865,
    region: 'nineteenth',
    icon: '🇺🇸',
    description: "The American Civil War (1861–1865) was the bloodiest conflict in American history and one of the first 'modern' wars — combining industrialised production, railways, telegraph communications, and mass conscription. At its core was the question of slavery and the nature of the Union. The Confederacy (11 Southern slave states) had brilliant generals — Robert E. Lee, Thomas 'Stonewall' Jackson — but ultimately couldn't overcome Union industrial, demographic, and naval superiority. The Emancipation Proclamation (January 1, 1863) transformed the war's purpose. Grant's grinding Overland Campaign (1864) and Sherman's March to the Sea broke Confederate will. Lee surrendered at Appomattox (April 9, 1865). Approximately 620,000 soldiers died — more than in all other American wars combined to that point. The 13th Amendment abolished slavery; Reconstruction attempted — and largely failed — to integrate formerly enslaved people as citizens.",
    periods: [
      { name: 'Fort Sumter & Early War', start: 1861, end: 1862 },
      { name: 'Gettysburg & Vicksburg (Turning Point)', start: 1863, end: 1863 },
      { name: 'Grant\'s Campaign & Sherman\'s March', start: 1864, end: 1865 },
    ],
  },
  {
    id: 'world-war-one',
    name: 'World War I',
    start: 1914, end: 1918,
    region: 'world-wars',
    icon: '🪖',
    description: "The Great War (1914–1918) was the first industrialised mass slaughter — the catastrophic collision of 19th-century military tactics with 20th-century weapons. The assassination of Archduke Franz Ferdinand (June 28, 1914) triggered a chain of alliances pulling all the major powers into war within weeks. The Western Front settled into a nightmare of trenches stretching from the English Channel to Switzerland. The Battle of the Somme (1916) killed 60,000 British soldiers on its first day; the Battle of Verdun lasted 10 months and killed 300,000 on each side. New weapons — poison gas, machine guns, tanks, aircraft, submarines — defined the conflict. The United States entered in 1917; German collapse followed in 1918. Approximately 20 million died. The Paris Peace Settlement (1919) dismembered empires and redrew maps — sowing the seeds of WWII through vindictive terms (the War Guilt Clause and reparations) that humiliated Germany.",
    periods: [
      { name: 'Opening Campaigns & Trenches', start: 1914, end: 1915 },
      { name: 'Industrial Slaughter (Verdun, Somme)', start: 1916, end: 1916 },
      { name: 'US Entry & German Collapse', start: 1917, end: 1918 },
    ],
  },
  {
    id: 'world-war-two',
    name: 'World War II',
    start: 1939, end: 1945,
    region: 'world-wars',
    icon: '💥',
    description: "World War II (1939–1945) was the deadliest conflict in human history — an estimated 70–85 million people died, including 6 million Jews and millions of others in the Holocaust. Nazi Germany's Blitzkrieg ('lightning war') overran Poland (September 1939), France (June 1940), and drove deep into the Soviet Union (June 1941, Operation Barbarossa). The Eastern Front was by far the largest and most destructive theatre: the Soviet Union lost an estimated 27 million people. The Pacific War began with Japan's attack on Pearl Harbor (December 7, 1941). The Allied turning points: Stalingrad (1942–43, one million dead), El Alamein (1942), D-Day (June 6, 1944) — 156,000 Allied troops landed on Normandy beaches. The Pacific was decided by carrier battles (Midway, 1942) and island-hopping. The atomic bombs on Hiroshima (August 6) and Nagasaki (August 9, 1945) ended the Pacific war. The Holocaust — the systematic genocide of 6 million Jews and millions of others — remains history's most meticulously documented crime against humanity.",
    periods: [
      { name: 'Blitzkrieg & Fall of France', start: 1939, end: 1941 },
      { name: 'Eastern Front & Pacific War', start: 1941, end: 1943 },
      { name: 'Allied Offensives & Victory', start: 1943, end: 1945 },
    ],
  },
  {
    id: 'cold-war-conflicts',
    name: 'Cold War & Proxy Conflicts',
    start: 1947, end: 1991,
    region: 'modern',
    icon: '☢️',
    description: "The Cold War (1947–1991) was the ideological and geopolitical struggle between the United States and Soviet Union — a conflict fought primarily through arms races, proxy wars, and espionage rather than direct confrontation (which might trigger nuclear annihilation). Key crises: the Berlin Blockade (1948), Korean War (1950–53, 3 million dead), Cuban Missile Crisis (October 1962 — the closest the world came to nuclear war), Vietnam War (1955–75, 3 million dead), Soviet invasion of Afghanistan (1979–89). Both superpowers maintained arsenals of thousands of nuclear warheads; NATO and Warsaw Pact lined up armies across a divided Europe. The Cold War also played out in space (Sputnik 1957, Moon landing 1969), in decolonisation (both powers competed for influence in newly independent nations), and in culture. The Soviet Union's collapse (1991) ended the Cold War but left a unipolar world with new instabilities.",
    periods: [
      { name: 'Korean War & Early Cold War', start: 1947, end: 1960 },
      { name: 'Cuban Crisis & Vietnam War', start: 1960, end: 1975 },
      { name: 'Afghanistan & Soviet Collapse', start: 1979, end: 1991 },
    ],
  },
  {
    id: 'decolonisation-wars',
    name: 'Wars of Independence & Decolonisation',
    start: 1945, end: 1980,
    region: 'modern',
    icon: '🌍',
    description: "The post-WWII period saw the rapid disintegration of European colonial empires — often violently. The French wars in Indochina (1946–54) and Algeria (1954–62) were particularly brutal; the Algerian War killed an estimated 300,000–1 million and was characterised by torture and atrocities on both sides. The Dutch fought a colonial war in Indonesia (1945–49). Kenya's Mau Mau uprising (1952–60) was suppressed by Britain with concentration camps. India's partition (1947) produced 200,000–2 million deaths and 10–20 million refugees. China's Communist revolution (1949) followed 22 years of civil war. The Korean War (1950–53) and Vietnam War (1955–75) were both decolonisation conflicts filtered through Cold War superpower competition. By 1980, almost all former colonies had achieved independence — often with borders drawn by colonial powers that cut across ethnic and religious communities, generating conflicts that persist today.",
    periods: [
      { name: 'Asian Independence Wars', start: 1945, end: 1954 },
      { name: 'African Independence Conflicts', start: 1952, end: 1975 },
      { name: 'Vietnam War', start: 1955, end: 1975 },
    ],
  },
  {
    id: 'post-cold-war',
    name: 'Post-Cold War Conflicts',
    start: 1991, end: 2025,
    region: 'modern',
    icon: '🌐',
    description: "The end of the Cold War did not end war. The 1990s brought ethnic cleansing in the former Yugoslavia (Bosnian War 1992–95; Kosovo 1998–99) and genocide in Rwanda (800,000 killed in 100 days, 1994) while the international community failed to intervene. The Gulf War (1990–91) expelled Iraq from Kuwait. The September 11 attacks (2001) launched the 'War on Terror': US-led invasions of Afghanistan (2001) and Iraq (2003), both ending in prolonged insurgencies. The Syrian Civil War (from 2011) has killed 500,000+ and produced 12 million refugees. Russia's annexation of Crimea (2014) and invasion of Ukraine (February 24, 2022) — Europe's largest war since 1945 — has killed hundreds of thousands and reshaped global security. Drone warfare, cyber attacks, and AI-enabled targeting are transforming the nature of conflict.",
    periods: [
      { name: 'Gulf War & Yugoslav Wars', start: 1991, end: 2000 },
      { name: 'War on Terror (Afghanistan, Iraq)', start: 2001, end: 2014 },
      { name: 'Syria, Ukraine & Modern Conflicts', start: 2011, end: 2025 },
    ],
  },
];
